### ISSUE TITLE
[New Theme Request] Duplicacy

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#100]
I've spent a while searching for a new backup solution, and after a lot of research, I settled on Duplicacy. It's quick and efficient with a good deal of granularity. It's also one of the only options that I know of that will dedup *across* backups, so if you push from two separate backup directories, it will actually use the same chunks in both backups if they are duplicates

It already comes with a very slick web UI, but it could benefit from a bit more theming. There are 5 tabs with a few popup modals.

https://hub.docker.com/r/saspus/duplicacy-web

![image](https://user-images.githubusercontent.com/39887349/95656498-73f96200-0ad4-11eb-9676-3b39120db7d6.png)
![image](https://user-images.githubusercontent.com/39887349/95656507-7c519d00-0ad4-11eb-87b2-1cd0ecac6d12.png)
![image](https://user-images.githubusercontent.com/39887349/95656513-84114180-0ad4-11eb-935c-b35865b94eb7.png)
![image](https://user-images.githubusercontent.com/39887349/95656522-92f7f400-0ad4-11eb-99b6-86fbaccbe809.png)
![image](https://user-images.githubusercontent.com/39887349/95656529-9ab79880-0ad4-11eb-8062-5fe09995a7c7.png)

**Comment by gilbN** [comment]
Added, but I dont use it, so let me know of any bugs
