### ISSUE TITLE
[Duplicacy] Clean up of various elements

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#102]
On the dashboard chart, you've inverted the chart, but it leads to the colors of the various line graphs to not match the legend. Removing the invert messes up the axis and the grid

```css
#chartStorages,
#chartBackups {
    filter: invert(100);
}
```

![image](https://user-images.githubusercontent.com/39887349/95663042-64444280-0b01-11eb-9b5b-69649e1c5609.png)
![image](https://user-images.githubusercontent.com/39887349/95663160-6b1f8500-0b02-11eb-9e82-8a5563db879b.png)

In Storages and Backups, you'd end up with cards on top of cards. This might be resulting in some visual quirks with the charts

![image](https://user-images.githubusercontent.com/39887349/95663080-acfbfb80-0b01-11eb-86c4-916b19cbaf26.png)

I was also unsure of how to fix the progress bars found when you backup/restore/run a schedule, though the default one isn't too far off in Organizr-Dark

![image](https://user-images.githubusercontent.com/39887349/95663139-272c8000-0b02-11eb-9c31-be11462b6d31.png)

Last one I couldn't fix was the mobile selected tab arrow is flipped on the sidebar menu, and the one from theme.park is appearing as well

![image](https://user-images.githubusercontent.com/39887349/95663156-53e09780-0b02-11eb-800b-a91d98181795.png)

**Comment by gilbN** [comment]
is this one okay now?

**Comment by rg9400** [comment]
Looks good to me

**Comment by gilbN** [comment]
Nice!
