### ISSUE TITLE
Transmission Plex theme - upload/download arrows the wrong way around

### ISSUE THREAD

**Issue by arbitrarypunter** [gilbN/theme.park#108]
On the transmission plex theme, the arrows that go with the upload/download rates are the wrong way around.
This is the original theme:
![transmission-orig](https://user-images.githubusercontent.com/73138663/96505992-cd892b80-124e-11eb-8f34-7d0572aadff3.PNG)
And this is the plex theme:
![transmission-tp-error](https://user-images.githubusercontent.com/73138663/96505997-ce21c200-124e-11eb-8ad9-43baec1f5aa5.PNG)
note that the uploading bandwidth now looks like it is downloading.

**Comment by gilbN** [comment]
Should be good now.

**Comment by arbitrarypunter** [comment]
All looks correct now - thanks very much!
