### ISSUE TITLE
Feature request: disk io

### ISSUE THREAD

**Issue by dc232** [gilbN/theme.park#112]
Hi was wondering if it would be possible to include disk io metrics for unraid

**Comment by gilbN** [comment]
?? What do you mean. This repo is for custom css.

**Comment by dc232** [comment]
sorry, I thought this repo was for grafana dashboards, please ignore

**Comment by gilbN** [comment]
I do have a grafana dashboard I've made. But I think that already has disk io panels. Can't remember. https://grafana.com/grafana/dashboards/7233

**Comment by dc232** [comment]
I just installed it but I don't see a disk io metric? maybe I'm looking in the wrong place?

**Comment by gilbN** [comment]
The disk read write panels.
![](https://selfhosted.app/f3c10/dALoHenO17.png/raw)

**Comment by dc232** [comment]
ah ok, thank you that makes sense
