### ISSUE TITLE
How to install to Tampermonkey/Userstyle format?

### ISSUE THREAD

**Issue by mkanet** [gilbN/theme.park#113]
I already have Tampermonkey installed on all my web browsers.  I was hoping for an easy way to install on Tampermonkey; so, it also automatically gets the updates.

I already tried Tampermonkey's **Utilities\Install from URL**, however, it didn't allow me to import the below URL:

https://gilbn.github.io/theme.park/CSS/themes/sonarr/plex.css

**Comment by gilbN** [comment]
Looks like Tamplermonkey is a script extention, so you'll need to create a javascript script that adds a stylesheet with the css url. 

This was the first google hit on "apple stylesheet using javascript" 

```js
(function() {
    'use strict';

    function addCss(fileName) {

  var head = document.head;
  var link = document.createElement("link");

  link.type = "text/css";
  link.rel = "stylesheet";
  link.href = "https://gilbn.github.io/theme.park/CSS/themes/sonarr/plex.css";

  head.appendChild(link);
}

addCss('{my-url}');
})();
```

**Comment by mkanet** [comment]
@gilbN Thank you so much for your help.  It doesn't seem to make any difference to my Sonarr UI after I add the code above as a Userscript.  I restarted my web browser.. but nothing changes on my Sonarr interface.  Is there something more I need to add?  BTW:  My Sonarr runs on TCP port **9989**.  Thanks again for your help.

**Comment by gilbN** [comment]
I updated the code 30? min ago. Did you try before or after that?

**Comment by mkanet** [comment]
Thanks for the quick reply back.  I just tried it again.. No difference at all.  This is what the userscript looks like below.  I didn't do anything else except point my web browser to:  **http://my-url.com:9989** after saving the script and restarting my web browser.
![Screenshot](https://user-images.githubusercontent.com/811008/98169545-5041f580-1ea1-11eb-8f26-9b612ca0b26b.png)

**Comment by gilbN** [comment]
Just tried again. And it works here. 
https://selfhosted.app/f3c10/JekuGUcu97.mp4

And if you have a webserver, why are you doing it this way? Why not just subfilter it?

**Comment by gilbN** [comment]
Lol I see your issue btw. Look at your @match line. It tries to apply it to this url..

![](https://selfhosted.app/f3c10/BuhoDebO37.png/raw)

**Comment by mkanet** [comment]
You are so awesome.  I really appreciate your help!  It works great!
