### ISSUE TITLE
Windows / Subfilter Method options

### ISSUE THREAD

**Issue by mkanet** [gilbN/theme.park#114]
My Sonarr and Radarr installations are on Windows.  I also have IIS Webserver installed for my webserver.  I'm curious if there are any Windows-friendly Nginx alternatives to use these themes on the server-side (in order to use these awesome themes on my mobile web browsers).

Currently, I use [Stunnel](https://www.stunnel.org/) as a proxy to add SSL to my IIS webpages.  However, I'm not sure if it will be able to help do what I want.

I would appreciate any suggestions that might help me on a Windows platform.

PS:  It looks like there is [Nginx for Windows](https://www.maketecheasier.com/install-nginx-server-windows/).  I'm guessing the instructions would still be similar regardless of what OS Nginx is installed on.

**Comment by gilbN** [comment]
Hi. Yes ngimx works well on windows. 
Check out https://github.com/elmerfdz/Organizr Installer

It will install ngimx and php for you. It will also add organizr which you might find interesting.

**Comment by gilbN** [comment]
Added wrong link

https://github.com/elmerfdz/OrganizrInstaller

**Comment by mkanet** [comment]
I just installed nginx by itself just as a test.  When I used the below code in nginx.conf's server section; and, start ngnix:

```
    server  #{
        listen       80;
        server_name  localhost;

        location /sonarr {
            proxy_pass http://localhost:9989;
            include /config/nginx/proxy.conf;
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/plex.css">
            </head>';
            sub_filter_once on;
        }
```
I get the error below:
```
nginx: [emerg] CreateFile() "C:/config/nginx/proxy.conf" failed (3: The system cannot find the path specified) in C:\Users\Michael\Downloads\nginx-1.18.0\nginx-1.18.0/conf/nginx.conf:41
```
It's complaining about the line:  `include /config/nginx/proxy.conf;`

If I comment out that line, nginx will start up just fine.  However, it doesn't change Sonarr's interface when I go to `http://localhost:9989` in a web browser.  Could you tell me what I'm doing wrong or missing?  Thank you for your patience in helping me.

**Comment by mkanet** [comment]
Thank you very much.  I was able to get it to work using Nginx for Windows (by itself).  I'm going to try it with Organizr next.. Thank you for your patience.. and, thank you for all your hard work!
