### ISSUE TITLE
Addon suggestion:  Sonarr V3 Calendar "Addon"

### ISSUE THREAD

**Issue by mkanet** [gilbN/theme.park#117]
Sonarr V3 Calendar is very hard to read due to it only using stripes instead of filling in the cells.  Please consider making this available as an addon.

**Before**
![Sonarr-Calendar-Old](https://user-images.githubusercontent.com/811008/98325297-53250f00-1fa3-11eb-89ea-65887de4dd57.png)

**After CSS mod**
![Sonarr-Calendar-New](https://user-images.githubusercontent.com/811008/98325317-5b7d4a00-1fa3-11eb-9ca5-53e9bedf7bed.png)

Below, is the code I used for this mod in nginx:
```
        location /sonarr {
            proxy_pass http://localhost:8989/sonarr/;
            include ./conf/proxy.conf;
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/organizr-dark.css">
            
            <style>
            .CalendarEvent\/downloaded\/2vSrJ {
                background: rgba(39, 194, 76, 0.7) !important;
                border-left-color: rgba(39, 194, 76, 0.0) !important;
            }

            .CalendarEvent\/missing\/1y6vZ {
                background: rgba(240, 80, 80, 0.7) !important;
                border-left-color: rgba(240, 80, 80, 0.0) !important;
            }

            .CalendarEvent\/unaired\/3aHdN {
                background: rgba(93, 156, 236, 0.7) !important;
                border-left-color: rgba(93, 156, 236, 0.0) !important;
            }

            .CalendarEvent\/unmonitored\/Zvc-m {
                background: rgba(173, 173, 173, 0.7) !important;
                border-left-color: rgba(173, 173, 173, 0.0) !important;
            }

            .CalendarEvent\/onAir\/dwaU_ {
                background: rgba(255, 165, 0, 0.7) !important;
                border-left-color: rgba(255, 165, 0, 0.0) !important;
            }

            .CalendarEvent\/downloading\/1kwSO {
                background: rgba(122, 67, 182, 0.7) !important;
                border-left-color: rgba(122, 67, 182, 0.0) !important;
            }
            </style>

            </head>';
            sub_filter_once on;
        }
```

**Comment by gilbN** [comment]
Looks good! Will add it this weekend if I get the time. Thanks.

**Comment by gilbN** [comment]
I added the changes to the base, so no need for the addon. 👍

**Comment by mkanet** [comment]
That's great. Thanks.  It is important to give the credit to **/u/hdmiusbc** from reddit:

https://www.reddit.com/r/sonarr/comments/jnnqkb/is_there_and_way_to_change_sonarr_v3_to_look_more/gb5tnqy?context=3

**Comment by jarlave** [comment]
Honestly, that change would have been better if it was an add-on. Sure it will work if you don't have much in your calendar, but look at this, this is just to much color for a dark theme IMHO....
![image](https://user-images.githubusercontent.com/3617501/98532485-0f235a00-2282-11eb-8197-22b9b64dd5df.png)
