### ISSUE TITLE
How to install on Microsoft IIS with URL Rewrite Module?

### ISSUE THREAD

**Issue by mkanet** [gilbN/theme.park#118]
I didn't see any installation instructions for Microsoft IIS web servers.  

I am able to set up reverse proxies for sonarr/radarr using IIS + URL Rewrite module relatively easily by following the instructions below.  However, I still don't know how to add the respective CSS mod necessary to use these awesome themes.  Any help would be appreciated!

[Setting up a HTTPS reverse proxy with IIS for Radarr and Sonarr | by Jett Jackson | Medium](https://medium.com/@jettjackson/setting-up-a-https-reverse-proxy-with-iis-for-radarr-and-sonarr-a381fbdb5396#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ5NDZiMTM3NzM3Yjk3MzczOGU1Mjg2YzIwOGI2NmU3YTM5ZWU3YzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2MDUxNTg1ODYsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwNjAyNDE1OTI1NDA3ODI5ODQyMCIsImVtYWlsIjoibWljaGFlbC5hdmFuZXNzaWFuQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiTUtBIE5FVCIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHanVvY25uZXUwdzJrZmJtNC12LWM5T0ZfUjBkcW95a0pxVWR2NTNIQT1zOTYtYyIsImdpdmVuX25hbWUiOiJNS0EiLCJmYW1pbHlfbmFtZSI6Ik5FVCIsImlhdCI6MTYwNTE1ODg4NiwiZXhwIjoxNjA1MTYyNDg2LCJqdGkiOiI2ZTQzZjVlYTg1Zjc3YWY4MzllYjQ3ZDU5ZTY0Nzk2MjJmZGQyYTVjIn0.QJUyuUe-60odnUMb3iVs-a_8ZW5jbeaT-s9BcBwI5FoX-MhQejjbW3yltRc5RYBhxT41i0QMmQNhmrHMoE2F9qowLwUuvLVcdrr-EQJy_bmvvrAPKkcTDH9FF5ICCEmwPGckzHOCA4Ics3U9Obmfb8RqnMnyDBy2yABpLYVLYe33oDhLrEUcn7KMKDMElQMtqxtxDBeilULJQZxFqpAO8zo796PKaQzxbaN_-Zh0cItGgIfjB4ZairPQ0xPA8ZsxXNtTg8Ge67V6plW5VrQd1iQHKmrFf94MK8LV_sdQ46JuFj5-9Bm4yRvmHMlYrdOEczydhZYnwnJXtLZ8GhC7rA)

I also asked a [similar question](https://stackoverflow.com/questions/64813895/converting-nginx-reverse-proxy-with-css-filter-to-iis10-url-rewrite) on StackOverflow.

**Comment by gilbN** [comment]
I've never used IIS, so you need to see if you can find something similar to 

https://nginx.org/en/docs/http/ngx_http_sub_module.html
https://httpd.apache.org/docs/2.4/mod/mod_substitute.html
https://github.com/echocat/caddy-filter
https://github.com/sjtug/caddy2-filter

**Comment by mkanet** [comment]
Thank you @gilbN.  If I figure out a straight forward solution, I'll let you know so you can add IIS to your installation instructions.   I'm going to close this issue since I'm not sure if/when I'll have a solution.
