### ISSUE TITLE
Plex Theme Calibre-Web doesn't work

### ISSUE THREAD

**Issue by virusperfect** [gilbN/theme.park#119]
This link doesn't work: https://gilbn.github.io/theme.park/CSS/themes/calibreweb/plex.css

**Comment by gilbN** [comment]
Error in the wiki. There is no plex.css

Its based on CaliBlur that is a plex theme for Calibre. 

Set theme to CaliBlur in UI Configuration -> View Configuration -> Theme -> CaliBlur -> Submit
