### ISSUE TITLE
[New Theme Request] Traefik Proxy

### ISSUE THREAD

**Issue by IntermittentlyRupert** [GilbN/theme.park#120]
Would be great to be able to have Traefik look consistent with the services I run through it!

https://github.com/traefik/traefik

**Comment by gilbN** [comment]
But how will you apply the theme using træfik? 😛. https://github.com/gilbN/theme.park/issues/42

**Comment by IntermittentlyRupert** [comment]
😄 

I've actually got plugin-rewritebody working for most containers (I use Stylus for the rest). I haven't run into any issues with traefik/plugin-rewritebody#12 - matching on `</head>` seems to work fine. traefik/plugin-rewritebody#13 is what's actually causing issues for several of my containers. Happy to share a minimal example in #42 if that'd be useful?

**Comment by gilbN** [comment]
> 😄
> 
> I've actually got plugin-rewritebody working for most containers (I use Stylus for the rest). I haven't run into any issues with [traefik/plugin-rewritebody#12](https://github.com/traefik/plugin-rewritebody/issues/12) - matching on `</head>` seems to work fine. [traefik/plugin-rewritebody#13](https://github.com/traefik/plugin-rewritebody/issues/13) is what's actually causing issues for several of my containers. Happy to share a minimal example in #42 if that'd be useful?

Yeah, that'd be great. I dont use Træfik, but it will definitvely be helpful for others! We can add it to the wiki too.

**Comment by GilbN** [comment]
As I dont use træfik, I'm closing this.
