### ISSUE TITLE
Apache2 example is incorrect

### ISSUE THREAD

**Issue by WintyBe** [gilbN/theme.park#123]
I'm probably the only one still using Apache2 instead of nginx, so I noticed the example code has some typo's in it (that seem copy/pasted from the nginx bit). 
mod_substitute uses 's/pattern/substitution/[infq]', so in this case the default `</head>` is replaced with `CSS LINK</head>`. _ni_ forces it to be case insensitive and looks for a string instead of a regex. | replaces / because of slashes being in the tags. 

Docs are here: https://httpd.apache.org/docs/2.4/mod/mod_substitute.html if needed to verify.

This should be the correct code block:
```
  AddOutputFilterByType SUBSTITUTE text/html
  Substitute 's|</head>|<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/<APP_NAME>/THEME.css"></head>|ni'
```

And this as example:
```
<Location /sonarr>
    ProxyPass http://localhost:8989/sonarr
    ProxyPassReverse http://localhost:8989/sonarr
    AddOutputFilterByType SUBSTITUTE text/html
     Substitute 's|</head>|<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/plex.css"></head>|ni'
  </Location>
```

**Comment by gilbN** [comment]
Thanks! I'll update the wiki

**Comment by WintyBe** [comment]
An extra sidenote maybe, I had to add this bit in my <Location> config as well or the theme simply wouldn't work:
`RequestHeader unset Accept-Encoding`

This prevents Apache from sending a gzipped response - preventing it from replacing the code. But I'm not sure if this will be the case for everyone.

**Comment by gilbN** [comment]
Cool, I'll add it 👍
