### ISSUE TITLE
Bitwarden Admin Page - Eye Cancer

### ISSUE THREAD

**Issue by angrycuban13** [gilbN/theme.park#127]
Bitwarden admin page is blindingly white when using `organizr-dark.css`

**Comment by tronyx** [comment]
+1 for dis.

So much eye cancer. Like being flashbanged after being hoodwinked for a week.
![eye-bleach](https://user-images.githubusercontent.com/22502007/102702826-2f591800-4235-11eb-890b-84337805c00e.png)

**Comment by gilbN** [comment]
Where is this menu? I dont have it.

**Comment by tronyx** [comment]
It's the admin menu. Append /admin to your URL and login with your admin token.

**Comment by gilbN** [comment]
https://github.com/gilbN/theme.park/commit/539c8ad489efa1ee06b4a4cb7eb4be5ab8755d68 check it

**Comment by tronyx** [comment]
Looks great to me. Thanks!
