### ISSUE TITLE
Duplicacy Admin Auth Page

### ISSUE THREAD

**Issue by angrycuban13** [gilbN/theme.park#128]
When using `organizr-dark.css` and setting authentication with Duplicacy my eye cells die

**Comment by gilbN** [comment]
![](https://media1.tenor.com/images/8644747a2e6c73bc21930425ef8ea3a5/tenor.gif?itemid=15607548)

**Comment by gilbN** [comment]
Where is the menu, I dunt use it.

**Comment by angrycuban13** [comment]
If you enable the administration password on it under `Settings` when you visit `duplicacy.domain.com` you'll get the page
