### ISSUE TITLE
[New Theme Request] Nginx Proxy Manager

### ISSUE THREAD

**Issue by Aesthetic1** [GilbN/theme.park#129]
I love these themes and I’m using the dark theme for everything I can.
Having the themes available for Nginx Proxy Manager too would be awesome!

https://github.com/jlesage/docker-nginx-proxy-manager

**Comment by gilbN** [comment]
There are instructions for npm in the wiki. https://github.com/gilbN/theme.park/wiki/Setup#nginx-proxy-manager

**Comment by Aesthetic1** [comment]
Maybe I didn’t express myself right.. I meant a theme for NPM itself.. :)

**Comment by C-Fu** [comment]
This would be awesome!

**Comment by Hukuma1** [comment]
+1!

**Comment by norsemanGrey** [comment]
Oh, yes please :D

**Comment by Monklite** [comment]
Agreed, has to happen lol seems great

**Comment by GilbN** [comment]
develop.theme-park.dev has a theme available now

**Comment by GilbN** [comment]
Merged to master
