### ISSUE TITLE
[Bug] qBit 4.3.2 theme break RSS tab

### ISSUE THREAD

**Issue by Sinderella** [gilbN/theme.park#132]
Hello,

I just attempted to use a theme in qBit 4.3.2, but this message occurs whenever I applied one of the themes. The following error messages occur when I load the page itself.

```
Uncaught SyntaxError: '' string literal contains an unescaped line break
```

Full traces:
![image](https://user-images.githubusercontent.com/1926450/103231030-bccff280-492e-11eb-96eb-95bec38e924d.png)

This renders RSS tab no longer accessible. When I click on the RSS tab, I get the following traces.

```
Uncaught TypeError: window.qBittorrent.Rss is undefined
```

Full traces:
![image](https://user-images.githubusercontent.com/1926450/103230984-9f9b2400-492e-11eb-9896-4c932eaaf927.png)

My nginx config:

```
location /qbittorrent/ {
    proxy_pass              http://$remote_user.qbittorrent;
    proxy_http_version      1.1;
    proxy_set_header        X-Forwarded-Host        $http_host;
    http2_push_preload on; # Enable http2 push
    auth_basic "What's the password?";

    proxy_set_header Accept-Encoding "";
    sub_filter
    '</head>'
    '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/qbittorrent/space-gray.css">
    </head>';
    sub_filter_once on;

    proxy_hide_header   "x-webkit-csp";
    proxy_hide_header   "content-security-policy";

    auth_basic_user_file /etc/htpasswd;
    rewrite ^/qbittorrent/(.*) /$1 break;
}
```

Note that the RSS tab became accessible when I remove the `sub_filter` from nginx.

Please let me know if you need any more information. I did try to debug it but I never thought CSS could break the functionality, could be one of the unicodes?

Thank you for beautiful themes!

**Comment by Sinderella** [comment]
@gilbN using `sub_filter` to replace `<noscript>` tag instead of the `</head>` tag fixed the issue for me. basically move the tag to group with other css files before javascript script tags.

**Comment by gilbN** [comment]
> @gilbN using `sub_filter` to replace `<noscript>` tag instead of the `</head>` tag fixed the issue for me. basically move the tag to group with other css files before javascript script tags.

Awesome! @rg9400 can you try this?

**Comment by rg9400** [comment]
Yeah, this fixed the issue for me

**Comment by rcdailey** [comment]
Can someone provide a verbatim `theme-park.conf` for this? I am not familiar with `sub_filter`, my attempt at this change did not work:

```
proxy_set_header Accept-Encoding "";
sub_filter
'<noscript>'
'<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/$app/$theme.css">
<noscript>';
sub_filter_once on;
```

**Comment by rg9400** [comment]
Yes, you want to keep those first two headers in qbt only. You also don't want to use this subfilter globally, so just hardcode it into qbt vs doing an include of `teme-park.conf`. 

I have no idea why doing it at the end of the `<head>` tag causes issues. Possibly, something is happening to the tab elements via javascript now.
