### ISSUE TITLE
How to install with a Feralhosting server

### ISSUE THREAD

**Issue by From2750** [gilbN/theme.park#134]
Hello, 

if i have a feralhosting server, how to i install the theme pack? im mosly looking for theme to rutorrent and deluge

**Comment by gilbN** [comment]
Check the wiki. Installation methods are there.

**Comment by gilbN** [comment]
Since you can do custom domains, I'm guessing you can edit the nginx configs to add the themes too. 
https://www.feralhosting.com/wiki/slots/custom-domain

**Comment by From2750** [comment]
Okay thanks, i will give it a try, i not so good with linux and ssh, but i give et a try, :)
