### ISSUE TITLE
The Lounge Mentions Popout

### ISSUE THREAD

**Issue by Dulanic** [gilbN/theme.park#136]
There is a issue /w thelounge dark theme /w the mentions popout. It doesnt effect dark organizr so i assume it has to do with the radiant gradiant in that theme. It does effect dark.  I am able to fix it by adding this, but I think you'd probably have a better way.

```
.mentions-popup {
   background:#1f1f1f
}
```
Without fix:
![image](https://user-images.githubusercontent.com/2948206/104136664-33bcb080-535d-11eb-9ee0-628a8eacd70e.png)

With fix:
![image](https://user-images.githubusercontent.com/2948206/104136647-1f78b380-535d-11eb-83d0-562487418c11.png)

**Comment by gilbN** [comment]
Thanks for the issue, can you clear cache to see if its fixed now? Might take a minute or two.

**Comment by Dulanic** [comment]
All good, thanks for the super fast fix!

**Comment by Dulanic** [comment]
Actually going to reopen... there is another part that needs a fix, class="toggle-content toggle-type-link"

![image](https://user-images.githubusercontent.com/2948206/104137420-15a57f00-5362-11eb-8416-2e77d063a8a1.png)

**Comment by Dulanic** [comment]
Closing /w merge.
