### ISSUE TITLE
[Sonarr] Issues w/ Scene Info Icon

### ISSUE THREAD

**Issue by tronyx** [gilbN/theme.park#142]
Looks like with the addition of the Scene Info icon the theme has developed issues with the row lines:

https://sharex.tronflix.app/zORI8/MEdoTUVU93.png

Versus a theme that shows the Scene Info icons:

https://sharex.helflix.app/Waxo2/lIqAyAHA69.png

**Comment by gilbN** [comment]
Scene info icon should be good now.

**Comment by tronyx** [comment]
It is, thank you. Need to see if anyone else is having the row line issues. I'm not adding anything custom on my side, but I'll try inspecting different things and see if I can find anything.

**Comment by gilbN** [comment]
Still an issue?

**Comment by tronyx** [comment]
The lines not lining up is still an issue, yes.

**Comment by gilbN** [comment]
Looks like a Firefox issue to me. 
![](https://selfhosted.app/f3c10/qafaFIhe75.png/raw)

**Comment by tronyx** [comment]
Firefox issue as in something needs to be added/adjusted with the theme or Mozilla needs to fix it?

**Comment by gilbN** [comment]
> Firefox issue as in something needs to be added/adjusted with the theme or Mozilla needs to fix it?

Yeah. Rendering issue by Firefox since it happens when not using the theme too.

**Comment by tronyx** [comment]
Got'cha. Will close this.
