### ISSUE TITLE
[Lidarr] Dark Theme Has Blanks on Delay Profile Window

### ISSUE THREAD

**Issue by angrycuban13** [GilbN/theme.park#144]
## Steps to Replicate

Lidarr > Settings > Profile > Delay Profiles > Click Wrench 

![rekt](https://sharex.angrycuban.xyz/XExe1/LEkeHUZa05.png/raw)

**Comment by gilbN** [comment]
notetoself; Need to run the  pr-profile tag

**Comment by GilbN** [comment]
Has this been merged yet?

**Comment by angrycuban13** [comment]
Don't think so, let me check

**Comment by GilbN** [comment]
Can't replicate, tested on :testing and :nightly
