### ISSUE TITLE
Sabnzbd Plex theme some of the letters are dark on dark background.

### ISSUE THREAD

**Issue by bbaraniec** [gilbN/theme.park#146]
Love this theme but there are two things that are hard to read. I've marked them with red circle on screenshot below, can that be changed?
![Screenshot 2021-02-01 130505](https://user-images.githubusercontent.com/4579438/106526159-6897cf80-64e5-11eb-8409-53751dd43f63.png)

**Comment by gilbN** [comment]
Thanks, I'll have a look later. I currently use nzbget so need to setup sab again. If you feel like it you can try and inspect those elements in the browser and find the class or id for those icons.

**Comment by bbaraniec** [comment]
Was able to find the 2nd one:

<div class="processing-download">
                            <div class="loader-bar-one"></div>
                            <div class="loader-bar-two"></div>
                            <div class="loader-bar-three"></div>
                            <div class="loader-bar-four"></div>
                        </div>

**Comment by bbaraniec** [comment]
@gilbN did you have a chance to look into i?

**Comment by gilbN** [comment]
Sorry haven't had any time yet. 

If you install the styulus plugin you can try and add this :

```css
.direct-unpack,
.processing-download {
color: #eee;
}
```
If that works, I'll push that :)
