### ISSUE TITLE
NPM install method breaks access list

### ISSUE THREAD

**Issue by TheWizKid95** [gilbN/theme.park#147]
Can someone else with this install method replicate this issue? 

Seems enabling the skin renders the access list useless. My main concern is Pi-hole, but it happens with others as well. As soon as you delete the custom location and then refresh from a device that is NOT in the allowed networks you get the 403 http error as expected.

**Comment by gilbN** [comment]
I don't use NPM , but I guess you can add the allow list stuff in the custom location.
