### ISSUE TITLE
[New Docker Mod] qBittorrent

### ISSUE THREAD

**Issue by IntermittentlyRupert** [gilbN/theme.park#148]
From discussion on #42:

@beloso
> Sorry for highjacking this. But do you have a rewrite example for Qbittorrent?
> 
> I was able to get the themes to working with Stylus + Middleware for the headers needed to hide.
> I'd like to keep it all within the Middleswares
> 
> ...
> 
> I researched a bit on doing a Mod, but I can't seem to find the default index.html for qbittorrent. It might be because I am not that well versed in how this is set up. If someone can point me in the right direction, I'd be happy to try my hand at this.

**Comment by IntermittentlyRupert** [comment]
I've searched the container and I can't find the WebUI HTML files from the qBittorrent repo. Based on the installation guide for [iFelix18/Dark-qBittorrent-WebUI](https://github.com/iFelix18/Dark-qBittorrent-WebUI#installation-one-of-two-ways) I'd guess they're compiled into the binary or something. So part of the docker mod would need to be downloading one of the Alternate WebUIs.

**Comment by gilbN** [comment]
Cool, I'll check it out

**Comment by gilbN** [comment]
Looks promising, I can enable everything using the qbitorrent.conf file 👍

**Comment by beloso** [comment]
I made this custom WebUI based on `organizr-dark`. It seems to work.
The hard part for me would be to script this to accept the appropriate ENV Flags.

[themePark.zip](https://github.com/gilbN/theme.park/files/5977636/themePark.zip)

PS: Feel free to use this zip file.

**Comment by gilbN** [comment]
> I made this custom WebUI based on `organizr-dark`. It seems to work.
> The hard part for me would be to script this to accept the appropriate ENV Flags.
> 
> [themePark.zip](https://github.com/gilbN/theme.park/files/5977636/themePark.zip)
> 
> PS: Feel free to use this zip file.

How do you apply this?

**Comment by beloso** [comment]
@gilbN I opened a PR (#149) for this, unsure you want to go over it.

I was unable to test it. But I'm willing to iterate on it to make it better.

**Comment by gilbN** [comment]
@IntermittentlyRupert There is a tag avaialble now. @beloso  Your PR looks to be working perfectly, just made som changes to the init file. 

tag: `gilbn/theme.park:qbittorrentpr`

**Comment by gilbN** [comment]
Let me know if it works and I'll merge docker-mods-pr into docker-mods

**Comment by beloso** [comment]
Great, glad I could help somewhat. I kinda wish qbittorrent had a better way of doing it though.

**Comment by gilbN** [comment]
> Great, glad I could help somewhat. I kinda wish qbittorrent had a better way of doing it though.

Yeah.

I have one more thing I'm going to add before merging. Adding the downloading of the public/private files ect in the dockerfile config

**Comment by beloso** [comment]
There is an extra `\n` in there.

https://github.com/gilbN/theme.park/blob/b8bdda6335edae16326ba6c21e4a6d75b563034f/qbittorrent/root/etc/cont-init.d/98-themepark#L46

**Comment by beloso** [comment]
Other than that it is working for me as well. Thanks for the help debugging it.

**Comment by gilbN** [comment]
Merged it to docker-mods. Available on `gilbn/theme.park:qbittorrent`

Thanks again for the help @beloso 👍
