### ISSUE TITLE
Unraid theme applying colours to logo and top bar

### ISSUE THREAD

**Issue by bobokun** [gilbN/theme.park#157]
I recently applied the organizr-dark theme and noticed that the unraid logo does not look the same as the one in your sample screenshots.

![image](https://user-images.githubusercontent.com/12660469/110968867-09b84800-8326-11eb-9495-e6e3bf3707ae.png)
As well as the bar:
![image](https://user-images.githubusercontent.com/12660469/110968880-0cb33880-8326-11eb-8760-464b1934cdf5.png)

From Sample photos:
![image](https://user-images.githubusercontent.com/12660469/110968991-2c4a6100-8326-11eb-950d-6c83db9a2644.png)
![image](https://user-images.githubusercontent.com/12660469/110969019-33716f00-8326-11eb-888a-da5cae494dc3.png)

**Comment by gilbN** [comment]
Solved by adding 
```html
#header path {
    fill: url(#header-logo) !important;
}</style><link type="text/css" rel="Stylesheet" href="https://gilbn.github.io/theme.park/CSS/themes/unraid/<THEME>.css"/>
```
