### ISSUE TITLE
[Unraid] - Dark text on dark background on FCP

### ISSUE THREAD

**Issue by bobokun** [gilbN/theme.park#158]
Currently using https://gilbn.github.io/theme.park/CSS/themes/unraid/organizr-dark.css

Could be a specific issue but under FixCommonProblems plugin and clicking "What is Checked" will show dark text on a dark background.

![image](https://user-images.githubusercontent.com/12660469/111171679-84c66c00-857b-11eb-9dba-b3c9608a903b.png)

**Comment by gilbN** [comment]
Thanks, will have a look later!
