### ISSUE TITLE
[qBittorrent] Some dialog text are hard to read

### ISSUE THREAD

**Issue by sarbian** [gilbN/theme.park#159]
The text color for the "File->Add Torrent File" and "Add Category" dialogs are hard to read and do not change with the selected theme. With themes other than dark the text is nearly invisible.
They use the default Body color.

![image](https://user-images.githubusercontent.com/4083375/111307447-c0cffe80-8659-11eb-8f0c-10d990e509c6.png)

**Comment by gilbN** [comment]
@sarbian which installation method did you use?

**Comment by sarbian** [comment]
Sorry, I should have added more details.
Docker mods with the lsio image (ghcr.io/linuxserver/qbittorrent) 
DOCKER_MODS=gilbn/theme.park:qbittorrent
TP_THEME=dark

**Comment by gilbN** [comment]
ok, think I know why it happens. That box is an iframe. So the stylesheet doesnt get applied to it using that method. Will need to sed the stylesheet into the iframe html too.

**Comment by gilbN** [comment]
@sarbian recreate the container now and it should be good.

**Comment by sarbian** [comment]
Thanks. It fixed the Add Torrent File, but the Add Category is still the same. Right-click on the "All" category to open this one.
