### ISSUE TITLE
Plex space-grey theme update accent colors

### ISSUE THREAD

**Issue by AquaRelliux** [gilbN/theme.park#160]
Hello Gilbn

First of all the work here is awesome! I do however have one problem with the plex theme and that is the accent colors on new items are not that clearly visible with this theme. I suggest change it to red so it matches the radarr and sonarr configs? This is the problem I am thinking about:

![image](https://user-images.githubusercontent.com/15650734/111386658-d884a280-86ac-11eb-8eda-c2752613f173.png)

Would be much easier to see if it was red instead!

**Comment by gilbN** [comment]
Yeah, changed to color now. Clear cache

**Comment by AquaRelliux** [comment]
Thanks looks awesome! However it does not work in libraries only the home tab:

![image](https://user-images.githubusercontent.com/15650734/111536409-80ac7100-876a-11eb-9c2a-7e7e46c93057.png)

Also I think these could do with a more alert color:

![image](https://user-images.githubusercontent.com/15650734/111536509-9b7ee580-876a-11eb-8465-4a91338d2301.png)

![image](https://user-images.githubusercontent.com/15650734/111536551-ac2f5b80-876a-11eb-942a-d006c580b850.png)

![image](https://user-images.githubusercontent.com/15650734/111536574-b5202d00-876a-11eb-94a2-ef67a4dd356b.png)

I suggest green for these as well :)

**Comment by gilbN** [comment]
tried brightening up the variables

**Comment by AquaRelliux** [comment]
Looks great now only one more small thing :)

![image](https://user-images.githubusercontent.com/15650734/111596827-df570680-87cd-11eb-8108-650e76091c66.png)

**Comment by gilbN** [comment]
Should be good now.
