### ISSUE TITLE
Unraid theme header colors not updating

### ISSUE THREAD

**Issue by JDFS404** [gilbN/theme.park#161]
When using i.e. Plex Unraid theme, the header in Unraid (with the logo and name of Unraid Server) is not correctly updating. I.e. this is how it looks with BrushThreesDark and Plex theme:

![image](https://user-images.githubusercontent.com/26678110/111515593-4388b480-8753-11eb-928f-f84e0c7de69f.png)

So my question is, besides using Dark as the Base Theme, what are the other theme settings? Because I cannot seem to get to get the header fitting as in your screenshots.

I think the problem is caused by using a saved theme, and then pasting your code...

By the way: love your work and am a big advocate of it!

**Comment by gilbN** [comment]
I pushed a fix for the header, but you should also set `Enable Theme Engine:` to `no`

**Comment by JDFS404** [comment]
Thanks, I think we're almost there - when I disable the theme engine and only apply custom styling, my header now looks like this with the Organizr Dark theme:

![image](https://user-images.githubusercontent.com/26678110/111529371-5e165a00-8762-11eb-8e1f-25056c63747a.png)

I tried it with Dark, alas, same result:

![image](https://user-images.githubusercontent.com/26678110/111529548-93bb4300-8762-11eb-8e2e-d3b85ee19a26.png)

Are there certain header settings that we should be aware about?

**Comment by gilbN** [comment]
try and press clear settings and apply the theme again. 
![]( https://selfhosted.app/f3c10/daMiqAgo76.png/raw)

**Comment by gilbN** [comment]
Ah, I see now that I had some custom styling on.

**Comment by gilbN** [comment]
In settings -> DisplaySettings set `Header custom text color:` to white

**Comment by JDFS404** [comment]
Thanks! This did the trick for now, I changed it myself in HTML code to match with Organizr's color. Do you know if this is a Unraid bug - because the header has changed since 6.9.0 right?

**Comment by gilbN** [comment]
yeah, Unfortunatley I can't change it with the theme as its a shadow DOM with its own body. https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
