### ISSUE TITLE
[Unraid] - Unable to see text on MyServers plugin

### ISSUE THREAD

**Issue by bobokun** [gilbN/theme.park#163]
Hard to read text on the top after installing My Servers.
Using organizr-dark theme.

![image](https://user-images.githubusercontent.com/12660469/111875504-82478600-8970-11eb-8556-ebac07a254d6.png)

**Comment by gilbN** [comment]
Hi. Try and follow all the steps here. https://github.com/gilbN/theme.park/wiki/Unraid#theme-engine

**Comment by bobokun** [comment]
yup fixed it! Thanks
