### ISSUE TITLE
Pixelated banner unraid after adding custom theme

### ISSUE THREAD

**Issue by AquaRelliux** [gilbN/theme.park#165]
Hey gilbN

I added your theme for urnaid today using the plugin. But I have one issue my banner is now all pixlated? What could cause this? It worked before I added the theme:

![image](https://user-images.githubusercontent.com/15650734/112750200-7b9bbd00-8fc7-11eb-940a-489b8ff87142.png)

**Comment by gilbN** [comment]
Yeah, think I know why.

**Comment by AquaRelliux** [comment]
Cool is there a way to fix it?

**Comment by gilbN** [comment]
Can you try and disable and re enable the custom banner.

**Comment by AquaRelliux** [comment]
I tried that also I changed back to the original banner for unraid still was an issue with it

**Comment by gilbN** [comment]
Try and clear cache now

**Comment by AquaRelliux** [comment]
It works but now the font is removed here:

![image](https://user-images.githubusercontent.com/15650734/112906021-c44c9680-90eb-11eb-8dec-f3f0517e9c32.png)

**Comment by gilbN** [comment]
yeah removed the accent on the logo. Figured it would be hard to read on some banners
If you want to add it back: 

```html
#header path {
    fill: var(--accent-color);
}
</style><link type="text/css" rel="Stylesheet" href="https://gilbn.github.io/theme.park/CSS/themes/unraid/space-gray.css" />
```

**Comment by AquaRelliux** [comment]
Yea I get what you mean:

![image](https://user-images.githubusercontent.com/15650734/112975055-7e2b1d80-9153-11eb-9780-a267ecab3f31.png)

Pretty hard to read this text also

**Comment by Glasti1** [comment]
doesn't seem to happen with my space-gray them when i add those lines
![image](https://user-images.githubusercontent.com/57273176/112975632-2e992180-9154-11eb-8e4a-6faa1f7d065c.png)

**Comment by Glasti1** [comment]
maybe a browser limitation?

**Comment by AquaRelliux** [comment]
![image](https://user-images.githubusercontent.com/15650734/113004114-a3c81f00-9173-11eb-83e6-a054f40409f8.png)
Tried edge just for the hell of it and it is the same on both Chrome and Edge

**Comment by Glasti1** [comment]
maybe it is worth to reinstall the Theme Engine plugin..

**Comment by AquaRelliux** [comment]
I actually tried that no luck :( it seems this problem is persistent over all themes for me the text is black instead of white which makes it hard to read

**Comment by gilbN** [comment]
Can you inspect the element to see what's overriding it?

**Comment by AquaRelliux** [comment]
> Can you inspect the element to see what's overriding it?
> It does look like some weird cache issue though.

![image](https://user-images.githubusercontent.com/15650734/113064289-042c8000-91b7-11eb-86f5-31896cdfba0c.png)
Is this what you want to see?

**Comment by gilbN** [comment]
Something like this: 
![](https://selfhosted.app/f3c10/YonOSuBA47.png/raw)

**Comment by gilbN** [comment]
@AquaRelliux try and clear cache now

**Comment by AquaRelliux** [comment]
> @AquaRelliux try and clear cache now

Seems to work now thank you :)
