### ISSUE TITLE
Calibre Book Details View reverts to default theme when infinite scroll refreshes.

### ISSUE THREAD

**Issue by cbartondock** [gilbN/theme.park#168]
Hard to describe the issue exactly without showing it to you, so here is a recording of what I mean:

https://user-images.githubusercontent.com/4482454/112770893-f16b4d00-8ff6-11eb-874d-7aded7b225ac.mp4

**Comment by cbartondock** [comment]
I fixed this in my PR to calibre web. It was their issue not yours.

**Comment by gilbN** [comment]
@cbartondock awesome!
