### ISSUE TITLE
Gitea Theme : Some differences between your screenshots and mine

### ISSUE THREAD

**Issue by MilesTEG1** [GilbN/theme.park#170]
Hello @gilbN ,

I've got some differences between your screenshots and mine.
First, I use Gitea in Docker, installed on my Synology NAS. Everything is working fine.
The volumes I set in my docker-compose.yml file :
```yaml
    volumes:
      - "/volume1/docker/gitea/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
```

---

## 1.  Following your installation instructions

If I follow your installation guide, and let my default theme to "arc-green" (from gitea), I got this for the plex theme :
![image](https://user-images.githubusercontent.com/29298312/113587204-bd171280-962e-11eb-854c-57837a7120ac.png)
Or this for the spece gray theme :
![image](https://user-images.githubusercontent.com/29298312/113587518-2f87f280-962f-11eb-9446-7796e81697aa.png)

That's not very important, but it differs in : 
- the background of the file list 
- the buttons HTTPS : the button background is colored for me, and not for yours.
- the download buttons aren't the same too.

If I set the theme to gitea, and not arc-green, I've got the same background in file list.

Ok, that's not major changes, but is that normal ? 

---

## 2. Following another method I create to have all your theme available for anyone

I have to explain what I did. I hope my explanations will be clear... I'll do my best.

So I download all your 6 gitea's themes css files  :
![image](https://user-images.githubusercontent.com/29298312/113589972-54ca3000-9632-11eb-8fea-6c86fa6e600d.png)
and put them into my `/docker/gitea/data/gitea/public/css` folder.

After several researches, (not easy to find what variable refers to the user theme, like the `{{AppSubUrl}}` variable you used), I managed to adapt your `header.tmpl` file like this :
```html
<!--
// Copie de la méthode d'installation qui ne laisse aucun choix à l'utilisateur
<link rel="stylesheet" href="{{AppSubUrl}}/styles.css">
-->
<link rel="stylesheet" href="{{AppSubUrl}}/css/{{DefaultTheme}}.css">
<link rel="stylesheet" href="{{AppSubUrl}}/css/{{.SignedUser.Theme}}.css">
```
I put this file into `/docker/gitea/data/gitea/templates/custom/` folder.

And I add this to the `/docker/gitea/data/gitea/conf/app.ini` file :
```ini
[ui]
THEMES        = gitea,arc-green,plex,aquamarine,dark,hotline,organizr-dark,space-gray
DEFAULT_THEME = arc-green
```

And now, all my users (ok, there is only me 😄 ) can change the theme in `Settings / Account / Select default theme` :
![image](https://user-images.githubusercontent.com/29298312/113592003-e9ce2880-9634-11eb-84f7-5e7cc4eb53f2.png)

I'm not sure if my method is the right one, but it seems to be working fine.

The file list backgound is now like open your screenshots. (I honestly prefer it when the background of the file list is darker, like in my previous captures :sweat_smile: )

But as before I have some little differences :
- the buttons HTTPS : the button background is colored for me, and not for yours.
- the download buttons aren't the same too,
- the "New File button" have a thin white/grey vertical bar at its left.

Here two screenshots made with plex and space-grey theme :
![image](https://user-images.githubusercontent.com/29298312/113593001-2c443500-9636-11eb-87fa-e651eb1ed44f.png)
![image](https://user-images.githubusercontent.com/29298312/113593019-31a17f80-9636-11eb-8c70-9502965b554e.png)

Are those differences normal ? Is it possible to correct it if it's not ?
And, the best question for the end : is my method correct ? 
(If it is, you can copy it into your instructions :wink: ).

Thanks for reading my big message, and thanks for your help.
Bye :wave:

**Comment by gilbN** [comment]
Looks like they have updated the gui. What version are you using? Theme was made on Version: 1.13.0+rc2

**Comment by MilesTEG1** [comment]
I'm using `Gitea Version: 1.15.0+dev-65-g0bb8bd819`.

**Comment by gilbN** [comment]
yeah, try gitea latest. https://github.com/go-gitea/gitea/releases/tag/v1.13.6

**Comment by gilbN** [comment]
the tag :latest will install the current development version. For a stable release you can use :1 or specify a certain release like :1.13.6.

**Comment by MilesTEG1** [comment]
Ho ! I didn't notice I wasn't on a stable version !!!
I'm using the :latest in my docker-compose :

**Comment by MilesTEG1** [comment]
It's too bad the `gitea/gitea:latest` isn't pointing to the last stable version...

**Comment by gilbN** [comment]
All in the docs :) https://docs.gitea.io/en-us/install-with-docker/#basics

**Comment by MilesTEG1** [comment]
Thanks for the link, I already follow it, but putting latest instead of a fixed version...
But I didn't give attention to this :

> Also be aware that the tag :latest will install the current development version. For a stable release you can use :1 or specify a certain release like :1.13.6.

And now, with the 1.13.6 version, my Gitea won't start because of this error :
![image](https://user-images.githubusercontent.com/29298312/113599027-513ca600-963e-11eb-92b5-d7fcc83680a8.png)

I wouldn't like loosing my works... by downgrading the database...
Is there a workaround ? (I knwo it's not yours to correct ;) ) but thanks in advance.

**Comment by gilbN** [comment]
Sorry, not sure. 
You could ask here though. https://discord.com/invite/Gitea

**Comment by MilesTEG1** [comment]
Thanks again.
In my research I found this : https://github.com/go-gitea/gitea/issues/15017
As it will be too risky for me to try an hasardous downgrade, I'll swith to a 1.14rc version. I hope soon it will be a stable version.

I'll try to ask in the discord server you gave me.
Thank you.

**Comment by MilesTEG1** [comment]
Do you think your themes will be fully compatible with the 1.14 version ? (Currently it's in RC2 status).

**Comment by MilesTEG1** [comment]
Waiting approuval to ask something in Gitea's discord, I set and installed 1.14rc2 version, my gitea is working again, but I've got the same little problems with icons :
![image](https://user-images.githubusercontent.com/29298312/113601761-09b81900-9642-11eb-8eca-3070d0d3c09b.png)

I hope you'll update your theme when 1.14 will be released :D

**Comment by GilbN** [comment]
Not sure what what you mean by issues with icons. 
Ive pushed some orther fixes to gitea now

**Comment by MilesTEG1** [comment]
Your update seems to have solve the issues :)
