### ISSUE TITLE
Bazarr stopped working, 

### ISSUE THREAD

**Issue by tordenflesk** [gilbN/theme.park#171]
grep: /app/bazarr/views/_main.html: No such file or directory,
sed: /app/bazarr/views/_main.html: No such file or directory

Guessing Bazarr got updated.

**Comment by gilbN** [comment]
Yup.

**Comment by gilbN** [comment]
> grep: /app/bazarr/views/_main.html: No such file or directory,
> sed: /app/bazarr/views/_main.html: No such file or directory
> 
> Guessing Bazarr got updated.

Bazarr develop got updated. Still works on master btw.

**Comment by tordenflesk** [comment]
I'm pretty sure I'm not on develop. I use ghcr.io/linuxserver/bazarr:latest which is Bazarr 0.9.3:

https://i.imgur.com/Cmrebjl.png

**Comment by gilbN** [comment]
ah yeah, I see the update now.

**Comment by gilbN** [comment]
Restart, and it should be good
