### ISSUE TITLE
Readarr Hotio docker_mod not working

### ISSUE THREAD

**Issue by darkcloud784** [GilbN/theme.park#177]
**Describe the bug**
Docker mod env variable for readarr:nightly hotio image is not working. 

**To Reproduce**
1. setup container/pod using hotio:nightly image (I'm using Rancher/kubernetes) with DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr
2. spin up container
3. access container and see no change in css.

**Expected behavior**
See css change to dark schema as is the case with sonarr,radarr,etc

**Screenshots**
![image](https://user-images.githubusercontent.com/989990/115054152-84d0c900-9ea5-11eb-9c37-09e52d15bc8f.png)

**Desktop (please complete the following information):**
 - windows 10 pro
 - firefox 87.0 (64-bit)

**Additional context**
I can confirm there are no errors in the pod/container as seen from docker logs.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-start-container: executing...
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1000
PGID=1000
UMASK=002
TZ=Etc/UTC
----------------------------------------------------------------------
Executing usermod...
usermod: no changes
Applying permissions to /config
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by GilbN** [comment]
Docker mods don't work with hotio containers. https://github.com/GilbN/theme.park/wiki/Setup#-hotio-containers

You need to use the bash script directly.

**Comment by darkcloud784** [comment]
Gotcha, I guess I didn't understand. I'll close this issue since you've provided information.
