### ISSUE TITLE
Slight issue with Sonarr v3 themeing

### ISSUE THREAD

**Issue by calmcacil** [gilbN/theme.park#18]
Everything mostly works fine, except for the dropdown from path choice. which is white text on white background for some reason.

![image](https://user-images.githubusercontent.com/716671/64910375-f3700280-d715-11e9-9491-57ccacb2a5dd.png)

**Comment by gilbN** [comment]
Where is this menu?

**Comment by calmcacil** [comment]
when you add a new show, and you click to set the root folder for the show.

**Comment by calmcacil** [comment]
added this in my stylish as a temporary workaround, might help you out in fixing it in the long run.

`div[class*='EnhancedSelectInputOption'] {
  background-color: #1e1e1e !important;  
`

**Comment by gilbN** [comment]
Clear cache. Should be fixed now. The issue was only visible when using stylus. Thanks for letting me know.
