### ISSUE TITLE
[Bug] Bazarr Theme

### ISSUE THREAD

**Issue by SDS1337** [GilbN/theme.park#181]
**Description**
Mismatched colors, text unreadable at times, big ass purple top bar, various other discrepancies in appearance.

**To Reproduce**
1. Use [dark.css](https://gilbn.github.io/theme.park/CSS/themes/bazarr/dark.css) with Bazarr.
2. Open Web UI
3. Profit?

**Screenshots**
[Imgur Album](https://imgur.com/a/oeLdWBO) 
[Screenshot 1](https://i.imgur.com/Ghl4zha.png)
[Screenshot 2](https://i.imgur.com/eiqP3bn.png)

**Additional context**
Using the Linuxserver/Bazarr:latest Docker image with nginx subfilter for `https://gilbn.github.io/theme.park/CSS/themes/bazarr/dark.css`

Seems to have happened due to [this commit](https://github.com/morpheus65535/bazarr/commit/f64719e4ad27df82d93f4eb2ea67c6fc81cf9d16) in Bazarr v0.9.4.

**Comment by GilbN** [comment]
Fixed on https://github.com/GilbN/theme.park/pull/182
