### ISSUE TITLE
Bazarr background

### ISSUE THREAD

**Issue by Shadow58624** [GilbN/theme.park#185]
**Describe the bug**
Bazarr background is white instead of the selected theme. I am using theme.park with a reverse proxy and about a week ago I noticed that bazarr had a white background. I thought it was my fault because I was changing some things in Nginx Proxy Manager. But I have tried to fix it and even tried it with Stylus and neither way works. I can see the theme is applying because the text changes color however the background remains white.

**To Reproduce**
1. Open bazarr in a tab
2. Apply bazarr theme via stylus 
4. Text changes color but background doesn't

**Expected behavior**
Bazarr background to be dark but instead is white.

**Screenshots**
![image](https://user-images.githubusercontent.com/29847057/116484031-2b42a400-a880-11eb-9b3e-f412cc455fbf.png)

**Theme Install Method**
- Webserver subfilter Config
- Stylus Config

**Application Info**
- hotio/bazarr

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10/docker
 - Browser: edge/chrome

**Comment by GilbN** [comment]
See https://github.com/GilbN/theme.park/issues/184

**Comment by Shadow58624** [comment]
Thanks
