### ISSUE TITLE
All Ngnix subfilter dark themes stopped working today

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#188]
**Describe the bug**
All Ngnix subfilter dark themes stopped working today using Chrome web browser.  They all look like they do without any mod.  This doesnt happen with MS Edge browser.

- Radarr
- Sonarr
- Bazarr
- Plex

My nginx config hasn't changed in months (below).  Restarting nginx doesn't make any difference.  Everything else in nginx works fine (subdomains, etc).

Did something break in the backend?  Nothing has changed at all on my end.  There isn't anything for me to configure or change.

**Comment by GilbN** [comment]
Please clear cache

**Comment by mkanet** [comment]
Thanks.  That worked perfectly!  Sorry to bother you.  I will know to do that next time.

**Comment by GilbN** [comment]
Well it was my fault :P

**Comment by mkanet** [comment]
Your themes are irreplaceable.  Thank you!
