### ISSUE TITLE
Radarr Ngnix subfilter dark theme stopped working

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#189]
**Describe the bug**

Radarr's subfilter dark theme stopped working on all my web browsers.  Clearing cache doesn't fix the issue.  It was working just an hour ago or so.  I don't have issues with the subfilter dark themes for Sonarr and Plex.

Is this issue related to? 
 https://github.com/GilbN/theme.park/issues/188

**Comment by GilbN** [comment]
Please check your browser console for any errors

**Comment by GilbN** [comment]
Still broken?

**Comment by mkanet** [comment]
Thank you so much for being so patient.  The issue seemed to go away after restarting Nginx.  The only thing unusual is that Radarr shows the below errors in the browser console.  I don't get these errors in Sonarr.  I'm not sure if that's normal or not.
![cosole-errors](https://user-images.githubusercontent.com/811008/116796167-5d762080-aa8f-11eb-8dc5-5b59fb59f97b.png)

I looked up the **No 'Access-Control-Allow-Origin header is present on the requested resource.** error..  Per [this link](https://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx).  It seems like I need a specially compiled version of Nginx that has the http://wiki.nginx.org/NginxHttpHeadersModule built-in.  I'm using the latest Windows Nginx build; which doesn't have that module.  I also don't have the skillset to build a special version of Nginx with that module included.  Reguardless, I'm not sure if those errors are related to the issue I saw or not.

If you have any suggestions that may help prevent these errors, please let me know.  Otherwise, please feel free to close this issue.  Thank you very much for the excellent support!

**Comment by GilbN** [comment]
Try and switch to the new url. 

`https://theme-park.dev/CSS/themes/<APP_NAME>/<THEME_NAME>.css`

**Comment by mkanet** [comment]
Thank you.  That didn't seem to make any difference on those errors I get in Chrome web browser for Radarr.  Anyway, I'm not able to reproduce the issue I posted here anymore.

Do you think its better I use the new URL from now for all my apps or should I revert back to the old URL?  Both seem to be hosted by github.

**Comment by GilbN** [comment]
Might as well use the new one.

**Comment by mkanet** [comment]
Thank you.  I'm curious, will you eventually update your documentation to use the new URL?

**Comment by GilbN** [comment]
Already have
