### ISSUE TITLE
Gitea organizr-dark: background color of Repositories list missing

### ISSUE THREAD

**Issue by abyssox** [GilbN/theme.park#191]
**Describe the bug**
The background color of the "Repositories" list at the gitea overview page is not customized in organizr-dark theme.

**To Reproduce**
1. Apply theme "organizr-dark" to gitea
2. Login to Gitea
2. Click on Top Navigation link 'Dashboard'

**Expected behavior**
The Background color of the repositories list (.feeds .list ul li.private) should be customized.

**Screenshots**
![image](https://user-images.githubusercontent.com/4539953/117114201-d3c69b80-ad8b-11eb-90dd-53c3320850d8.png)

**Application Info**
- Gitea: 1.14.2

Regards
abyssox

**Comment by abyssox** [comment]
done

**Comment by GilbN** [comment]
> done

How did you apply the theme? 
Looks okay here. 

![image](https://user-images.githubusercontent.com/24592972/118153024-b6da3a00-b415-11eb-8ca6-da5fa52b5508.png)

**Comment by hrvylein** [comment]
Same problem. Installed it as mentioned here: https://docs.theme-park.dev/themes/gitea/

Everything looks great, except the Repositories section.

**Comment by GilbN** [comment]
Are those repositories private?

**Comment by abyssox** [comment]
Sorry for the delay.

Ah yes they are indeed private.

Looks like the background color of `.feeds .list ul li.private` needs to be adjusted as well:
https://github.com/go-gitea/gitea/blob/a137ee7a68b2246507b8def2de67a4553661a28f/web_src/less/_dashboard.less#L158
