### ISSUE TITLE
Radarr 4k Logo Not Working

### ISSUE THREAD

**Issue by mmaghometech** [GilbN/theme.park#194]
**Describe the bug**
Radarr 4k Logo Not Working Anymore

**To Reproduce**
1. Add radarr-4k-logo as TP_ADDON
2. Open Radarr
3. 4k Logo missing

**Expected behavior**
Radarr 4k logo does not show was previously working.  Rest of theme is applying as expected

**Screenshots**

**Theme Install Method**
- Docker unRAID

![Screenshot 2](https://user-images.githubusercontent.com/64668236/117971097-72587c80-b2f7-11eb-9730-ef3a4e86eb8c.png)
![Screenshot](https://user-images.githubusercontent.com/64668236/117971098-72587c80-b2f7-11eb-9c30-b5a8d06b8704.png)

**Comment by GilbN** [comment]
does the browser console say anything? 
Btw you dont need TP_DOMAIN variable. It's set to `theme-park.dev` by default.

**Comment by GilbN** [comment]
Works on latest and develop for me

**Comment by mmaghometech** [comment]
> does the browser console say anything?
> Btw you dont need TP_DOMAIN variable. It's set to `theme-park.dev` by default.

I was on the nightly branch. Was testing it on my 4k Radarr instance since I don't have many movies on it.  Had forgotten about it. Switching to develop and it fixed the issue.  Thanks for guiding me to the solution.  Sorry for the bother on such a simple solution.

**Comment by GilbN** [comment]
Nw. Thanks for the heads up.
