### ISSUE TITLE
Trying to install plex theme in calibre-web via docker-mods not working

### ISSUE THREAD

**Issue by alejakun** [GilbN/theme.park#198]
I've been testing several themes in several containers, I specifically could not make work the plex theme for calibre-web, other themes work fine for this app.

**Comment by GilbN** [comment]
There is no plex theme. It has one already. 

Set theme to CaliBlur in UI Configuration -> View Configuration -> Theme -> CaliBlur -> Submit

**Comment by alejakun** [comment]
Thanks!

**Comment by GilbN** [comment]
np!
