### ISSUE TITLE
Theme Request : AUTHELIA

### ISSUE THREAD

**Issue by cyb3rgh05t** [GilbN/theme.park#202]
Hi, 

would be very cool if you could add a theme for authelia :)

**Comment by DanWillman** [comment]
This would be nice, though Authelia does [support themes](https://www.authelia.com/docs/configuration/theme.html) via their configurations if you were not aware.

Example `configuration.yml`:
![image](https://user-images.githubusercontent.com/4489280/119374098-c7dd4380-bc7e-11eb-848f-99994478e8b6.png)

**Comment by GilbN** [comment]
Sorry. I don't use Authelia, so I don't have any plans on adding it. Closing this.
