### ISSUE TITLE
Sonarr Unaired Premiere not working

### ISSUE THREAD

**Issue by ILoveNox** [GilbN/theme.park#203]
Hello to all,
I find the themes really amazing guys.
A small issue though.
For Sonarr V3, the calendar color for "unaired premiere" isn't applying. It gets the color of "unaired".
I see it is in the code of the themes, but it is not working.
Is there a way to make it work?
Thanks in advance.
Cheers.

**Comment by GilbN** [comment]
Not sure what you mean.  It does show Premiers. 
![image](https://user-images.githubusercontent.com/24592972/120214627-0487dc80-c235-11eb-93f5-6b8d44f3a55e.png)

**Comment by ILoveNox** [comment]
Thanks for your reply.
Yes I know this and see it. I meant the whole background color like other
status colors. It is in your code but not applied :
--calendar-tv-unaired-premiere: 53 197 244 (taken from aquamarine)
I gather it is because the sonar-base.css doesn't have the code to apply it
to. There is no code for this color to be used in.
Cheers.

**Comment by GilbN** [comment]
Right. Sonarr doesn't have a class I can style. It's the same class on both unaired and unaired premier divs. The variable is just there if I ever need it in the future.
