### ISSUE TITLE
Blank Page Ombi v4

### ISSUE THREAD

**Issue by AlexAshs** [GilbN/theme.park#205]
**Describe the bug**
Trying to access ombi v4 with a firefox browser, a blank background in the themes background color appears.
Caddy logs this error message: 78.10.0esr (64-bit)
By removing the theming configuration from the reverse proxy directive in caddy and restarting it, it works fine again with firefox, so the issue has to be the theme.

**Theme Install Method** (Don't skip)
organizr-dark.
caddyfile caddy v2 reverse proxy

**Application Info** (Don't skip)
ombi v4 (linuxserver/ombi)
It has been working before with ombi v3, so i definitely have configured caddy correctly

**To Reproduce**
1. Setup a docker-compose.yaml like so:
`version: "3.7"
  services:
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      environment:
        - PUID=1111
        - PGID=1111
        - UMASK_SET=0007
      volumes:
        - ./config/ombi:/config:rw
      ports:
        - 3579:3579
      restart: unless-stopped
   caddy:
      build:
        context: .
        dockerfile: Dockerfile
      image: caddy
      container_name: caddy
      volumes:
        - "./Caddyfile:/etc/caddy/Caddyfile:rw"
        - "./config:/config:rw"
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped`
2. Configure the caddyfile like this:
`  {
      order filter after encode
  }
 ombi.domain {
    reverse_proxy 192.168.1.33:3579 {
      header_up -Accept-Encoding
      header_down -x-webkit-csp
      header_down -content-security-policy
    }
    filter {
      content_type text/html.*
      search_pattern </head>
      replacement "<link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/ombi/organizr-dark.css'></head>"
  2   }
  1 }`
3. Call ombi.domain with a current version of firefox
4. See only the background but no login page

**Expected behavior**
The ombi login page should show up.

**Screenshots**

**Desktop (If applicable) (please complete the following information):**
Linux kali 5.10.0-kali8-amd64 #1 SMP Debian 5.10.40-1kali1 (2021-05-31) x86_64 GNU/Linux
Firefox on linux 78.10.0esr (64-bit) and with 
It is working as intended with the current version of chrome, both on windows and linux.

**Smartphone (If applicable) (please complete the following information):**
Xiaomi Mi Max 3
MIUI 11.04
Android 10
Firefox on android 89.1.1 (Build #2015812947)

**Additional context**
No base url was used.

**Comment by GilbN** [comment]
Hi. Ombi v4 is not supported

**Comment by AlexAshs** [comment]
Well that explains it.
Shall I close this then?
It'll probably be good, that it's reported, so others may find it.

**Comment by AlexAshs** [comment]
Haven't checked that one out yet, but i like the plexish style.
I think, I'll give it a try!
Afaik ombi v4 is quite done now, because linuxserver has moved it to their stable realease.
It used to have the development tag before, and stable was only v3.

**Comment by GilbN** [comment]
Omvi v4 is supported now btw

**Comment by AlexAshs** [comment]
I still receive the blank page using any version of firefox.
Is there anything new to consider with v4 support?

**Comment by GilbN** [comment]
Oh. You dont need to subfilter the theme. Ombi supports custom css in Settings. https://docs.theme-park.dev/themes/ombi/#installation

**Comment by AlexAshs** [comment]
Oh I didn't consider that.
Now it works like a charm :)
Thank you very much!
