### ISSUE TITLE
File Browser pagination/infinite scrolling not working

### ISSUE THREAD

**Issue by moosedookie** [gilbN/theme.park#21]
I recently noticed that pagination/infinite scrolling is not working after using any of the themes on Filebrowser. I went ahead and tested all the variations and found they all have the issue.

Currently using File Browser v2.0.12

After some digging around I believe I have found the issue.
In the filebrowser-base.css at the beginning under the html section overflow is set to hidden. If you remove this line file browser works as intended.

**Comment by moosedookie** [comment]
I submitted pull request #20 to fix this.

**Comment by gilbN** [comment]
Thanks for the pr. I'm on 2.0.3 so I'm gonna upgrade to verify 👍

**Comment by gilbN** [comment]
merged https://github.com/gilbN/theme.park/pull/20
