### ISSUE TITLE
High contrast theme type

### ISSUE THREAD

**Issue by agneevX** [GilbN/theme.park#210]
The Organizr-Dark theme recently lost its high contrast feature because text colors got very dark and its hard to make out text. 

Can a high contrast theme be added? Thanks.

**Comment by GilbN** [comment]
you can customize the text color with the --text variable

**Comment by agneevX** [comment]
Thanks. Would you be able to tell me how to save a local version of a theme?. It's a bit confusing with all the imports.

**Comment by GilbN** [comment]
> Thanks. Would you be able to tell me how to save a local version of a theme?. It's a bit confusing with all the imports.

Depends one the install method you're using. If you are using stylus its as simple as
```css
@import url("some.url");
:root {
--the-text-variable-for-the-theme: #FFFFFF;
}
```
I think most themes use `--text` some use `--text-color` ect
You can fin the variables in the `<theme>.css` files. 

If you use subfilter or docker mods ect you can fork the repo and just change the variables directly
https://docs.theme-park.dev/custom/
