### ISSUE TITLE
[BUG] VueTorrent theme

### ISSUE THREAD

**Issue by pcmv-dev** [GilbN/theme.park#218]
### Problem
The stats sidebar is not properly being themed

### Theme Install Method
Nginx Proxy Manager
```
proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/themes/vuetorrent/space-gray.css">
</head>';
sub_filter_once on;
```
### Application Info
- Version: Qbittorrent(4.3.5)/VueTorrent(0.10.0)
- Docker: hotio/qbittorrent:latest

### Screenshots
https://i.imgur.com/qfm00dp.png
https://i.imgur.com/gK63M0g.png
https://i.imgur.com/sVRF7xv.png
https://i.imgur.com/A0DcXLH.png

**Comment by GilbN** [comment]
Thanks, looks like I only tested the theme with stylus..
![](https://media.giphy.com/media/3ohzdYJK1wAdPWVk88/giphy.gif)

**Comment by GilbN** [comment]
Oh, looks like they use inline styling on the HTML page that gets loaded after the theme stylesheet. 

Try and replace `</head>` with `</body>` in your subfilter config.  Looks like that worked for me.

**Comment by GilbN** [comment]
btw, if you use the linuxserver container, there is a docker mod now. `DOCKER_MODS=ghcr.io/gilbn/theme.park:vuetorrent`

**Comment by pcmv-dev** [comment]
Thanks for the fix it looks great now! I use hotio because his comes with Wireguard VPN support and Vuetorrent builtin as well.

**Comment by GilbN** [comment]
> Thanks for the fix it looks great now! I use hotio because his comes with Wireguard VPN support and Vuetorrent builtin as well.

This script should work for hotio now. https://github.com/GilbN/theme.park/blob/docker-mods/vuetorrent/root/etc/cont-init.d/98-themepark
