### ISSUE TITLE
Backround not blurring on Firfox and Samsung Internet

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [gilbN/theme.park#22]
Nothing is being blurred. Login screen, navagation bar, account setting, etc. 

https://imgur.com/a/mE0KNDo

Any way to fix this?

**Comment by gilbN** [comment]
Needs to be enabled in FF

```
 From version 70: this feature is behind the layout.css.backdrop-filter.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.
```

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> Needs to be enabled in FF
> 
> ```
>  From version 70: this feature is behind the layout.css.backdrop-filter.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.
> ```

Thank you for the fast response! I set the `layout.css.backdrop-filter.enabled` setting to True and restarted Firefox still having the same issue.

**Comment by gilbN** [comment]
Not sure whats wrong then, It works on FF 70.0.1 (64-bit) here
