### ISSUE TITLE
Sonarr base.ccs file for Plex theme is not found

### ISSUE THREAD

**Issue by STiXzoOR** [GilbN/theme.park#223]
**Describe the bug**
The base.css file for sonarr is not found due to wrong address in plex.css file. It should be:

`url(https://theme-park.dev/CSS/themes/sonarr/sonarr-base.css)` 

instead of 

`url(https://gflix.app/theme.park/CSS/themes/sonarr/sonarr-base.css)`.

**Theme Install Method**
Webserver subfilter Config

**Application Info**
Version: 3.0.6.1272
Branch: Develop
Container: Windows Setup

**To Reproduce**
1. Go to 'Sonarr'

**Expected behavior**
Plex theme should be applied like the rest of the services but the default theme is loaded instead.

**Comment by jasonalsing** [comment]
Came here looking for this same issue. Errors in Chrome developer console that it can't find the base.css file. Plex theme not applied.

**Comment by GilbN** [comment]
lol, this is why you shouldn't push changes at 2am :P.
