### ISSUE TITLE
[qBittorrent] Right click menu not showing icons

### ISSUE THREAD

**Issue by darkknight6722** [GilbN/theme.park#227]
**Describe the bug**
In qbittorrent themes, right click menu on torrents not showing any icons. Some of them are toggles. So its unable to see whether they are on/off.

**Theme Install Method** Linuxserver Docker Mods
- Docker run / Compose Config 
qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=
      - PGID=
      - UMASK=
      - TZ=
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
    restart: on-failure

**Application Info** (Don't skip)
- Version 4.3.6
- Branch Stable
- Container linuxserver

**To Reproduce**
1. Open web ui and right click on any torrent.

**Expected behavior**
Icons to show properly

**Screenshots**
![qBittorrent v4 3](https://user-images.githubusercontent.com/68375196/124382791-d0e21b80-dce6-11eb-95b2-6b2c989690d2.png)

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by GilbN** [comment]
should be good now
