### ISSUE TITLE
Bazarr themes broken

### ISSUE THREAD

**Issue by Nomelas** [GilbN/theme.park#228]
**Describe the bug**
None of the themes for Bazarr work

**Theme Install Method** (Don't skip)
- Docker Mods, but likely broken for everything

**Application Info** (Don't skip)
- Latest linuxserver/bazarr docker image

**To Reproduce**
1. Use any themes for bazarr

**Expected behavior**
Expected to change theme to the one configured

**Screenshots**
![image](https://user-images.githubusercontent.com/15185630/124397218-11d93080-dce5-11eb-9d91-f564c4b685a9.png)

**Desktop (If applicable) (please complete the following information):**
 - N/A

**Smartphone (If applicable) (please complete the following information):**
 - N/A

**Additional context**
https://theme-park.dev/CSS/themes/bazarr/organizr-dark.css

This has the wrong variables path:
https://theme-park.dev/CSS/varibles/organizr-dark.css

should be:
https://theme-park.dev/CSS/variables/organizr-dark.css

Same for all of them:
https://theme-park.dev/CSS/themes/bazarr/aquamarine.css
https://theme-park.dev/CSS/themes/bazarr/hotline.css
https://theme-park.dev/CSS/themes/bazarr/plex.css
https://theme-park.dev/CSS/themes/bazarr/dark.css
https://theme-park.dev/CSS/themes/bazarr/space-gray.css
https://theme-park.dev/CSS/themes/bazarr/organizr-dark.css

**Comment by GilbN** [comment]
try and clear cache now
