### ISSUE TITLE
Theme for latest Sonarr V3 partially broken (3.0.3.659)

### ISSUE THREAD

**Issue by quorn23** [gilbN/theme.park#23]
Todays update of Sonarr V3 broke the theme in the "add new show" section, see screenshot.

[https://imgur.com/a/yIwNFHv](https://imgur.com/a/yIwNFHv)

Edit: Some additional info might be good, using Sonarr with nginx (sub filter) not Stylus or sorts.
The first entry is how it looks with mouse over, the others without.

**Comment by gilbN** [comment]
@quorn23 sonarr version?

**Comment by gilbN** [comment]
Fixed on https://github.com/gilbN/theme.park/commit/8c334503c142124ece3c24e60077d9389834de2d

**Comment by quorn23** [comment]
Noted, next time not only in the title :D

**Comment by gilbN** [comment]
no worries :)

**Comment by lostandlost** [comment]
I am seeing this same visual behavior on Lidarr 0.7.1.1588.

**Comment by gilbN** [comment]
> I am seeing this same visual behavior on Lidarr 0.7.1.1588.

I'm not seeing that. Im on version 0.7.1.1381

**Comment by lostandlost** [comment]
I am running a little newer version.  Are you able rerecreate it with 1558?  I just tested it again on a mobile browser this time and still see the same issue.

**Comment by gilbN** [comment]
Are you on develop? I'm using the  linuxserver/lidarr latest

**Comment by lostandlost** [comment]
Nightly actually.  The last update was Dec 16th.

**Comment by gilbN** [comment]
@lostandlost 

fixed https://github.com/gilbN/theme.park/commit/c0c08561081d8ef332275f4f90c69edcffebcd84
