### ISSUE TITLE
Organizr theme issues

### ISSUE THREAD

**Issue by STiXzoOR** [GilbN/theme.park#231]
Describe the bug
I'm getting error 404 saying that Oragnizr.css file is not found when using any of the themes and looking up in the repo it is in fact missing from the organizr folder. Also when using the nginx subfilter method with the nginx variable described in the docs, i can't use the commands `set $app <app>; include /config/nginx/theme-park.conf;` for the organizr location block since it messes up with the rest of the applications and the theming is not working as i'm accessing them as subfolders and not as subdomains. I have to manually add the subfilter block for organizr in the location block in order to get it working as it should be.

Theme Install Method
Webserver subfilter Config

Application Info
Version: 2.1.426
Branch: Develop
Container: Windows Setup

To Reproduce

1. Go to 'Organizr'
2. Open 'Developer Tools'
3. Check in the network tab for any 404 errors about organizr.css

**Comment by GilbN** [comment]
> Describe the bug
> I'm getting error 404 saying that Oragnizr.css file is not found when using any of the themes and looking up in the repo it is in fact missing from the organizr folder. Also when using the nginx subfilter method with the nginx variable described in the docs, i can't use the commands `set $app <app>; include /config/nginx/theme-park.conf;` for the organizr location block since it messes up with the rest of the applications and the theming is not working as i'm accessing them as subfolders and not as subdomains. I have to manually add the subfilter block for organizr in the location block in order to get it working as it should be.
> 
> Theme Install Method
> Webserver subfilter Config
> 
> Application Info
> Version: 2.1.426
> Branch: Develop
> Container: Windows Setup
> 
> To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to 'Organizr'
> 2. Open 'Developer Tools'
> 3. Check in the network tab for any 404 errors about organizr.css

The themes can be found in the Theme Marketplace menu in Organizr.

**Comment by GilbN** [comment]
https://docs.theme-park.dev/themes/organizr/#installation
