### ISSUE TITLE
Space gray color bug

### ISSUE THREAD

**Issue by pasuva** [GilbN/theme.park#234]
**Describe the bug**
The fonts in the space gray theme appears with black color instead white, in all the navigators.

**Theme Install Method** (Don't skip)
- Stylus Config

**Application Info** (Don't skip)
- Branch

**To Reproduce**
-Install the theme and test it

**Screenshots**
<img width="1559" alt="Captura de pantalla 2021-07-20 a las 8 20 44 1" src="https://user-images.githubusercontent.com/31448608/126271542-01c54352-fbe8-41de-8dbb-ab272155d2e7.png">

**Desktop (If applicable) (please complete the following information):**
 - Browser [e.g. chrome, safari,firefox]

**Smartphone (If applicable) (please complete the following information):**

**Comment by GilbN** [comment]
And clear cloudflare cache if you use that.

**Comment by Zachar2** [comment]
I have the same problem with Dark Theme. I followed your directions but to no avail :(

**Comment by GilbN** [comment]
> I have the same problem with Dark Theme. I followed your directions but to no avail :(

Try incognito and another browser.

**Comment by Zachar2** [comment]
You are correct. I thought I cleared my cache. Thanks.

**Comment by reloxx13** [comment]
private tab, cache cleared
sabnzb black theme
![grafik](https://user-images.githubusercontent.com/14855001/126879463-346022cd-e87a-40e2-b1dd-ba0b4f598cda.png)

**Comment by GilbN** [comment]
> private tab, cache cleared
> sabnzb black theme
> ![grafik](https://user-images.githubusercontent.com/14855001/126879463-346022cd-e87a-40e2-b1dd-ba0b4f598cda.png)

Still think its cache. 
![chrome_m7ky8yvqkN](https://user-images.githubusercontent.com/24592972/126879582-6ffb5dfe-7af7-4774-96b4-2327b77da28b.png)

**Comment by reloxx13** [comment]
naah, i look into it, someone removed the override of sabs default btn color and i had gitter night theme from sab active.    
sab default night btn color is #E4E4E4 (white/grey).   
    
gitter auto/night are not not compatible anymore.

**Comment by reloxx13** [comment]
now feedback btn (beta only?) unreadable
![grafik](https://user-images.githubusercontent.com/14855001/126879775-0f47242b-10df-457b-b4a4-3d3a4addc0be.png)

**Comment by reloxx13** [comment]
```
/*
dont use it hsla/transparent (from default btn color), or the inner text if open is not readable
*/
#feedback-slider{
	background: hsl(0,0%,20%); 
}
```
![grafik](https://user-images.githubusercontent.com/14855001/126879980-0a01bf43-f0f8-472c-8e8b-40f023323ec4.png)
