### ISSUE TITLE
No background poster with custom Plex CSS

### ISSUE THREAD

**Issue by fana13** [GilbN/theme.park#238]
**Theme Install Method** (Don't skip)
- Stylus Config

**Application Info** (Don't skip)
- Version 2.0.1

**Expected behavior**
When theme is apply, the background poster disappear on movie, tv serie, etc...

**Screenshots**
Without theme : https://imgur.com/7LWkF4p
With theme : https://imgur.com/6dzahVu

**Comment by GilbN** [comment]
Yeah, I haven't found a way around that.

**Comment by GilbN** [comment]
This is fixed on develop btw. Use `develop.theme-park.dev`

**Comment by fana13** [comment]
Thanks, it's really good :)
