### ISSUE TITLE
Calibre-Web Caliblur Theme is broken at the moment.

### ISSUE THREAD

**Issue by cbartondock** [GilbN/theme.park#239]
**Describe the bug**
The following code in calibreweb-base is causing dropdowns to misbehave:
```
.dropdown-menu {
    background-color: var(--drop-down-menu-bg)!important;
    max-height: none!important
}
```
Namely they go down too far and are transparent. Also, this is a thing:

![Capture](https://user-images.githubusercontent.com/4482454/127232732-97f1807d-2506-40c9-ab78-212481d1c250.PNG)

**Theme Install Method** (Don't skip)
Subfilter

**Application Info** (Don't skip)
- Version: Master

**Screenshots**

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by GilbN** [comment]
@cbartondock try and clear cache now.

**Comment by cbartondock** [comment]
That fixed the transparaency issue (thanks) but they are still dropping down too far which they didn't use to do, and there is still some strange button highlighting occurring. Not sure if the dropping down too far issue is caused by you or a change in calibreweb.

![Screen Shot 2021-07-28 at 1 17 40 PM](https://user-images.githubusercontent.com/4482454/127367638-17443357-61a4-4e6b-bbcf-faf61a4bb7b7.png)

**Comment by cbartondock** [comment]
Actually I can confirm that the dropping down too far issue is not with the theme it's with calibreweb so all that remains is the weird button highlighting issue upon being clicked. Thanks!!

**Comment by GilbN** [comment]
Cool, yeah there's an issue with the minification on the css. Need to look into that.

**Comment by GilbN** [comment]
should be good now.

**Comment by cbartondock** [comment]
Brilliant thank you.

**Comment by cbartondock** [comment]
Actually could you please get rid of the max-height: none ! important line? That is not the correct behavior and this shouldn't be set in a theme anyway.

**Comment by GilbN** [comment]
> @GilbN Actually could you please get rid of the max-height: none ! important line? That is not the correct behavior and this shouldn't be set in a theme anyway.

Yeah, fixed.

**Comment by cbartondock** [comment]
Thanks!
