### ISSUE TITLE
Some buttons on nzbget are hard to see if it is toggled

### ISSUE THREAD

**Issue by Roxedus** [gilbN/theme.park#24]
NZBGET 21. nzbget-dark

With nzbget-dark it is hard to see if a button is active or not. `btn-primary`and `btn` are very similar.

Happens to all buttons when editing a item that is in the download queue, or in the history. 

Without theme. 
![image](https://user-images.githubusercontent.com/7110194/69901851-55d8b680-1387-11ea-896f-344b58f08ad5.png)

With theme.
![image](https://user-images.githubusercontent.com/7110194/69901880-ac45f500-1387-11ea-898a-51829aad2ba0.png)

**Comment by gilbN** [comment]
cache? https://github.com/gilbN/theme.park/blob/8772a7e6f4c532643d97b12e7b1512ab49d19a77/CSS/themes/nzbget/dark.css#L20

**Comment by gilbN** [comment]
I see it now

**Comment by gilbN** [comment]
@Roxedus  try now. https://github.com/gilbN/theme.park/commit/1cf37e6106ee6ddfc9702ff44108a1d72547a47c

**Comment by Roxedus** [comment]
not quite, looks like you need a `#HistoryEdit_ParamData input.btn.btn-primary` selector too

**Comment by gilbN** [comment]
clear cache

**Comment by Roxedus** [comment]
works 
![image](https://user-images.githubusercontent.com/7110194/69919199-b8f74580-147a-11ea-9faa-014a6436026d.png)
