### ISSUE TITLE
Apache2 Errors

### ISSUE THREAD

**Issue by UnPossible-Me** [GilbN/theme.park#247]
Hello,
I recently found out about this and was excited to give it a go.
Now I still have to use Apache2, and have run into some problems:

My `apache2.conf` looks like this:
```
ProxyPass /deluge http://localhost:8112/

<Location /deluge>
    ProxyPassReverse /
    ProxyPassReverseCookiePath / /deluge
    RequestHeader set X-Deluge-Base "/deluge/"
    Order allow,deny
    Allow from all

    RequestHeader unset Accept-Encoding
    AddOutputFilterByType SUBSTITUTE text/html
    Substitute 's|</head>|<link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/themes/deluge/deluge-base.css">
    <link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/variables/dracula.css"></head>|ni'
</Location>
```

That led me to the first issue, `apache2: Syntax error on line 251 of /etc/apache2/apache2.conf: Expected </link> but saw </Location>`
So as directed, I added `</link>` to the code block.

Now reloading, I'm hit with:
```
AH00526: Syntax error on line 248 of /etc/apache2/apache2.conf:
Unknown filter provider SUBSTITUTE
```

And... I'm at a loss on how to proceed.
I've followed the setup manual and the changes from [Issue 123](https://github.com/GilbN/theme.park/issues/123), but no luck. 
Any ideas?

**Comment by GilbN** [comment]
For testing, can you try this:
`Substitute 's|</head>|<link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/themes/deluge/dracula.css"></head>|ni'`

**Comment by UnPossible-Me** [comment]
Unfortunately, it results in the same error, tried with calibreweb as well in case it was just a deluge issue with the exact result.

**Comment by GilbN** [comment]
Does your Apache have e module installed? I've never used Apache but maybe it needs to be compiled with mod_substitute.

Found this https://corpocrat.com/2008/09/19/install-apache-mod_substitute/

**Comment by UnPossible-Me** [comment]
I found that as well!
I'm on Debian currently, but it's at least given me a direction, I'll check if I've got all the required modules installed

**Comment by KaKi87** [comment]
Hello,

I encountered the same issue and solved it with `sudo a2enmod substitute`.

I also needed `sudo a2enmod headers`.

I think those prerequisites should be documented.

Thanks
