### ISSUE TITLE
Theme background not appearing for Plex 

### ISSUE THREAD

**Issue by cbartondock** [GilbN/theme.park#249]
**Describe the bug**
Using the hot pink theme via nginx subfilter. Broke today for plex - no longer applies a background. Buttons etc are still themed but the background is broken

**Theme Install Method** (Don't skip)
- Webserver subfilter Config

**Application Info** (Don't skip)
- Plex up to date as of 8/18/2021

**To Reproduce**
1. Apply plex-base via subfilter
2. Go to plex
3. Original plex background appears

**Expected behavior**
The hot pink theme background is supposed to appear - it still does for other apps.

**Screenshots**
As you can see the background is the original plex background, but buttons and text have the hot pink theming
![Capture](https://user-images.githubusercontent.com/4482454/129994060-5bbe3e54-c03f-4996-bbf2-6d9c33014820.PNG)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave (up to date)

**Additional Context**
Fork I made 15 commits ago still has the correct behavior, so the change occurred since then.

**Comment by GilbN** [comment]
Make sure you use the correct domain in the subfilter. `theme-park.dev`
