### ISSUE TITLE
Nextcloud/Searx theme

### ISSUE THREAD

**Issue by Nosirus** [gilbN/theme.park#25]
Hi, I'm trying to use the themes I love on all my dockers, a nextcloud/Searx theme would be great for me !

**Comment by gilbN** [comment]
Whats nextcloud/Searx ?

**Comment by Nosirus** [comment]
Sorry, I confess I wasn't very clear.

Nextcloud and Searx https://github.com/asciimoo/searx :)

**Comment by gilbN** [comment]
I'll maybe do a nextcloud theme if I ever get the time
