### ISSUE TITLE
[New Theme Request] Uptime Kuma

### ISSUE THREAD

**Issue by Monklite** [GilbN/theme.park#250]
[Uptime Kuma](https://github.com/louislam/uptime-kuma) has gotten some attention lately and while I have yet to spin it up, the overall design of it seems pretty simple and getting a theme.park theme for this doesn't seem too difficult based on what I see so far. It would be awesome to have a theme for this one!

**Comment by GilbN** [comment]
Added https://docs.theme-park.dev/themes/uptime-kuma/
