### ISSUE TITLE
Bazarr new style doesn't work

### ISSUE THREAD

**Issue by fana13** [GilbN/theme.park#251]
- Stylus Config
- Bazarr Version 0.0.9-beta 3
- Branch Development
- Debian 10
- Firefox last version, cache refresh

I try to apply new style, with new domain in stylus like this:
@import "https://theme-park.dev/CSS/themes/bazarr/bazarr-base.css";
@import "https://theme-park.dev/CSS/addons/bazarr/bazarr-darker/bazarr-darker.css";
@import "https://theme-park.dev/CSS/addons/bazarr/bazarr-4k-logo/bazarr-4k-logo.css";

No 4K logo appear, no dark background, just font color change

With the old method, style is correctly displayed:
@import "https://gilbn.github.io/theme.park/CSS/themes/bazarr/bazarr-base-old.css";
:root {
  --main-bg-color: #1f1f1f;
  --modal-bg-color: #1b1b1b;

  --button-color: #2cabe3;
  --button-color-hover: rgb(44 171 227 / .8);
  --accent-color:  #2cabe3;
  --accent-color-hover: white;
}

Could you tell what's wrong ?
Thanks

**Comment by GilbN** [comment]
Update bazarr to latest version. 

If `bazarr-base-old.css` works that means your Bazarr is outdated.

![image](https://user-images.githubusercontent.com/24592972/132688100-f7f1a8e9-0cfa-4535-9ce8-eb111da77734.png)

**Comment by fana13** [comment]
You got me on the way.
I do a fresh install and now it work perfectly.
Thanks !

**Comment by GilbN** [comment]
Great! 👍
