### ISSUE TITLE
Certain docker-mods saved with CRLF newlines

### ISSUE THREAD

**Issue by bobokun** [GilbN/theme.park#255]
**Describe the bug**
There are certain docker-mods files (ex. jackett/tautulli/qbittorrent ) that are saved with CRLF as the newline. This causes hotio containers to fail when trying to execute the scripts. Other docker-mods like radarr are unaffected (it's saved using LF newline)

**Theme Install Method** (Don't skip)
- Docker run

**Application Info** (Don't skip)
Master branch

**Comment by GilbN** [comment]
Fixed in develop
