### ISSUE TITLE
aquamarine.css Is it incompatible with grafana 8.1.3 version

### ISSUE THREAD

**Issue by 2021zxc** [GilbN/theme.park#257]
**Describe the bug**
aquamarine.css Is it incompatible with grafana 8.1.3 version，The following problems occur, how can I solve them, thank you
There is no black color block at the top of the screen, and a white vertical scroll bar appears on the right

**Theme Install Method** (Don't skip)
- rpm -ivh

**Application Info** (Don't skip)
- Version 8.1.3

**Expected behavior**
The colors on the right and top are consistent with the background color

**Desktop (If applicable) (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [chrome v94]
 
![image](https://user-images.githubusercontent.com/87515154/134803789-7117e349-3553-4a1a-82c2-047d310552e8.png)

**Comment by GilbN** [comment]
Grafana themes are deprecated. If you want to fix any issues you will have to make a pull request.
