### ISSUE TITLE
Button Sizing for Ombi

### ISSUE THREAD

**Issue by camkidd** [gilbN/theme.park#26]
Firstly thanks for all the work on these styles - really love it. 👍

Ombi has a few buttons that have more text that the button can accommodate, such as on the Plex page.
![image](https://user-images.githubusercontent.com/1066576/71847511-2739c280-3121-11ea-83d7-3124262d939e.png)

This can be alleviated with css "min-width" instead of "width" for .btn-primary-outline
https://github.com/gilbN/theme.park/blob/9f0eaef3f34888a667c3c7cf9262a856c97ef4f6/CSS/themes/ombi/ombi-base.css#L282

![image](https://user-images.githubusercontent.com/1066576/71848269-26a22b80-3123-11ea-9b0a-e8690a2958ff.png)

CSS not my thing so I don't know if the other btn- styles need to be updated also.

**Comment by gilbN** [comment]
Thanks. LGTM
https://github.com/gilbN/theme.park/commit/896bf2cd882605ad11f65346a75124d71c199d43
