### ISSUE TITLE
Ombi Version 4.1.0 search results posters display incorrectly

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#268]
**Describe the bug**
After upgrading to Ombi Version 4.1.0, all **search results** posters are stretched and overlapped when using:

**https://theme-park.dev/CSS/themes/ombi/dark.css**

**Screenshots**

![screens-one](https://user-images.githubusercontent.com/811008/136605429-760b0c5d-6a98-4d62-b9c0-b70de4129f47.png)

**Also, weird scaling behavior when changing web browser's zoom level too.  If I disable the CSS theme entirely, the issue goes away.**

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 94.0.4606.71 

**Additional context**
I can reproduce this on my Android Samsung Web Browser too.

**Comment by GilbN** [comment]
Pushed a fix on develop. https://github.com/GilbN/theme.park/commit/5d5fdc377cb7db38a2f9d93a7e1b05d3df3553cd

use https://develop.theme-park.dev to test

**Comment by GilbN** [comment]
Fixed on https://github.com/GilbN/theme.park/releases/tag/1.4.1

**Comment by mkanet** [comment]
> Fixed on https://github.com/GilbN/theme.park/releases/tag/1.4.1

Thank you so much. I worked perfectly!!
