### ISSUE TITLE
Dark themes onedark for Radarr and Jackett is broken.

### ISSUE THREAD

**Issue by SuberSeb** [GilbN/theme.park#282]
**Describe the bug**
Themes for Radarr and Jackett is broken. For dark theme all is in white colors. But for Sonarr it's fine now.

**Theme Install Method** (Don't skip)
- Docker run

**Application Info** (Don't skip)
- Radarr Version: 4.0.0.5426
- Branch: nightly
- Container: linuxserver/radarr

- Jackett Version: v0.19.108
- Branch: latest
- Container: linuxserver/jackett

**To Reproduce**
Just open app.

**Expected behavior**
Dark theme should be applied.

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 93.0

**Comment by SuberSeb** [comment]
Same for Sonarr, just recreated the container and it's broken now.

**Comment by GilbN** [comment]
See latest release notes https://github.com/GilbN/theme.park/releases/tag/1.6.0

**Comment by Akirainblack** [comment]
All docker-mods appear broken, even running it with default values. I'm getting stock radarr,sonarr, lidarr and jackett.

**Comment by jamiew0w** [comment]
> 
> 
> See latest release notes https://github.com/GilbN/theme.park/releases/tag/1.6.0

> The old folder structure will still be working for the time being, but will be removed in the future.

It appears old setups are broken already though?

**Comment by 338lm** [comment]
> > See latest release notes https://github.com/GilbN/theme.park/releases/tag/1.6.0
> 
> > The old folder structure will still be working for the time being, but will be removed in the future.
> 
> It appears old setups are broken already though?
> 
> For example, all CSS linked here is 404'ing (https://docs.theme-park.dev/themes/radarr/)

this is exactly right. the URL results in a 404 error

**Comment by GilbN** [comment]
I'll also look into recreating the theme-option files inside each base/themes automatically

**Comment by GilbN** [comment]
With release of [1.6.1](https://github.com/GilbN/theme.park/releases/tag/1.6.1) docker mods should now only need a reboot to get the new paths. 

And all the old paths are back.

The `/CSS/xxx` path will still be removed in the future. So if any of you are using subfiltering you should switch to the new path: `/css/base/<app>/<theme-option>.css`
