### ISSUE TITLE
Trouble getting linuxserver.io containers to display theme

### ISSUE THREAD

**Issue by deaglenomics** [GilbN/theme.park#285]
Hi , 

Its probably me doing something wrong but im trying to fix the styles not applying to my containers.

Logs from the container look like it applies the config but nothing is actually applied when the container starts.

I still have DOCKER_MODS set to ghcr.io/gilbn/theme.park:sonarr

[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 98-themepark: executing... 

---------------------------

|  Sonarr theme.park Mod  |

---------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=true
'TP_ADDON'=
'TP_THEME'=organizr-dark

No domain set, defaulting to theme-park.dev

---------------------------
|  Adding the stylesheet  |
---------------------------

Stylesheet set to organizr-dark
[cont-init.d] 98-themepark: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.6.1342 

Hoping someone here is able to point me to the right ENV variables I need to set.

**Comment by GilbN** [comment]
Remove the community env. And set tp_theme to `organizr`

**Comment by deaglenomics** [comment]
Legend! 

That was the issue :)
