### ISSUE TITLE
Gitea: code-view not readable at all ( White background for dark themes )

### ISSUE THREAD

**Issue by Crashdummyy** [GilbN/theme.park#293]
**Describe the bug**
The CodeView in gitea is not quite readable ( white background with lightgray text ).
At least the identifiers can be read.

**Theme Install Method** (Don't skip)
Gitea runs in `/var/lib/gitea` with:
`templates/custom/header.tmpl`
```
{{ if .IsSigned }}
  {{ if and (ne .SignedUser.Theme "gitea") (ne .SignedUser.Theme "arc-green") }}
    <link rel="stylesheet" href="/styles.css">
    <link rel="stylesheet" href="/css/gitea.css">

<!-- Had to swap some path here... is that correct ? -->
<!--<link rel="stylesheet" href="https://theme-park.dev/css/gitea/base/{{.SignedUser.Theme}}.css">-->
    <link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/{{.SignedUser.Theme}}.css">
  {{end}}
{{ else if and (ne DefaultTheme "gitea") (ne DefaultTheme "arc-green") }}
  <link rel="stylesheet" href="/styles.css">
  <link rel="stylesheet" href="/css/gitea.css">
  <link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/{{DefaultTheme}}.css">
{{end}}
```
`/etc/gitea/app.ini`
```
[ui]
THEMES        = gitea,arc-green,arc-blue,plex,aquamarine,dark,dracula,hotline,organizr,organizr-dark,space-gray,hotpink,onedark,overseerr,nord
DEFAULT_THEME = gitea
```

```
# /etc/systemd/system/gitea.service
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target

Wants=postgresql.service
After=postgresql.service

[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web -p 61000 --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea

[Install]
WantedBy=multi-user.target
```

**Application Info** (Don't skip)
I assume you mean gitea here
- Version 1.15.3 - 1.15.6 (latest as of wring)
- Branch develop ( der Uri nach zu urteilen )

**Screenshots**
![image](https://user-images.githubusercontent.com/15139403/141686901-e77ddeb6-ff46-4ff6-b87a-a34eaca993b2.png)

If I disable **--color-code-bg: #ffffff;** its a lot better

**Comment by MilesTEG1** [comment]
Hello,
In order to make this new installation process, with the recent modification of css folders,
I had to modify the `header.tmpl` to this :
```go
{{ if .IsSigned }}
  {{ if and (ne .SignedUser.Theme "gitea") (ne .SignedUser.Theme "arc-green") }}
    <!-- <link rel="stylesheet" href="/styles.css"> -->
    <!-- <link rel="stylesheet" href="/css/gitea.css"> -->
		<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/gitea-base.css">
		<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/chroma.css">
    <link rel="stylesheet" href="https://theme-park.dev/css/theme-options/{{.SignedUser.Theme}}.css">
  {{end}}
{{ else if and (ne DefaultTheme "gitea") (ne DefaultTheme "arc-green") }}
	<!-- <link rel="stylesheet" href="/styles.css"> -->
	<!-- <link rel="stylesheet" href="/css/gitea.css"> -->
	<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/gitea-base.css">
	<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/chroma.css">
  <link rel="stylesheet" href="https://theme-park.dev/css/theme-options/{{DefaultTheme}}.css">
{{end}}
```

My container's logs indicate that the /styles.css dans /css/gitea.css aren't found : 
```log
2021/11/17 07:45:01 Completed GET /styles.css 404 Not Found in 20.770057ms
2021/11/17 07:45:01 Completed GET /css/gitea.css 404 Not Found in 20.907167ms
```

**Comment by MilesTEG1** [comment]
But it can't be done easyly for the community themes with an URL like this : "https://theme-park.dev/css/community-theme-options/blackberry-shadow.css"
It requires to test each comunity theme to apply the correct URL...

**Comment by GilbN** [comment]
You can use https://theme-park.dev/css/base/gitea/blackberry-shadow.css

**Comment by MilesTEG1** [comment]
> You can use https://theme-park.dev/css/base/gitea/blackberry-shadow.css
> 
> https://theme-park.dev/css/base/gitea/Theme.css works on everything
Oh ! great !!!
I thought that the URL to use has to be a mirror of your GH repository...
If I check the repo, there is no `blackberry-shadow.css` file in the `css/base/gitea/` folder...


For now, I have this `header.tmpl`
```go
{{ if .IsSigned }}
  {{ if and (ne .SignedUser.Theme "gitea") (ne .SignedUser.Theme "arc-green") }}
    <!-- <link rel="stylesheet" href="/styles.css"> -->
    <!-- <link rel="stylesheet" href="/css/gitea.css"> -->
    <link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/gitea-base.css">
    <link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/chroma.css">    
    
    {{ if (eq .SignedUser.Theme "dracula-test") }}
      <link rel="stylesheet" href="https://theme-park.dev/css/theme-options/dracula.css">
    {{else}}
      <!-- <link rel="stylesheet" href="https://theme-park.dev/css/theme-options/{{.SignedUser.Theme}}.css"> -->
      <link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/{{.SignedUser.Theme}}.css">
    {{end}}

  {{end}}

{{ else if and (ne DefaultTheme "gitea") (ne DefaultTheme "arc-green") }}
	<!-- <link rel="stylesheet" href="/styles.css"> -->
	<!-- <link rel="stylesheet" href="/css/gitea.css"> -->
	<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/gitea-base.css">
	<link rel="stylesheet" href="https://theme-park.dev/css/base/gitea/chroma.css">
  <link rel="stylesheet" href="https://theme-park.dev/css/theme-options/{{DefaultTheme}}.css">
{{end}}
```

ANd for now, it works perfectly :D 
It's simplier than the solution I had in place before (the one I share in #246 ).

Is this a long-lasting URL? (vis-à-vis recent URL changes)

**Comment by Crashdummyy** [comment]
Works for me as well, thanks a lot :)

**Comment by GilbN** [comment]
> Is this a long-lasting URL? (vis-à-vis recent URL changes)

Yeah. The github action creates them here https://github.com/GilbN/theme.park/blob/master/themes.py#L164 and then pushes the changes to the live/live_develop branches. Github pages uses the `live` branch and Netlify uses `live_develop`

**Comment by GilbN** [comment]
> Works for me as well, thanks a lot :)

I'll try and take a look at the code-view css today

**Comment by GilbN** [comment]
@Crashdummyy  @MilesTEG1 New Gitea install instructions: https://docs.theme-park.dev/themes/gitea/

**Comment by MilesTEG1** [comment]
> @Crashdummyy @MilesTEG1 New Gitea install instructions: https://docs.theme-park.dev/themes/gitea/

Could you tell us what is the origin of the change from `header.tmpl` to `body_outer_pre.tmpl`, please ?
Thanks :)

**Comment by GilbN** [comment]
> > @Crashdummyy @MilesTEG1 New Gitea install instructions: https://docs.theme-park.dev/themes/gitea/
> 
> Could you tell us what is the origin of the change from `header.tmpl` to `body_outer_pre.tmpl`, please ? Thanks :)

It adds the stylesheet into the body instead of the head. And that will override stylesheets in the head as its loaded after

**Comment by Crashdummyy** [comment]
> @Crashdummyy @MilesTEG1 New Gitea install instructions: https://docs.theme-park.dev/themes/gitea/

works like a charm, thanks a lot
