### ISSUE TITLE
[BUG] Problem with Calibre-Web docker mod (and Nginx variable)

### ISSUE THREAD

**Issue by madindehead** [GilbN/theme.park#295]
**Describe the bug**
Docker mod for Calibre-Web does not apply the theme to the instance. 
The Nginx variable method also does not work.

**Theme Install Method**
- Compose Config

Using the following line: 

      `- DOCKER_MODS=linuxserver/calibre-web:calibre|ghcr.io/gilbn/theme.park:calibre-web`

**Application Info**
- 0.6.14-ls140
- Main LinuxServer.io version
- LinuxServer.io container - 0.6.14-ls140 (or latest) (https://github.com/linuxserver/docker-calibre-web/releases)

**To Reproduce**
1. Add the Docker mod into Docker Compose file
2. Run the container using `docker-compose up -d`
3. Open Docker logs
4. See error: 

`[cont-init.d] 98-themepark: executing... 
exec: fatal: unable to exec bash: No such file or directory`

**Expected behavior**
The Docker theme should apply to the Calibre-Web instance

**Screenshots**
Not required. Theme just doesn't apply. 

**Additional context**
The theme also doesn't apply when using the Nginx variable. The Nginx variable method is working for other containers (I use it for Portainer), so it's not my setup.

**Comment by GilbN** [comment]
I've updated the docker mod. So try and restart. Also there is a new setup step after calibre-web added CSP.
http://localhost:8000/themes/calibreweb/#setup

**Comment by madindehead** [comment]
Thanks for the fast turnaround. Works perfectly, so closing with this comment.
