### ISSUE TITLE
Portainer plex theme issues

### ISSUE THREAD

**Issue by CooleRnax** [gilbN/theme.park#30]
There are several issues with portainer plex theme.
1. Open Stacks - Open any stack - Open arrow of any service, you will see white themed containers inside service.
2. When you open logs of any container, you will see that logs are white themed.

**Comment by CooleRnax** [comment]
1. 
![image](https://user-images.githubusercontent.com/980180/75021280-2aa4c580-54a5-11ea-8c96-6cd4fc5a4a25.png)
2.
![image](https://user-images.githubusercontent.com/980180/75021358-4f993880-54a5-11ea-9130-eae1c1d67436.png)

**Comment by gilbN** [comment]
Thanks. Will try and have a look this weekend. If you're up to it PRs are welcome.

**Comment by gilbN** [comment]
@CooleRnax 
>Open arrow of any service, you will see white themed containers inside service.

Where is this open arrow?

**Comment by CooleRnax** [comment]
You need to create a service or a stack with a service to service tasks with containers

**Comment by gilbN** [comment]
Hm, I dont really use portainer, and I dont use docker services/swarm?. 
Are you able to inspect which css classes I need to fix?

**Comment by CooleRnax** [comment]
I can inspect, but I don't know what you are looking for

**Comment by gilbN** [comment]
> I can inspect, but I don't know what you are looking for

Think I can use http://demo.portainer.io/#/dashboard

Will check later.

**Comment by gilbN** [comment]
@CooleRnax  check now

**Comment by CooleRnax** [comment]
@gilbN looks good!
