### ISSUE TITLE
Ombi + Docker Mod = Broken

### ISSUE THREAD

**Issue by neo-neo1** [GilbN/theme.park#300]
Any Ombi theme installed with Docker Mod method is broken. I'm using theme.park for 3 other Docker containers just fine but Ombi is not working. Ombi themes do work properly when installed via any other method, only Docker Mod method is broken.

**Bug**

_Docker Log:_
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying gilbn/theme.park:ombi files to container
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Theme Install Method**
- `DOCKER_MODS=ghcr.io/gilbn/theme.park:ombi`

**OmbiInfo** 
- 4.7.6
- Latest
- lscr.io/linuxserver/ombi

**Comment by GilbN** [comment]
There is no docker mod for Ombi. Ombi has custom CSS built in. :)

**Comment by neo-neo1** [comment]
> There is no docker mod for Ombi. Ombi has custom CSS built in. :)

Please add Docker Mod for Ombi. Customizing themes directly from docker-compose adds portability.
