### ISSUE TITLE
Nginx Proxy Manager doesn't apply themes

### ISSUE THREAD

**Issue by Gitoffomalawn** [GilbN/theme.park#301]
I'm using Nginx Proxy Manager for proxying various apps, such as Sonarr and Radarr. I wanted to apply some themes to the from this repository using NPM.

However, after following the installation instructions for NPM, the themes aren't applied. I've tested this on Sonarr, Radarr, and Lidarr. 

Is this a problem in the installation instructions, with NPM, or am I overlooking something (can;t imagine what, the instructions are dead simple)?

**Comment by L-L-MJ** [comment]
Yes it's a problem with the installation instructions for those apps and sabnzbd that I know off (some others do work strangely enough). go to edit proxy hosts and instead of using the advanced tab. Which says at the bottom it will not be used by nginx if you use add_header or set_header directives.

You will need to use the custom locations tab instead.
location / and the cog next to it allows you to enter the code ``proxy_set_header etc.`` there.
That should get you running.

**Comment by Gitoffomalawn** [comment]
Thanks, @L-L-MJ, for pointing me in the right direction. This solved my problem. I still had to figure out some things that weren't in the instructions though, so I'll post my steps below.

---

### Preparation
Go your Proxy Hosts list in NPM, and click the three dots on the rightmost side of the host you want to add a theme to. Select 'Edit' from the menu that appears (first item). Within the edit menu go to 'Custom locations' (second tab).

### Step 1
Click 'Add location'. That will show the 'Define location' options.

![NPM_step1](https://user-images.githubusercontent.com/25043070/146364809-cf1c3bb9-46ea-49db-b38f-037b824c5a2f.png)

### Step 2
Enter '/' in the location bar, and the click the gear to the right of it. That will open the box at the bottom where Nginx config code can be added.

![NPM_step2](https://user-images.githubusercontent.com/25043070/146364935-f40817d2-8430-4590-a115-703fb29b17e6.png)

### Step 3
Fill in the details of the host you're forwarding to. These should be the same as the ones you filled in when you created the host (i.e. the same as in the 'Details' tab (first tab) in the edit menu).

![NPM_step3](https://user-images.githubusercontent.com/25043070/146365362-e9a4586e-aab6-47df-89cc-dcf0c7891e1a.png)

### Step 4
Paste the Nginx code from [step 3 of the Nginx Proxy Manager config instructions](https://docs.theme-park.dev/setup/#nginx-proxy-manager) in the box at the bottom. Don't forget to update the `<APP_NAME>` and `<THEME>` with the correct app and theme.

![NPM_step4](https://user-images.githubusercontent.com/25043070/146365672-5329a865-23d6-4004-945c-9e61b70f75e8.png)

### Step 5
Click 'Save'. Your theme should now work.

---

I'll leave this issue open, and let one of the project owners close it, just to make sure they saw it in case they wanted to update the install instructions with these alternative steps.

**Comment by L-L-MJ** [comment]
Sorry @Gitoffomalawn I should have taken the time to give a more in depth explanation. I did like a week ago on discord. Nice write up though! glad you got it working.

**Comment by GilbN** [comment]
@Gitoffomalawn Great! 

Want to PR the changes on https://github.com/GilbN/tp-docs/blob/main/docs/setup.md ?

Use this image instead of all 4. :)
![image](https://user-images.githubusercontent.com/24592972/146405314-1dce1569-52f5-4e73-a06a-b1001b41f468.png)

**Comment by Gitoffomalawn** [comment]
@L-L-MJ: No sweat. I don't mind doing a writeup once in a while.

@GilbN: Sure! I'll get that to you ASAP (probably somewhere in the next 36 hours). And good call on using only one image. Should make the whole thing more readable.

**Comment by Gitoffomalawn** [comment]
@GilbN: My day was a little slower than I expected, so I've managed to get the PR out to you. It's [here](https://github.com/GilbN/tp-docs/pull/13).

**Comment by GilbN** [comment]
Thanks, looks good :)
