### ISSUE TITLE
Vaultwarden/Bitwarden theme no longer working after last update.

### ISSUE THREAD

**Issue by BaukeZwart** [GilbN/theme.park#304]
**Describe the bug**
After the latest Vaultwarden update the organizr theme isn't working anymore.

**Theme Install Method** (Don't skip)
- Webserver subfilter Config/NPM

**Application Info** (Don't skip)
- 2.25.0
- Latest
- vaultwarden/server

**To Reproduce**
1. Open login screen
2. Theme isn't working

**Expected behavior**
Working theme

**Screenshots**

![NFtOGbMGBi](https://user-images.githubusercontent.com/1872733/147094701-757ee537-c4f5-4185-98ed-4191b65b2570.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Win 11
 - Browser: chrome
 - Version: 96.0.4664.110

**Comment by GilbN** [comment]
@BaukeZwart try the develop branch now

**Comment by aussiehuddo** [comment]
same issue with sonarr and radarr. themes not working

**Comment by GilbN** [comment]
> same issue with sonarr and radarr. themes not working

Those are working fine here.

**Comment by aussiehuddo** [comment]
> > same issue with sonarr and radarr. themes not working
> 
> Those are working fine here.

they are now upon another restart. cheers

**Comment by GilbN** [comment]
@BaukeZwart Looks like they added dark/light theme options that is doing it. I pushed some changes, but might still be some jank in there

**Comment by BaukeZwart** [comment]
@GilbN looking good.
At first glance everything is looking good again.
I will check the various pages, if I find anything I will report back.
Thanks for the fix and all the best for next year.
