### ISSUE TITLE
Prowlarr App Profiles - no text shown (Gray)

### ISSUE THREAD

**Issue by bakerboy448** [GilbN/theme.park#306]
**Describe the bug**
Fixups needed with app profiles

![image](https://user-images.githubusercontent.com/55419169/147140327-88dbe6c6-62c7-405b-ad6d-8964634ee10a.png)
dark theme

**Theme Install Method** (Don't skip)
- Webserver subfilter Config

**Application Info** (Don't skip)
- Version 0.1.8.1265
- Branch nightly
- Container n/a

**To Reproduce**
view app profiles; can't see disabled text

**Expected behavior**
should be able to view text

**Screenshots**
see above

**Desktop (If applicable) (please complete the following information):**
n/a

**Smartphone (If applicable) (please complete the following information):**
n/a

**Additional context**
Looks like just some css or color updates

**Comment by GilbN** [comment]
Hm, wierd. Im on the same version now, and I don't see that. 
https://selfhosted.app/f3c10/xoHejUBe36.png/raw

Can you try and inspect the elements to see what overrides it?
