### ISSUE TITLE
qBittorrent bug when going to copy menu

### ISSUE THREAD

**Issue by bobokun** [GilbN/theme.park#307]
**Describe the bug**
Trying to copy a torrents hash with theme park on does not work.

**Theme park OFF**
![image](https://user-images.githubusercontent.com/12660469/147514135-ed429115-77bc-4b36-80f2-21561e21d8e8.png)
**Theme Park ON**
![image](https://user-images.githubusercontent.com/12660469/147514176-8f5c4545-eba4-4298-bb05-91df70bfbfe4.png)

**Theme Install Method** (Don't skip)
`docker run -d --name='qbittorrent' --net='proxynet' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TP_HOTIO'='true' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='002' -p '83:8080/tcp' -v '/mnt/cache/appdata/qbittorrent':'/config':'rw' -v '/mnt/user/data/torrents/':'/data/torrents/':'rw' -v '/mnt/cache/appdata/theme.park/docker-mods/qbittorrent/root/etc/cont-init.d/98-themepark':'/etc/cont-init.d/99-themepark':'ro' --restart unless-stopped 'cr.hotio.dev/hotio/qbittorrent'`

**Application Info** (Don't skip)
cr.hotio.dev/hotio/qbittorrent

**To Reproduce**
Right click any torrent and hover over Copy

**Expected behavior**
Should see Hash instead of Info hashv1 and Info hash v2

**Comment by GilbN** [comment]
hm, can you add -`e TP_DISABLE_THEME='true' ` and use the subfilter method to apply the theme?
I suspect this happens because the mod downloads the qbittorrent UI https://github.com/GilbN/theme.park/blob/master/docker-mods/qbittorrent/root/etc/cont-init.d/98-themepark#L71
and its not exactly the same.

**Comment by bobokun** [comment]
Can confirm that using subfilter method instead of docker_mods works.

**Comment by bobokun** [comment]
I noticed the link seems to be invalid in https://github.com/GilbN/theme.park/blob/0a3771420ec3a2de4cf30c1d4383db067e70ba16/docker-mods/qbittorrent/root/etc/cont-init.d/98-themepark#L77

Could that be the root cause of the issue?

**Comment by GilbN** [comment]
No that's the correct url when using svn

**Comment by GilbN** [comment]
Upstream issue, can't fix.
