### ISSUE TITLE
Radarr Dropdowns are blinding White

### ISSUE THREAD

**Issue by bakerboy448** [GilbN/theme.park#308]
**Describe the bug**
Settings drop down are blinding white for all settings pages

This was also an issue in Prowlarr and I would expect it to be an issue for all \*arrs as well

**Theme Install Method** (Don't skip)
- Webserver subfilter Config

**Application Info** (Don't skip)
- Version 4.0.0.5724
- Branch nightly 
- Container NA

**To Reproduce**
Open any settings drop down and be blinded by white

**Expected behavior**
Dark theme should be respected

**Screenshots**

![7523BD9E-184A-44A2-BC9E-64E414A253CB](https://user-images.githubusercontent.com/55419169/147841765-d1fd1fd8-2c4f-47ad-b68d-e7df07ea5adf.jpeg)

**Smartphone (If applicable) (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12P
 - OS: [e.g. iOS8.1] 15.2
 - Browser [e.g. stock browser, safari] chrome
 - Version [e.g. 22] 96.0.4664.116

**Additional context**

**Comment by GilbN** [comment]
Should be good now
