### ISSUE TITLE
Caddy compatible ?

### ISSUE THREAD

**Issue by Nosirus** [gilbN/theme.park#31]
I'm thinking of switching to caddy server, the css are compatible with? I didn't find much information on that.

**Comment by gilbN** [comment]
Perhaps. https://github.com/echocat/caddy-filter/issues/39
You could ask the devs of caddy filter if they could provide an example.

**Comment by gilbN** [comment]
Or maybe @STaRDoGG has an example he can share? ref https://caddy.community/t/issue-with-filter-plugin/5411

**Comment by gilbN** [comment]
@Nosirus  If you find a working config please let me know

**Comment by nawuko** [comment]
I have been using caddy, i used docker labels for the filter like that:

```
"caddy.filter": "rule"
"caddy.filter.content_type": "text/html.*"
"caddy.filter.search_pattern": "</head>"
"caddy.filter.replacement": "\"<link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/tautulli/dark.css'></head>\""
```

which would be translate to a config file like this:

```
  filter rule {
      content_type text/html.*
      search_pattern </head>
      replacement "<link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/tautulli/dark.css'></head>"
  }
```

Hope this helps

**Comment by gilbN** [comment]
@nawuko  Thanks! Will add this to the wiki!

**Comment by gilbN** [comment]
@nawuko for subfolders is this correct?

```nginx
filter rule {
path /tautulli
    content_type text/html.*
    search_pattern </head>
    replacement "<link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/tautulli/dark.css'></head>"
}
```

I guess this will also work?

```nginx
proxy /plexpy 172.18.0.10:8181 {
    header_upstream Host {host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Proto {scheme}
    header_upstream X-Forwarded-Host {host}
    header_upstream X-Forwarded-Ssl {on}
filter rule {
    content_type text/html.*
    search_pattern </head>
    replacement "<link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/tautulli/dark.css'></head>"
}
    }
```

And for subdomains I guess you dont need the path line just the filter rule block right?

**Comment by STaRDoGG** [comment]
Sorry, I'm down with the friggin flu atm, so I kida just speed-read this thread, so if I didn't fully get the gist of the question .... *shrug* lol

Here's an example of how I added my won .css to Deluge, via the Caddyfile:

```
(Filters) {
  # Snippet: Replacement Filters
  # Requires: http.filter

  # Add Dark CSS Theme to Deluge WebUI
  filter rule {
      path /delugedoc
      content_type text/html.*
      search_pattern "</head>"
      replacement "<link rel='stylesheet' type='text/css' href='https://stardogg.github.io/Deluge-Dark/deluge.css'>\n</head>"
  }
```

Then in the regular server block:
```
import Filters
```

That said, I ended up throwing in the towel on Caddy and going with Nginx. The support for Caddy is patchy and you can go for weeks just fighting with one issue to get working, only to do the exact same thing for the next problem that crops up. With Nginx it's been smooth sailing, and I can spend that time actually being productive and moving forward than just fighting with getting something to work. YMMV
