### ISSUE TITLE
Stylus Method don't work since 1.6.9 version

### ISSUE THREAD

**Issue by fana13** [GilbN/theme.park#311]
**Describe the bug**

**Theme Install Method** (Don't skip)
- Stylus Config

**Application Info** (Don't skip)
- Version 1.6.9

Since last update, all sytlus methods don't work.
Syntax is same but none css work (Sonarr, Radarr, Lidarr, Jackett, etc...)

**Comment by GilbN** [comment]
Yeah, Just update to the correct url paths. 
This was a planned change. 
https://github.com/GilbN/theme.park/releases/tag/1.6.9

https://github.com/GilbN/theme.park/releases/tag/1.6.1

https://github.com/GilbN/theme.park/releases/tag/1.6.0

**Comment by fana13** [comment]
Thank for your reply but i'm on correct url paths since 1.6.0
https://theme-park.dev/css/base/radarr/radarr-base.css don't work on stylus method for me
Like https://theme-park.dev/css/base/sonarr/sonarr-base.css or https://theme-park.dev/css/base/jackett/jackett-base.css
etc...

**Comment by GilbN** [comment]
> Thank for your reply but i'm on correct url paths since 1.6.0 https://theme-park.dev/css/base/radarr/radarr-base.css don't work on stylus method for me Like https://theme-park.dev/css/base/sonarr/sonarr-base.css or https://theme-park.dev/css/base/jackett/jackett-base.css etc...

share your whole stylus config

**Comment by fana13** [comment]
@import "https://theme-park.dev/css/base/radarr/radarr-base.css";
@import "https://theme-park.dev/CSS/addons/radarr/radarr-4k-logo/radarr-4k-logo.css";
@import "https://theme-park.dev/CSS/addons/radarr/radarr-darker/radarr-darker.css";

**Comment by GilbN** [comment]
> @import "https://theme-park.dev/css/base/radarr/radarr-base.css"; @import "https://theme-park.dev/CSS/addons/radarr/radarr-4k-logo/radarr-4k-logo.css"; @import "https://theme-park.dev/CSS/addons/radarr/radarr-darker/radarr-darker.css";

The last two are wrong. needs to be `css`

**Comment by fana13** [comment]
Sorry for your lost time...
Many thanks !
