### ISSUE TITLE
Organizr Themes Not Working

### ISSUE THREAD

**Issue by MRobi1** [GilbN/theme.park#312]
Opened my browser last night to find a white sidebar (using dark_theme_park). Was fine earlier in the day. No config changes were made on my end. Regardless of which theme park theme I select they are no longer applying. Non-theme park themes work fine. Tried on Edge, Chrome and Firefox as well as on 2 pc's to rule out it being a browser or cache issue.

**Theme Install Method** (Don't skip)
Through organizr marketplace

**Application Info** (Don't skip)
Organizr v2.1.1140

![clip](https://user-images.githubusercontent.com/34860474/148097659-774a6f80-fc42-47fc-958e-37c5133c4f40.jpg)

**Comment by GilbN** [comment]
try and delete and reinstall the themes. If that doesnt work clear your cache, and if you use cloudflare , clear that cache too.

**Comment by totof-l** [comment]
> try and delete and reinstall the themes. If that doesnt work clear your cache, and if you use cloudflare , clear that cache too.

Hi, I've got the same issue.
Reinstalling the theme and clear the cache solved it for me :)

**Comment by Hendo-AU** [comment]
I'm using Stylus and noticed my themes are no longer working today, Tried deleting and re-adding the themes but didn't work.

Can't figure out how to fix it.

**Comment by GilbN** [comment]
> I'm using Stylus and noticed my themes are no longer working today, Tried deleting and re-adding the themes but didn't work.
> 
> Can't figure out how to fix it.

Update your url paths to the correct ones.

**Comment by Hendo-AU** [comment]
> Update your url paths to the correct ones.

Oh ok I didn't realize that they had changed, Thanks.

**Comment by MRobi1** [comment]
> > try and delete and reinstall the themes. If that doesnt work clear your cache, and if you use cloudflare , clear that cache too.
> 
> Hi, I've got the same issue. Reinstalling the theme and clear the cache solved it for me :)

This was the first thing I did last night and didn't work. Just tried it again and I'm back in business.
