### ISSUE TITLE
Nginx subfilter Dark css theme stopped working

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#313]
**Describe the bug**
I use nginx subfilter to add dark css themes.  It just stopped working today.  Did anything change or break?  Nothing has changed on my setup. 

**Theme Install Method**  nginx subfilter css
- Docker run / Compose Config
- Webserver subfilter Config
- Stylus Config

**Application Info** (Don't skip)
- Version
- Branch
- Container

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by GilbN** [comment]
Se latest release notes https://github.com/GilbN/theme.park/releases/tag/1.6.9
