### ISSUE TITLE
SABnzbd caret not showing

### ISSUE THREAD

**Issue by h3llrais3r** [GilbN/theme.park#317]
**Describe the bug**
Theme park theme not showing sabnzbd caret (see screenshot)

**Theme Install Method** (Don't skip)
- Webserver subfilter Config

**Application Info** (Don't skip)
- Version: Sabnzbd 3.4.2
- Branch: master
- Container: windows installer

**To Reproduce**
Install theme with webservice filter config and apply 'nord' theme.

**Expected behavior**
To see the dropdown caret for changing some settings on the item in the queue.

**Screenshots**
Original:
![image](https://user-images.githubusercontent.com/1945295/149834844-e10b2b31-570c-49cc-a075-1cfe0fd014b0.png)

With theme (nord):
![image](https://user-images.githubusercontent.com/1945295/149835078-fc5e50a9-2b11-4547-9cef-65312ea22664.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Comment by GilbN** [comment]
Fixed on develop

**Comment by h3llrais3r** [comment]
Which url should I use for testing develop branch?
I'm now using: https://theme-park.dev/css/base/sabnzbd/nord.css which is probably only master?

**Comment by GilbN** [comment]
https://develop.theme-park.dev/css/base/sabnzbd/nord.css

**Comment by h3llrais3r** [comment]
Oh, I'm already using the develop branch in that case... What's the url for the master branch then? Because I followed the installation instructions which by default tells to use that dev url.

**Comment by GilbN** [comment]
Which installation instructions?

**Comment by h3llrais3r** [comment]
https://docs.theme-park.dev/setup/#apache

**Comment by GilbN** [comment]
That doesn't say to use the develop.theme-park.dev url?

Anyways the latest commit on develop fixes the caret

**Comment by h3llrais3r** [comment]
Ah, sorry, did not see the develop in front of the domain name... my bad.
Trying it out now with the develop url.

**Comment by h3llrais3r** [comment]
Great, it's working.
![image](https://user-images.githubusercontent.com/1945295/149840611-a828bdeb-3092-4236-92d9-e21619f7a5c9.png)

Thanks for great themes an awesome support. 👍
