### ISSUE TITLE
Gitea: Cursor not visible in div.CodeMirror-scroll

### ISSUE THREAD

**Issue by Crashdummyy** [GilbN/theme.park#319]
**Describe the bug**
When I want to edit an issue in gitea I cant see the cursor at all.

**Theme Install Method** (Don't skip)
-[Plan installation](https://docs.theme-park.dev/themes/gitea/)

**Application Info** (Don't skip)
- 1.16.0

**To Reproduce**
* Open an Issue
* Type something in comment or issue description
* Dont see the cursor

**Expected behavior**
The cursor is white... and blinks 

**Screenshots**

**Additional context**
Used to be a Problem in gitea..

Adding this to your stylesheet apparently helped.
```css
.CodeMirror-cursor {
  border-color: var(--color-text) !important;
}
```

** Screenshots
## Actual
![actual](https://user-images.githubusercontent.com/15139403/152064819-df3b79c4-283a-41c6-aaf8-d6f303ca3265.png)

## Excpected ( css from above )
![expected](https://user-images.githubusercontent.com/15139403/152064892-549ef8c2-0e48-477a-93bc-2a7ebc9b8059.png)

**Comment by GilbN** [comment]
Pushed a fix to dev. Please test develop.theme-park.dev

**Comment by Crashdummyy** [comment]
> Pushed a fix to dev. Please test develop.theme-park.dev

It now works :)
