### ISSUE TITLE
Bazarr Aquamarine and NGINX Variable Method

### ISSUE THREAD

**Issue by therealatreides** [gilbN/theme.park#32]
Got several supported apps working, but Bazarr does not seem to work with Aquamarine on using the variable method with nginx.

**Comment by gilbN** [comment]
Specific page/div or just the whole theme. Other themes work?

**Comment by gilbN** [comment]
![image](https://user-images.githubusercontent.com/24592972/75919618-2b066e80-5e5e-11ea-8b4c-df691b2decb9.png)

Works here?

**Comment by therealatreides** [comment]
Upgraded to latest version of Bazarr, same thing.

My bazarr conf set up correctly, and works on radarr, transmission, etc. Just bazarr having the issue. Below is the bazarr conf

`location /bazarr/ {
    proxy_pass          http://127.0.0.1:30431;
    proxy_redirect      off;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    #access_log logs/bazarr.access.log;
    #error_log  logs/bazarr.error.log;
    set $app bazarr;
    include theme-park.conf;
}
`

**Comment by gilbN** [comment]
`include theme-park.conf;` is that line correct?

**Comment by therealatreides** [comment]
Should be. All my other confs are set up the same way.

**Comment by gilbN** [comment]
tried without variable?

**Comment by therealatreides** [comment]
Same thing. Must be something with the nginx setup. I am not seeing anything related in the html source of the generated page either.

![image](https://user-images.githubusercontent.com/47747094/75930278-3a76bf00-5e40-11ea-8305-ea0718cdb9f8.png)

**Comment by gilbN** [comment]
try and use what the dev recommends https://github.com/morpheus65535/bazarr/wiki/Reverse-proxy-Nginx

**Comment by therealatreides** [comment]
Yeah, definitely something at the box's end. Still nada. Will follow up there to see what I can find. Nothing on your end for sure.
