### ISSUE TITLE
PiHole-plugin in Organizr has partially missing background due to inheritance of "bg-inverse" lately

### ISSUE THREAD

**Issue by systemofapwne** [GilbN/theme.park#320]
**Describe the bug**
Some weeks ago, my PiHole indicator in organizr started missing the background-color for Queries Blocked, Percent Blocked and Domains on Blocklist but not for Total queries.
I might have traced it back to around this commit, where the CSS class _bg-inverse_ has been modified: https://github.com/GilbN/theme.park/commit/fe739621da96e0b8aa21e0ecda26c7a073398c41#diff-57cd7f84a310a63392db1f3014f1fd5423e97478b3d75d62a536bc9f5b0b6277

It looks like, that the three panels in question derive their style also from _bg-inverse_ (which sets ``background: transparent !important;``) while the Total queries does not and thus is unaffected.

**Theme Install Method**
- CSS include directly in Organizr, pointing to this very git-repo, locally hosted on my webserver on latest commit@master.
```
@import url("https://MY.TLD/themepark/css/base/organizr/organizr-base.css");
@import url("https://MY.TLD/themepark/css/theme-options/nord.css");
```

**Application Info**
- Application: Organizr
- Version: Latest git commit
- Branch: v2-develop
- Container: organizr/organizr

**To Reproduce**
1. Go to Settings/Tab Editor/Homepage-Elements
2. Click on PI-HOLE/connection
3. Point it to your ``http://<Piholeip>/admin/`` page
4. Watch the "Homepage" of Organizr missing the panel-backgrounds

**Expected behavior**
Panel-Backgrounds all show properly

**Screenshots**
What I expect to see
![Screenshot_20220203_223057](https://user-images.githubusercontent.com/30482165/152433849-45c58b62-15d7-4d3a-9166-ba7c17c61da0.png)

What I actually see
![Screenshot_20220203_223158](https://user-images.githubusercontent.com/30482165/152433852-8b3ac66a-4326-4b08-8383-a578124d929d.png)

**Desktop:**
 - OS: Manjaro Linux
 - Browser: Chrome, Firefox
 - Version: Most recent

**Comment by GilbN** [comment]
Pushed a fix to dev. Please test develop.theme-park.dev

**Comment by systemofapwne** [comment]
I can confirm, that this fixed it.
