### ISSUE TITLE
Most themes (for gitea) leave line numbers unreadable

### ISSUE THREAD

**Issue by embeddedpenguin** [GilbN/theme.park#321]
onedark:
![image](https://user-images.githubusercontent.com/33668314/153563498-7b896ec6-e250-4491-b606-f38a276556e8.png)

overseerr:
![image](https://user-images.githubusercontent.com/33668314/153563738-4985d13a-949b-44bd-8a98-0b77261f4b2d.png)

I could change this in `.lines-num` if that helps at all. I don't want to submit a pr for a css change because I would have no idea what I'm doing.

Most of the themes mentioned [here](https://docs.theme-park.dev/themes/gitea/) are affected by this.

**Comment by GilbN** [comment]
> onedark: ![image](https://user-images.githubusercontent.com/33668314/153563498-7b896ec6-e250-4491-b606-f38a276556e8.png)
> 
> overseerr: ![image](https://user-images.githubusercontent.com/33668314/153563738-4985d13a-949b-44bd-8a98-0b77261f4b2d.png)
> 
> I could change this in `.lines-num` if that helps at all. I don't want to submit a pr for a css change because I would have no idea what I'm doing.
> 
> Most of the themes mentioned [here](https://docs.theme-park.dev/themes/gitea/) are affected by this.

Pushed a fix to dev. Please test develop.theme-park.dev

**Comment by embeddedpenguin** [comment]
> > onedark: ![image](https://user-images.githubusercontent.com/33668314/153563498-7b896ec6-e250-4491-b606-f38a276556e8.png)
> > overseerr: ![image](https://user-images.githubusercontent.com/33668314/153563738-4985d13a-949b-44bd-8a98-0b77261f4b2d.png)
> > I could change this in `.lines-num` if that helps at all. I don't want to submit a pr for a css change because I would have no idea what I'm doing.
> > Most of the themes mentioned [here](https://docs.theme-park.dev/themes/gitea/) are affected by this.
> 
> Pushed a fix to dev. Please test develop.theme-park.dev

The way I'm applying these themes is via this method: https://docs.theme-park.dev/themes/gitea/#adding-the-themes-in-gitea I'm not sure how to test changes on another branch because `https://theme-park.dev/css/base/gitea/<theme_name_here>.css` is hard pointing at a page.

**Comment by embeddedpenguin** [comment]
> > > onedark: ![image](https://user-images.githubusercontent.com/33668314/153563498-7b896ec6-e250-4491-b606-f38a276556e8.png)
> > > overseerr: ![image](https://user-images.githubusercontent.com/33668314/153563738-4985d13a-949b-44bd-8a98-0b77261f4b2d.png)
> > > I could change this in `.lines-num` if that helps at all. I don't want to submit a pr for a css change because I would have no idea what I'm doing.
> > > Most of the themes mentioned [here](https://docs.theme-park.dev/themes/gitea/) are affected by this.
> > 
> > 
> > Pushed a fix to dev. Please test develop.theme-park.dev
> 
> The way I'm applying these themes is via this method: https://docs.theme-park.dev/themes/gitea/#adding-the-themes-in-gitea I'm not sure how to test changes on another branch because `https://theme-park.dev/css/base/gitea/<theme_name_here>.css` is hard pointing at a page.

Ok nevermind I realize now... I didn't realize "develop" was a subdomain to theme-park.dev. Tested and working great!

onedark
![image](https://user-images.githubusercontent.com/33668314/153799226-fafac111-764f-4aaa-8449-adbd736892b8.png)

organizr
![image](https://user-images.githubusercontent.com/33668314/153799273-0209317c-7dfd-433e-b82a-3fa5f5a305b7.png)

overseerr
![image](https://user-images.githubusercontent.com/33668314/153799474-5b1eeaf4-6646-4aba-8aa9-ac3f2ffbdc9c.png)

**Comment by embeddedpenguin** [comment]
Thank you for the quick fix!
