### ISSUE TITLE
Dark qBittorrent resolution issue

### ISSUE THREAD

**Issue by K6TPg6g9f** [gilbN/theme.park#33]
There seem to be an issue with the dark qbittorrent theme and resolution. By default when I load the page on my 1440p monitor, the download section is completely blank until I zoom in/out manually with [CTRL] + [+].

It is not limited to 1440 either, when at work on a 1080p monitor, it loads by default, but when zooming in or out at certain levels, again the entries become blank.

![Capture](https://user-images.githubusercontent.com/56618593/76473061-48ec4a00-63ef-11ea-824c-eab271caf3c7.JPG)

**Comment by gilbN** [comment]
Thanks. I will have a look
