### ISSUE TITLE
Can't install deluge theme

### ISSUE THREAD

**Issue by SuberSeb** [GilbN/theme.park#332]
**Describe the bug**
Theme organizr for Deluge is not working after latest container update on 17 March. Before that theme was working as expected.

**Theme Install Method** (Don't skip)
Docker Variables:
- DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
- TP_THEME=organizr

**Application Info** (Don't skip)
- Version: Deluge 2.0.5
- Branch: latest
- Container: linuxserver/deluge

**To Reproduce**
1. Install theme organizr.

**Expected behavior**
Organizr theme should be working.

**Comment by SuberSeb** [comment]
Here is logs:

---------------------------
| Deluge theme.park Mod |
---------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_THEME'=organizr

No domain set, defaulting to theme-park.dev
grep: /usr/lib/python3/dist-packages/deluge/ui/web/index.html: No such file or directory
---------------------------
| Adding the stylesheet |
---------------------------
sed: /usr/lib/python3/dist-packages/deluge/ui/web/index.html: No such file or directory
sed: /usr/lib/python3/dist-packages/deluge/ui/web/index.html: No such file or directory
Stylesheet set to organizr

[cont-init.d] 98-themepark: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by GilbN** [comment]
Try now, pushed a fix

**Comment by SuberSeb** [comment]
Seems something is broken, get stucked at this:
`---------------------------
| Deluge theme.park Mod |
---------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_THEME'=organizr

No domain set, defaulting to theme-park.dev`

**Comment by SuberSeb** [comment]
It's working, thanks.
