### ISSUE TITLE
Bazarr sidebar style wrong after beta 9

### ISSUE THREAD

**Issue by sambartik** [GilbN/theme.park#334]
**Describe the bug**
The sidebar background color is off after Bazarr UI refactor that was released in beta 9.

**To Reproduce**
No additional steps needed except having installed Bazarr [v1.0.4-beta.9](https://github.com/morpheus65535/bazarr/releases/tag/v1.0.4-beta.9) or greater.

**Expected behavior**
Sidebar background should look like in previous Bazarr releases.

**Screenshots**
![sidebar](https://user-images.githubusercontent.com/63553146/159121878-1c6b6af7-ede1-4877-98db-167bf67832fc.png)

**Additional context**
Class names have changed [upstream](https://github.com/morpheus65535/bazarr/issues/1767#issuecomment-1072934198).

**Comment by GilbN** [comment]
Fixed on develop.
