### ISSUE TITLE
Plex Match modal not fully themed

### ISSUE THREAD

**Issue by Roxedus** [gilbN/theme.park#34]
Reproduce steps:
(Download stupid file
Manually fix its metadata)
Fix match in plex

![image](https://user-images.githubusercontent.com/7110194/77780753-c56c6300-7054-11ea-9c8b-bf488286ba08.png)

**Comment by Roxedus** [comment]
This bg also shows like this on "get info"

**Comment by Roxedus** [comment]
Its alright 
![image](https://user-images.githubusercontent.com/7110194/78051986-c2d47b00-737e-11ea-943f-d7b445c93bd8.png)

**Comment by gilbN** [comment]
hm
![image](https://user-images.githubusercontent.com/24592972/78052178-05965300-737f-11ea-9d7d-e6c8a16dbd57.png)
