### ISSUE TITLE
Is there a way to use selfhosted CSS themes without domain?

### ISSUE THREAD

**Issue by SuberSeb** [GilbN/theme.park#341]
I want to selfhost CSS themes on my server via Docker, but I don't want to use domain and HTTPS, I'm planning to use CSS themes only in LAN, so domain is not what I want. How can I use selfhosted themes for linuxserver.io containers?

As I can see in code, HTTPS is hardcoded - https://github.com/GilbN/theme.park/blob/master/docker-mods/radarr/root/etc/cont-init.d/98-themepark#L50. It may be worth putting the protocol selection in the parameter, so we can choose between HTTP and HTTPS? Or is there another way to use selfhosted themes in linuxserver.io containers?

**Comment by GilbN** [comment]
Yeah, thought about that yesterday. Gonna update the mods with a SCHEME env

**Comment by GilbN** [comment]
I've updated the mods, try and set TP_SCHEME=http

**Comment by SuberSeb** [comment]
Excellent, thank you! Selfhosted themes are working now.

**Comment by GilbN** [comment]
Great! Thanks for confirming.

**Comment by SuberSeb** [comment]
Something wrong with deluge and self hosted themes. I have installed organizr theme, seems that the most part of theme is loaded, but all icons are missing. With not self hosted theme all is okay. Can you check please?

**Comment by GilbN** [comment]
What does the browser console output?

**Comment by GilbN** [comment]
No 404 errors etc?

**Comment by SuberSeb** [comment]
No, see only 200 in every query, so all seems to be loaded. Strange

**Comment by SuberSeb** [comment]
Hmm, I have found the issue. There are no port in the link to icon.

Example:
Trying to load icon from this http://192.168.1.45/resources/deluge/add_small.png, but I have theme.park working at http://192.168.1.45:1234/resources/deluge/add_small.png. So there are no icon at the port 80.

**Comment by GilbN** [comment]
Did you set TP_DOMAIN=<ip>:<port> or just <ip>?

**Comment by SuberSeb** [comment]
TP_DOMAIN=192.168.1.1:1234

**Comment by SuberSeb** [comment]
Sure, I will try it and provide result

**Comment by SuberSeb** [comment]
Checked with previous settings (not switched to develop) - icons is working.

**Comment by GilbN** [comment]
Nice. Yeah pushed a new version on the `latest` tag

**Comment by SuberSeb** [comment]
Icons missing again. I can see in the browser console that deluge tries to download icons from https://192.168.1.1:1234/ using HTTPS but I set up to use HTTP.

**Comment by GilbN** [comment]
Try to pull latest. There was some changes yesterday

**Comment by SuberSeb** [comment]
All seems to be updated, but icons are still missing.

**Comment by GilbN** [comment]
check if the `develop` tag fixes it
