### ISSUE TITLE
Radarr calendar line vs fill

### ISSUE THREAD

**Issue by macbean101** [GilbN/theme.park#345]
**Describe the bug**
On the calendar, for movies I have, the block is filled as green.  For other statuses, the block is grey with the appropriate colored line on the left (same as how both sonarr and radarr show things by default).  using the same info in my nginx subfilter, sonarr shows as expected with the entire block of the appropriate color. 

I've tried this with different themes 

**Theme Install Method** (Don't skip)
```
                proxy_set_header Accept-Encoding "";
                sub_filter
                '</head>'
                '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/radarr-base.css">
                <link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/theme-options/nord.css">
                </head>';
                sub_filter_once on;
```

**Application Info** (Don't skip)
Radarr 4.0.5.5981

**To Reproduce**
view calendar (month vs week vs day, doesn't matter)

**Expected behavior**
would expect each block to be 'filled' 

**Screenshots**
attaching sonarr_tp.jpg as example of what is expected and radarr_tp.jpg as what I see. 
![radarr_tp](https://user-images.githubusercontent.com/25144645/160236258-6c436a28-c3d9-4ffb-becf-1696469ab31a.jpg)

![sonarr_tp](https://user-images.githubusercontent.com/25144645/160236261-2ac059aa-26c7-44a9-9e2b-5c17e1baebb2.jpg)

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by GilbN** [comment]
Is death on the nile and morbuis downloaded but set to unmonitored?

**Comment by macbean101** [comment]
no, both are monitored but unavailable. The blue line on the left of the block is correct, but shouldn't that color fill the block the way green does for downloade?

**Comment by GilbN** [comment]
I pushed a fix to develop.theme-park.dev now

**Comment by macbean101** [comment]
my very mild ocd thanks you!
![image](https://user-images.githubusercontent.com/25144645/160286782-5382e438-5b93-4880-a406-47ff9fead4c9.png)

**Comment by GilbN** [comment]
Nice, thanks for confirming

**Comment by macbean101** [comment]
I just noticed that queued movies do the same thing.  

![image](https://user-images.githubusercontent.com/25144645/160287230-fd5bce7f-5860-4186-a016-aa3c3a0c9976.png)

**Comment by GilbN** [comment]
Should be good now

**Comment by macbean101** [comment]
Confirmed
