### ISSUE TITLE
Docker image: Not all URL's set as HTTPS

### ISSUE THREAD

**Issue by jpdsc** [GilbN/theme.park#346]
I took the time to set up the new Theme.park docker image and have everything locally.
In the docker-compose file I have set:

```
- TP_DOMAIN=themepark.DOMAIN
- TP_SCHEME=https
```

However, on some apps it give an error in console. Not sure if related to Theme.park. Perhaps something is not mapped correctly where it sets http or https based on the env.

Bazarr:
`Mixed Content: The page at 'https://organizr.DOMAIN/#Bazarr' was loaded over HTTPS, but requested an insecure stylesheet 'http://DOMAIN/css/defaults/placeholders.css'. This request has been blocked; the content must be served over HTTPS.`

Nzbget:
`Mixed Content: The page at 'https://nzbget.DOMAIN/' was loaded over HTTPS, but requested an insecure element 'http://themepark.DOMAIN/resources/nzbget/icons.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`

Portainer:
`Mixed Content: The page at 'https://organizr.DOMAIN/#Portainer-Nas-01' was loaded over HTTPS, but requested an insecure stylesheet 'http://themepark.DOMAIN/css/defaults/placeholders.css'. This request has been blocked; the content must be served over HTTPS.`

Pi-Hole (Not sure if same issue):
`Refused to load the stylesheet 'http://themepark.DOMAIN/css/defaults/placeholders.css' because it violates the following Content Security Policy directive: "style-src 'self' https://themepark.DOMAIN 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.`

**Comment by GilbN** [comment]
Can you test the develop tag? Pushed a fix

**Comment by jpdsc** [comment]
> Can you test the develop tag? Pushed a fix

@GilbN 

Just tested it, all fixed. Error's are no longer there.
Anything else you want me to test now that I have dev image loaded?

**Comment by GilbN** [comment]
No thats fine. Thanks for confirming
