### ISSUE TITLE
Multi arch images

### ISSUE THREAD

**Issue by agneevX** [GilbN/theme.park#349]
Would be helpful on Raspberry Pis.

**Comment by GilbN** [comment]
Can you test ghcr.io/gilbn/theme.park:testing

**Comment by agneevX** [comment]
:(

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by agneevX** [comment]
This is:

```
~> docker pull ghcr.io/gilbn/theme.park:testing@sha256:b07dead82ab3138a20c86d567e21a176ca8f6b4e07c1c49c
d86c305af9144803
ghcr.io/gilbn/theme.park@sha256:b07dead82ab3138a20c86d567e21a176ca8f6b4e07c1c49cd86c305af9144803: Pulling from gilbn/theme.park
Digest: sha256:b07dead82ab3138a20c86d567e21a176ca8f6b4e07c1c49cd86c305af9144803
Status: Downloaded newer image for ghcr.io/gilbn/theme.park@sha256:b07dead82ab3138a20c86d567e21a176ca8f6b4e07c1c49cd86c305af9144803
ghcr.io/gilbn/theme.park:testing@sha256:b07dead82ab3138a20c86d567e21a176ca8f6b4e07c1c49cd86c305af9144803
```

**Comment by GilbN** [comment]
Someone tested on 64bit rpi4b and it worked.  So not sure what happens on your system. 

Post the container logs and how you deployed the container.

**Comment by agneevX** [comment]
```sh
~> docker run -it --rm ghcr.io/gilbn/theme.park:testing
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by agneevX** [comment]
I think its because of:

https://github.com/GilbN/theme.park/blob/35023ce113883ee4303b19c90e46d8085ef00098/.github/workflows/docker-build.yml#L61

Can you please try just `linux/arm64` instead?

**Comment by GilbN** [comment]
I changed it, but it shouldnt matter because it already gets normalized. https://stackoverflow.com/a/70889505/15290341

**Comment by agneevX** [comment]
I have no idea what I'm doing wrong over here:

```sh
 ~ [1]> docker run -it --rm gilbn/theme.park:develop
Unable to find image 'gilbn/theme.park:develop' locally
develop: Pulling from gilbn/theme.park
...
Digest: sha256:c64289fc096d7501d7fca8b7f5d4d47a3b154d70197371b79bd0f25f130f773e
Status: Downloaded newer image for gilbn/theme.park:develop
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by agneevX** [comment]
This is what the image layers look like:

![Screenshot (249)](https://user-images.githubusercontent.com/19761269/161391088-8a75f433-26a3-46ed-a649-10a15b1a8666.png)

**Comment by avib333** [comment]
if you are doing something wrong i think i am doing the same thing... (pi 4 64)

**Comment by GilbN** [comment]
Image is broken. multi arch isn't working yet

**Comment by GilbN** [comment]
> if you are doing something wrong i think i am doing the same thing... (pi 4 64)

Can you try the :testing tag now? I think the manifest is working now

**Comment by agneevX** [comment]
Thanks @GilbN!

**Comment by avib333** [comment]
Works perfectly! Thanks alot!
