### ISSUE TITLE
[FR] Radarr 4K Instance seperating

### ISSUE THREAD

**Issue by reloxx13** [gilbN/theme.park#35]
Heya,

i have multiple Radarr instances installed, HD and 4K.
To better seperate those two, i added CSS to display a "4K" text next to the logo.

I would like to share this idea and my code. Hopefuly you can integrate it somehow, ie with an additional import file "4k.css"

```
/* 4K Text next to "Radarr" text on mobile */
.navbar > .container-fluid .navbar-brand .logo-text:after {
		content: "4K";
		font-weight: bold;
		font-size: 20px;
		position: relative;
		top: 2px;
		margin-left: 10px;
	}

/* 4K Text under logo on desktop */
@media (min-width: 768px) {
	.navbar > .container-fluid .navbar-brand .logo-text:after {
		content: "";	
	}
	
	.navbar > .container-fluid .navbar-brand:after {
		content: "4K";
		font-weight: bold;
		font-size: 30px;
		position: relative;
		top: 6px;
	}
}
```

![grafik](https://user-images.githubusercontent.com/14855001/78431648-7e462980-7675-11ea-9a1c-6b4087204684.png)

![grafik](https://user-images.githubusercontent.com/14855001/78431867-8c944580-7675-11ea-8482-80e780662299.png)

![grafik](https://user-images.githubusercontent.com/14855001/78432077-9ae26180-7675-11ea-81d7-859a1878c4fb.png)

**Comment by reloxx13** [comment]
PS:
i also made the logo smaller a few weeks ago, forgot that.
```
/* Smaller logo */
.xnavbar > .container-fluid .navbar-brand img {
	max-height: 70px;
}
```

Thats how it looks with the orginal logo size:
![grafik](https://user-images.githubusercontent.com/14855001/78435232-8f436a80-7676-11ea-980f-796d9ab367af.png)

**Comment by gilbN** [comment]
Nice idea! 
Added this now https://github.com/gilbN/theme.park/tree/master/CSS/addons/radarr

https://github.com/gilbN/theme.park/commit/ad81d103616e5fee71af53801dc4a766143cd26e

![image](https://user-images.githubusercontent.com/24592972/78450388-8fdfff00-767e-11ea-8a79-c92e6b32adaf.png)

![image](https://user-images.githubusercontent.com/24592972/78450395-9a01fd80-767e-11ea-8c4b-d438e14c2c32.png)

**Comment by reloxx13** [comment]
Very nice, thank you :)
