### ISSUE TITLE
[Feature request] Light theme support

### ISSUE THREAD

**Issue by reeseovine** [GilbN/theme.park#359]
I started making a Nord Bright theme to use during the daytime but it appears there are a lot of things hardcoded in various base styles that assume the theme is dark, such as setting some text to white or inverting the logo. I think it would be better to leave more up to the color themes but I'm not sure if it's entirely possible.

**Comment by GilbN** [comment]
I've tried to remove most of the hardcoded values. Can you try https://testing.theme-park.dev/ ?

**Comment by reeseovine** [comment]
I see the things you've fixed so far and they look good! The inverted logo I mentioned was in the AdGuard Home base theme.

There's also quite a lot of things with `background-color: rgba(0, 0, 0, .25);` for example, which looks a bit harsh with a light theme. My first thought was to instead use `color-mix` to darken the background color but it would break with background gradients.

**Comment by GilbN** [comment]
Yeah that will be a larger task. 

One could for example create new vars for transparency. 

```css
:root {
--transparency-10: rgba(0, 0, 0, .10)
--transparency-15: rgba(0, 0, 0, .15)
--transparency-25: rgba(0, 0, 0, .25)
...
}
```

And update all the base css files to use that. Then you would easily be able to override it.

**Comment by GilbN** [comment]
Ive added https://github.com/GilbN/theme.park/blob/develop/css/defaults/transparent.css.
All base files should be updated to use it on develop.

**Comment by GilbN** [comment]
This is merged to master now. Should solve any problems
