### ISSUE TITLE
[Radarr Aphrodite] Movie Index SortToken background not set

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#36]
On Aphrodite, when using poster mode and sorting by any token, an additional row of information is displayed below each poster. These do not have a themed background right now.

![image](https://user-images.githubusercontent.com/39887349/79076678-b0810800-7cc1-11ea-8b50-92afdf39d8c5.png)

**Comment by gilbN** [comment]
Fixed on https://github.com/gilbN/theme.park/commit/625a161b836b27308274d6afd9b76441f0e62b10
