### ISSUE TITLE
RuTorrent missing some css from modal windows

### ISSUE THREAD

**Issue by Zemoj** [GilbN/theme.park#364]
**Describe the bug**
RuTorrent missing css from modal windows "rule manager" and "rss manager"

**Theme Install Method** (Don't skip)
- Docker mod for linuxserver.io

**Application Info** (Don't skip)
- Version: 3.10
- Branch: linuxserver/rutorrent

**To Reproduce**
1. Install on Unraid OS using docker mod for linuxserver.io containers.

**Expected behavior**
CSS styling on the modal windows

**Screenshots**
https://i.imgur.com/npgMeOq.png
https://i.imgur.com/JFKkHQU.png

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.88

**Smartphone (If applicable) (please complete the following information):**
N/A

**Additional context**
Relevant CSS tags

```
#filterList
#filterProps
#filterPropsFieldSet legend
#filterPropsFieldSet label
#filterPropsFieldSet input

#ruleList
```

**Comment by GilbN** [comment]
I dont currently have it installed, wanna make a PR?

**Comment by Zemoj** [comment]
I'm not super familiar with this setup, I can try to take a look this weekend. Can I test changes by pointing my install to a fork?

**Comment by GilbN** [comment]
Simplest way to test changes is to use the stylus browser plugin https://docs.theme-park.dev/setup/#stylus-method
