### ISSUE TITLE
Guacamole icons obstruct text

### ISSUE THREAD

**Issue by typkrft** [GilbN/theme.park#367]
**Describe the bug**
Icons covering text in Guacamole.

**Theme Install Method** (Don't skip)
- Installed as a guacamole extension but this also occurs using stylus. 
- Side note: If it's worth it I could create a blurb about how to install via guacamole extension, not sure if theme-park would be interested in maintaining something like that, but its pretty easy and native for guacamole. For gaucamole it's potentially beneficial as the theme is seen by everyone using from deployment without any other setup. It could also be used to add custom logos.

**Application Info** (Don't skip)
- Version Current `latest` tag `bc853c0af816`
- Branch dracula
- Container guacamole

**To Reproduce**
Move Cursor over menu items - see picture 

**Expected behavior**
No icons, or better placed icons if possible. 

**Screenshots**
Certain parts of the picture are redacted ignore missing blocks
<img width="974" alt="Screen Shot 2022-04-25 at 1 30 26 AM" src="https://user-images.githubusercontent.com/12100960/165027016-46dbbf32-dec5-4b40-b98a-6c0dfe08e9f2.png">

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**
 - Device: M1 Max Macbook Pro
 - OS: 12.1 (21C52)
 - Browser Firefox
 - Version 100.0b9 (64-bit)

**Additional context**
NA

**Comment by GilbN** [comment]
Pushed a fix on develop.theme-park.dev.

And yeah we can add some extra instructions to https://docs.theme-park.dev/themes/guacamole/ 👍

**Comment by typkrft** [comment]
Great I'll write something up this weekend. Unfortunately the issue still persists. It's improved however in the sense that when hovering over home the icon no longer shows up. I should have recorded a video initially to better show the scope sorry about that. 

https://user-images.githubusercontent.com/12100960/165157091-83f2c8e8-ee94-4b9b-a5f4-e48ff6bcdbae.mov

**Comment by typkrft** [comment]
Confirmed working, sorry didn't catch the develop URL!
