### ISSUE TITLE
[Guacamole] Side Bar background not always displayed

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#37]
When connected (RDP), the side bar background is not always displaying a proper background. Sometimes, bringing up the menu shows the background. Other times, it does not render. Hitting F12 will force the background to render, but not sure if this can be easily fixed so that it does not create the below quirk

![image](https://user-images.githubusercontent.com/39887349/79076730-0e155480-7cc2-11ea-99ee-6af15623d5fb.png)

**Comment by gilbN** [comment]
Maybe this will fix it. Not sure. Let me know if it happens again. https://github.com/gilbN/theme.park/commit/2a6e4300c76a73c42a577d5c03b094ee5172a837

**Comment by rg9400** [comment]
Unfortunately, the commit did not fix it. The background still renders only occasionally, but now, when it does not, the whole side bar becomes transparent. If it can't be fixed, the prior version was still preferable 

![image](https://user-images.githubusercontent.com/39887349/79077648-c1814780-7cc8-11ea-973c-01aa2207aaf2.png)
