### ISSUE TITLE
SABnzbd DARK Theme issue

### ISSUE THREAD

**Issue by cyb3rgh05t** [GilbN/theme.park#374]
Hi :)

using stylus to have different themes for some app, i noticed that using the dark theme on sabnzbd the theme has a little color fault on the download bar 

![image](https://user-images.githubusercontent.com/5200101/167290253-b9c28dc3-74ee-41fa-9e8b-af0efb947157.png)

could this be fixed?

**Comment by GilbN** [comment]
Yes. It must be set to Glitter light https://docs.theme-park.dev/themes/sabnzbd/#setup
