### ISSUE TITLE
New Portainer update breaks theme

### ISSUE THREAD

**Issue by jpdsc** [GilbN/theme.park#376]
Hi there!

Portainer updated this morning and broke a bit of the theme on the home page: /#!/home
See below screenshot.

![image](https://user-images.githubusercontent.com/7014736/167599447-6c3a93df-d80c-4e37-8643-ece6333868a2.png)

I went through the rest of Portainer and didn't find other sections where the theme was broken.

**Comment by GilbN** [comment]
Version?

**Comment by jpdsc** [comment]
> Version?

2.13.1 from the official docker image: https://hub.docker.com/r/portainer/portainer

**Comment by GilbN** [comment]
try develop.theme-park.dev now

**Comment by jpdsc** [comment]
> develop.theme-park.dev

Tested and working as intended! Thanks!
