### ISSUE TITLE
qBittorrent Themes Not Working

### ISSUE THREAD

**Issue by Droppisalt** [GilbN/theme.park#380]
**Describe the bug**
Added the following environment vars:

- DOCKER_MODS=ghcr.io/gilbn/theme.park:qBittorrent
- TP_THEME=plex

and these custom HTTP headers:
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline' theme-park.dev raw.githubusercontent.com use.fontawesome.com; img-src 'self' theme-park.dev raw.githubusercontent.com data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self'; font-src use.fontawesome.com;

**Theme Install Method** (Don't skip)
- Docker compose

**Application Info** (Don't skip)
- qBit v4.3.8
- qBit Docker Image: markusmcnugen/qbittorrentvpn:latest

**To Reproduce**
Add env vars to docker compose of qBit
Add custom HTTP headers to qBit settings
Recreate qBit docker container

**Expected behavior**
Theme should change to Plex but regular qBit theme stays

**Screenshots**
![image](https://user-images.githubusercontent.com/67336980/168818106-52784d2c-3fec-443e-90d4-e61ae1f76283.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Linux/Docker
 - Browser: Chrome, Brave, Firefox and Edge

**Comment by GilbN** [comment]
It's `ghcr.io/gilbn/theme.park:qbittorrent` not `ghcr.io/gilbn/theme.park:qBittorrent`

**Comment by GilbN** [comment]
Check your logs

**Comment by GilbN** [comment]
Also docker-mods only support linuxserver.io images not markusmcnugen/qbittorrentvpn!

**Comment by Droppisalt** [comment]
> Also docker-mods only support linuxserver.io images not markusmcnugen/qbittorrentvpn!

Ah! Forgot about that. My bad
