### ISSUE TITLE
Jackett theme not works

### ISSUE THREAD

**Issue by ScreNN** [GilbN/theme.park#384]
**Describe the bug**
Jackett DOCKER_MODS theme stopped working. Worked a week ago
Plex, Radarr and other, work

**Theme Install Method** (Don't skip)
- Docker run / Compose Config

**Application Info** (Don't skip)
- Jackett v0.20.1131

**Screenshots**
[https://i.imgur.com/mxNiH5o.png](https://i.imgur.com/mxNiH5o.png)
[https://i.imgur.com/u38Qw95.png](https://i.imgur.com/u38Qw95.png)

**Comment by GilbN** [comment]
Tested OK on v0.20.1144

**Comment by GilbN** [comment]
Share you container logs.

**Comment by ScreNN** [comment]
> 

[https://pastebin.com/C0RzatJi](https://pastebin.com/C0RzatJi)

**Comment by ScreNN** [comment]
> Share you container logs.

[https://pastebin.com/C0RzatJi](https://pastebin.com/C0RzatJi)

**Comment by GilbN** [comment]
You added the envs under `labels:` add them under `environment:`

**Comment by ScreNN** [comment]
> You added the envs under `labels:` add them under `environment:`

Ohhhh... Sorry. Ty :)
