### ISSUE TITLE
[Radarr Aphrodite/Sonarr] Manual Import path text not themed

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#39]
See below, found when manually importing a movie/show, having a file selected, and then selecting episodes/movie against that file. Found in both Radarr Aphrodite and Sonarr

![image](https://user-images.githubusercontent.com/39887349/79366719-4c08b780-7f12-11ea-98b6-e36f24bac2ba.png)

**Comment by gilbN** [comment]
Keep em coming :)
