### ISSUE TITLE
Authelia and Nginx Proxy Manager

### ISSUE THREAD

**Issue by ItsRainingHP** [GilbN/theme.park#391]
Hello, I am not sure if its a bug or if I am doing something wrong. There  is not support category. I cannot get any themes to work that utilize Authelia. I noticed one other post about Authelia but it looks like the Docker method and did not work for me. Help is appreciated!

**Theme Install Method** (Don't skip)
- Webserver subfilter Config

**Application Info** (Don't skip)
- Version
Using Nginx
- Branch
Using Nginx
- Container
Using Nginx
- Logs
NET::ERR_CERT_AUTHORITY_INVALID

**To Reproduce**
1. Add Authelia authentication code to advanced tab Custom Nginx Config
2. Add in Nginx Proxy Manager code to custom location

**Expected behavior**
Use the theme css

**Screenshots**
![image](https://user-images.githubusercontent.com/79205731/176064343-e678bc07-37f6-4bb8-8ac1-8ed23d835c97.png)
![image](https://user-images.githubusercontent.com/79205731/176064410-2c672037-98e4-42f3-bccf-62e67fafd894.png)
Authelia Nginx Custom Config: https://pastebin.com/6Ukf88nH

**Desktop (If applicable) (please complete the following information):**
 - OS: Unraid 6.9.2 for dockers, Windows 11 (up-to-date) for loading website
 - Browser: Chrome
 - Version 102.0.5005.115

I am likely doing something wrong but it would be so great to have these themes working for my Authelia locked sites.

**Comment by GilbN** [comment]
If you are using linuxserver containers, you should use DOCKER_MODS https://docs.theme-park.dev/setup/

If not then try and add authelia and the subfilter parts under Advanced. I dont use NPM though. But there are some people in the discord that have made it work

 ![](https://cdn.discordapp.com/attachments/591378792845541376/922452671850508338/Screenshot_20211220-123703__01.jpg)

**Comment by ItsRainingHP** [comment]
I see thank you for the reply. I will attempt the Docker Mods method and join discord if it doesn't work.
