### ISSUE TITLE
[Bug] VueTorrent modal panel and button change in Hotio qBittorrent 4.4.3.1

### ISSUE THREAD

**Issue by Codelica** [GilbN/theme.park#399]
**Describe the bug**
There appears to be a style change/bug in the VueTorrent theme, at least in the latest version (4.4.3.1) from Hotio.  The modal panels (settings, double click info on torrent, etc) are all light grey and the top right control buttons (save, close) have changed).  Using "organizr" theme, but suspect it's a global change.

**Theme Install Method** (Don't skip)
Docker compose but not relevant, only Hotio qBittorrent/VueTorrent version changed.

**Application Info** (Don't skip)
- hotio/qbittorrent:release-4.4.3.1

**To Reproduce**
1. Setup Hotio qBittorrent per https://hotio.dev/containers/qbittorrent/
2. Configure with Theme.park themes (I'm using "organizr")
3. Enable VueTorrent UI for qBittorrent
4. Refresh browser
5. Bring up settings panel or info panel for torrent (double click)

**Expected behavior**
Dark styled modal windows as previously with "organizr" theme.

**Screenshots**

<img width="1336" alt="vuetorrent" src="https://user-images.githubusercontent.com/386101/178515595-5c0bbf31-b42c-46c2-bd3b-eaa062dd6f3d.png">

Same on desktop or mobile.

**Comment by GilbN** [comment]
Should be fixed on develop

**Comment by Codelica** [comment]
Looks good..  thanks!
