### ISSUE TITLE
[Bug] qBittorrent Dialog text is left with unreadable colour. Aquamarine + other themes

### ISSUE THREAD

**Issue by SgtBreadStick** [GilbN/theme.park#403]
**Describe the bug**
Text on some dialog windows are unreadable on many themes because the text remains grey. Occurs with multiple themes but I'm using Aquamarine.

**Theme Install Method** (Don't skip)
- Ultraseedbox Installer Script

**Application Info** (Don't skip)
- qBittorrent 4.3.9

**To Reproduce**
One of things affected is 'Add Torrent Link'

**Expected behavior**
The text is easy should be white or lighter shade to make it easier to read.

**Screenshots**
[Screenshot](https://i.sgtbrdstk.xyz/wkljj4.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 11 x64 21H2
 - Browser: Microsoft Edge (Chromium) 64-bit
 - Version: 103.0.1264.71

**Comment by GilbN** [comment]
I'm not seeing this on that dialog box. Try and clear cache. 

![](https://selfhosted.app/f3c10/wEjoRUHO64.png/raw)

I'm using v4.4.3.1

**Comment by SgtBreadStick** [comment]
I've uninstalled the theme and instead now using it via Stylus and i've no longer got the issue, apologies for that.
