### ISSUE TITLE
Uptime Kuma + Nord theme (maybe others)

### ISSUE THREAD

**Issue by the-lazy-fox** [GilbN/theme.park#416]
**Describe the bug**
With the Nord theme on Uptime Kuma, there is a big arrow displayed in all text fields
![image](https://user-images.githubusercontent.com/35723598/186381194-83fd32d8-2459-4a11-8ade-a79a147a50ec.png)

**Theme Install Method** (Don't skip)
- TamperMonkey custom script, works fine for all other apps

**Application Info** (Don't skip)
- Version: 1.17.1
- Branch: latest
- Container:  louislam/uptime-kuma

**To Reproduce**
1. Go to Uptime Kuma app with Nord Theme

**Expected behavior**
This arrow shouldn't be there

**Screenshots**
With theme
![image](https://user-images.githubusercontent.com/35723598/186381405-bddf04a3-b9b3-4cbc-b42e-682c46094daf.png)
Without theme
![image](https://user-images.githubusercontent.com/35723598/186381506-debb85d7-7f20-465c-9746-30e27f74881a.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 103.0.2 (64-bit)

**Comment by GilbN** [comment]
Does the same happen with stylus?

**Comment by the-lazy-fox** [comment]
I made the test and yes it does @GilbN 
With light or dark activated on uptime kuma.

**Comment by GilbN** [comment]
I'm not seeing this issue with stylus. Using uptime version 1.17.1 
![](https://selfhosted.app/f3c10/YuMEZOYo83.png/raw)

**Comment by the-lazy-fox** [comment]
This is the css element in cause:
![image](https://user-images.githubusercontent.com/35723598/188263253-8f7a0882-b87c-40f1-926c-aee4c024eed5.png)
The arrow is the background-image.

**Comment by GilbN** [comment]
> This is the css element in cause: ![image](https://user-images.githubusercontent.com/35723598/188263253-8f7a0882-b87c-40f1-926c-aee4c024eed5.png) The arrow is the background-image.
> 

Try develop.theme-park.dev

**Comment by the-lazy-fox** [comment]
Yes it fixed it @GilbN !
Thank you!

**Comment by GilbN** [comment]
Great. Thanks for reporting.
