### ISSUE TITLE
Vaultwarden WebUI (=Bitwarden) : cannot works with SWAG install because of Content-Security-Policy (CSP)

### ISSUE THREAD

**Issue by MilesTEG1** [GilbN/theme.park#418]
**Describe the bug**
Theme installed with SWAG method with variables.
Works perfectly for other docker app I use with the swag reverse proxy like Calibre-Web, Adguard Home.
But for my Vaultwarden instance, it doesn't work at all.
I get Content-Security-Policy error in my navigator (see with development tools) : see screenshot.

Vaultwarden can be themes successfully with Stylus method (but this one isn't accessible with mobile browsers...).

**Theme Install Method** (Don't skip)
- Webserver subfilter Config
I add this in my location :
```nginx
        set $theme dracula;
        set $app bitwarden;
        include /config/nginx/theme-park.conf;
```

and the `theme-park.conf` : 
```nginx
# File to be included in each .conf
# See : https://docs.theme-park.dev/setup/

proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/$app/$theme.css">
</head>';
sub_filter_once on;
```

The server block for my vaultwarden.conf file :
```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name vault.*;

    include /config/nginx/ssl.conf;

    # THEME.PARK
    # add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' theme-park.dev;" always;

    client_max_body_size 128M;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;
    
    # GeoIP Blocking with Maxmind Docker-MOD
    include /config/nginx/maxmind-geoblock_and_LAN.conf;

    # Custom error pages
    include /config/nginx/error_pages.conf;
    
    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # THEME.PARK
        set $theme dracula;
        set $app bitwarden;
        include /config/nginx/theme-park.conf;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        # GeoIP Blocking with Maxmind Docker-MOD
        include /config/nginx/maxmind-geoblock_and_LAN.conf;
        
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.2.230;
        set $upstream_port 882;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
```

For AdGuard Home, or Calibre-Web, I used the exact same method.

In the documentation ( https://docs.theme-park.dev/themes/bitwarden/ ), it's said that :

> Due to Bitwarden's Content-Security-Policy header, it is necessary to adjust this policy to include the domain(s) to load stylesheets from. Open bwdata/config.yml and add the domain name(s) to the nginx_header_content_security_policy property in the style-src policy directive.

But, for Vaultwarden, there is not such a file as bwdata/config.yml.
I tried to use this : `add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' theme-park.dev;" always;` in my location, but it doesn't work too...

**Application Info** (Don't skip)
- Version : Vaultwarden 1.25.2, WebUI 2022.6.2
- Branch:  stable
- Container: Vaultwarden
- Logs
``` log
2022-08-28T17:48:50.456233431Z [2022-08-28 19:48:50.456][_][WARN] Request guard `AdminToken` is forwarding.
2022-08-28T17:48:50.608622627Z [2022-08-28 19:48:50.608][vaultwarden::api::web][ERROR] Static file not found: bootstrap.css.map
2022-08-28T17:48:58.675453775Z [2022-08-28 19:48:58.675][vaultwarden::api::web][ERROR] Static file not found: bootstrap.css.map
2022-08-28T17:49:03.397408853Z [2022-08-28 19:49:03.397][vaultwarden::api::web][ERROR] Static file not found: bootstrap.css.map
```
Is there a way to have the theme working with Vaultwarden and the SWAG variable install method ?

**To Reproduce**
1. Install vaultwarden
2. Install SWAG, and configure a reverse proxy entrie
3. Use the variable method
4. See the choosed theme not applied

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29298312/187087398-53f3b9b8-aec2-4297-b7e7-9fe857336045.png)
![image](https://user-images.githubusercontent.com/29298312/187093189-aee7eb80-7798-4259-8089-b147c431caae.png)

**Additional context**
--

**Comment by GilbN** [comment]
You can add 
```nginx
proxy_hide_header "x-webkit-csp";
proxy_hide_header "content-security-policy";
proxy_hide_header "X-Frame-Options";
```

To remove the header

**Comment by MilesTEG1** [comment]
I can try this :)
But will not this affect the global security of Vaultwarden ?

**Comment by GilbN** [comment]
That's up to you. 

You can also get around the csp rule by self hosting the CSS files in the same domain as vault.domain.com

**Comment by MilesTEG1** [comment]
@GilbN You think I will not get the error if I use my domain ? (theme-park.mydomain.tld) 
I can give a try 😄

**Comment by GilbN** [comment]
If the files are hostd on the same domain as vault.domain.com then no

**Comment by MilesTEG1** [comment]
Ok, as I followed your docs about selfhosting, I've got a domain for theme-park :D ( https://docs.theme-park.dev/setup/#selfhosting )
I'll try this when I can ;) and get back here
Thanks.

**Comment by GilbN** [comment]
Just remember the files need to be accessible on the same domain as vaultwarden. themes.domain.com won't work, needs to be the exact same e.g vault.domam.com/themepark

**Comment by GilbN** [comment]
Another workaround is to remove the header and replace it with this. 

```nginx
proxy_hide_header "x-webkit-csp";
proxy_hide_header "content-security-policy";
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' develop.theme-park.dev theme-park.dev; img-src 'self' data: https://haveibeenpwned.com/ https://www.gravatar.com ; child-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-src 'self' https://*.duosecurity.com https://*.duofederal.com; connect-src 'self' https://api.pwnedpasswords.com/range/ https://2fa.directory/api/ https://app.simplelogin.io/api/ https://app.anonaddy.com/api/ https://relay.firefox.com/api/; object-src 'self' blob:; frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh moz-extension://*" ;
```

The CSP policy was extracted from https://securityheaders.com/

![](https://selfhosted.app/f3c10/JijixoNo50.png/raw)

**Comment by MilesTEG1** [comment]
> Just remember the files need to be accessible on the same domain as vaultwarden. themes.domain.com won't work, needs to be the exact same e.g vault.domam.com/themepark

I'm not sure how to do this with Nginx...

And for your last message, I'm too worry to change something about security for my vault, so I think I'll abandon the idea to theme with nginx... It's not too problematic as I nealy never use the web interface... I prefer using Bitwarden windows/macOS app, or iOS app...

Thanks for the help you gave me 🙇🏻

**Comment by GilbN** [comment]
Added Vaultwarden docs https://docs.theme-park.dev/themes/bitwarden/#vaultwarden

**Comment by MilesTEG1** [comment]
> Added Vaultwarden docs https://docs.theme-park.dev/themes/bitwarden/#vaultwarden

Hello,
I followed the part [#selfhosting](https://docs.theme-park.dev/themes/bitwarden/#selfhosting).
But I have selfhosted with the SWAG Docker-Mods, so in order to get my vaultwarden instance themed with dracula theme, I add to change this:
```nginx
location ^~ /themepark/ {
        set $upstream_app theme-park;
        set $upstream_port 443;
        set $upstream_proto https;
        proxy_set_header Host $host;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
```
to this:
```nginx
    location /themepark/ {
        alias /config/www/themepark/;
        sub_filter_types *;
        sub_filter 'url("/css/' 'url("/themepark/css/';
        sub_filter_once off;
        try_files $uri $uri/ /index.html;
    }
```
And now, My vault is themed 😄 and with outside my LAN too 😀 

I try to restriced the access to `my-vault.my-domaine.tld/themepark` subfolder to outside my LAN access, but If I do this, outside access are no more themed :sweat_smile:
Do you think it's possible to do that ?

**Comment by MilesTEG1** [comment]
@GilbN 
And there is an error in the docs subdomain-example:
a `;` is missing for this line:
```nginx
        set $tp_domain vaultwarden.domain.com/themepark # You can also do: $scheme://$host/themepark
```
It should be :
```nginx
        # You can also do: $scheme://$host/themepark
        set $tp_domain vaultwarden.domain.com/themepark;
```

**Comment by GilbN** [comment]
> I try to restriced the access to `my-vault.my-domaine.tld/themepark` subfolder to outside my LAN access, but If I do this, outside access are no more themed :sweat_smile:
> 
> Do you think it's possible to do that ?
> 

No? Think about it...

You want to restrict external access to /themepark but be able to access it externally..
Makes no sense.

**Comment by MilesTEG1** [comment]
> > I try to restriced the access to `my-vault.my-domaine.tld/themepark` subfolder to outside my LAN access, but If I do this, outside access are no more themed 😅
> > Do you think it's possible to do that ?
> 
> No? Think about it...
> 
> You want to restrict external access to /themepark but be able to access it externally.. Makes no sense.

That's what I was thinking... 
But I hoped that even when I access outside my LAN, the request would be seen as internal not external...
Thanks for the heads up.

**Comment by GilbN** [comment]
You could look into just allowing access to specific file types like CSS if you dont want the themepark page to load. 
Or just remove `try_files $uri $uri/ /index.html;`

**Comment by MilesTEG1** [comment]
Hello,
@GilbN I found a way to block the access to themepark subfolder :) It took me severals days to understand how nginx works, and it's not perfect on my side 😄 
I only authorise the access to the CSS and images files.
Here what I added in my vaultwarden.subdomain.conf file, for someone with the same need as me :
```nginx
    location ~* themepark/css/.*/.*\.(png|gif|ico|jpg|jpeg|css)$ {
        alias /config/www/;
        try_files $uri $uri/ /index.html;
    }
    location = /themepark/ {
        return 301 $scheme://$http_host/themepark;
    }
    location = /themepark {
        # return 302  $scheme://$http_host/themepark/;
        root /config/www/default;
        try_files $uri /404.html;
    }
```
It may not be very nice, and can probably be improved, but it works : my vaultwarden instance is themed, so CSS files are accessible, but myvault.ndd.tld/themepark is not working and return a custom 404 error file.

**Comment by GilbN** [comment]
Nice, since its just CSS files you can probably do `themepark/css/.*/.*\.css$`

**Comment by MilesTEG1** [comment]
> Nice, since its just CSS files you can probably do `themepark/css/.*/.*\.css$`

Ho I copy/paste too quickly, I just wanted to add png file because I see some png (or jpg) in some d’idées in the css directory.
You confirm me that there is only css file loaded with all versions of your theme ?

**Comment by GilbN** [comment]
AS far as I remember bitwarden doesnt use anything other than .css files. But you can take a look at the source.

**Comment by MilesTEG1** [comment]
> AS far as I remember bitwarden theme doesnt use anything other than .css files. But you can take a look at the source.

It seems that you are right, no image file is included. I just made the modification ;)
Thanks.

**Comment by MilesTEG1** [comment]
Hello @GilbN 
I don't know why and when, but the method I used to get my Vaultwarden instance themed isn't working anymore...
I try to check if something changed, but no...
Here what erroe message I got in dev console (on MS Edge) :
![image](https://user-images.githubusercontent.com/29298312/204091024-aa538fbb-0645-4674-9fbf-b23105bc76c3.png)

I comment my location about themepark in the vaultwarden conf file, and add instead the headers:
```nginx
    # THEME.PARK
    proxy_hide_header "content-security-policy";
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' themepark.my-domaine.tld develop.theme-park.dev theme-park.dev; img-src 'self' data: https://haveibeenpwned.com/ https://www.gravatar.com ; child-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-src 'self' https://*.duosecurity.com https://*.duofederal.com; connect-src 'self' https://api.pwnedpasswords.com/range/ https://2fa.directory/api/ https://app.simplelogin.io/api/ https://app.anonaddy.com/api/ https://relay.firefox.com/api/; object-src 'self' blob:; frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh moz-extension://*" ;
```
ANd it works again.

Maybe the problem is with SWAG, and it's constant changes...
