### ISSUE TITLE
emby nord theme, transparent buttons under Movies/TV shows

### ISSUE THREAD

**Issue by rj-d2** [GilbN/theme.park#419]
**Describe the bug**
emby nord theme, transparent buttons under movies/tv shows, not readable

**Theme Install Method** (Don't skip)
- Docker Compose Config

      - DOCKER_MODS=ghcr.io/gilbn/theme.park:emby
      - TP_THEME=nord

**Application Info** (Don't skip)
- Emby Version: 4.7.6.0
- Branch: latest
- Container: ghcr.io/linuxserver/emby 

**To Reproduce**
select light theme for docker mod, with nord theme buttons under movies/tv shows are transparent and not readable

**Expected behavior**
readable buttons

**Screenshots**

![nord](https://user-images.githubusercontent.com/20203399/187265890-141e134b-3e68-41de-84ed-4ca49abece95.png)
![nord1](https://user-images.githubusercontent.com/20203399/187265894-7695a0bf-1504-4918-9f03-f56384e12b86.png)

**Comment by GilbN** [comment]
try `-e TP_DOMAIN=develop.theme-park.dev`
