### ISSUE TITLE
[NEW ADDON REQUEST] Sonarr Text Logo with 4K

### ISSUE THREAD

**Issue by cyb3rgh05t** [GilbN/theme.park#426]
hi,

want to ask if there is a possibility to add a 4k logo to the Sonarr Text Logo?

thanks

**Comment by GilbN** [comment]
Perhaps @neoestremi wants to add one.

**Comment by neoestremi** [comment]
#427 ;)

**Comment by GilbN** [comment]
@cyb3rgh05t available on develop.theme-park.dev

**Comment by cyb3rgh05t** [comment]
thank you
