### ISSUE TITLE
[Suggestion] Dark headers for space-gray theme (Tautulli, NZBGet, LazyLibrarian)

### ISSUE THREAD

**Issue by rg9400** [GilbN/theme.park#43]
This is not a bug, entirely a suggestion that is open to your personal preference. If you disagree, feel free to close.

I noticed that the space-gray theme has a dark header for certain apps like the Arrs and NZBHydra. The header gives a good contrast and looks very clean in my opinion. Other apps are missing this distinction, so the header sort of blends into the body of the page. Both from a consistency as well as a theme perspective, I think adding similar black headers to apps that are missing them could enhance the theme. 

Apps with dark headers already
![image](https://user-images.githubusercontent.com/39887349/79695848-b2f1dd80-823e-11ea-944e-35938d6d4c7c.png)
![image](https://user-images.githubusercontent.com/39887349/79695854-bdac7280-823e-11ea-8ba1-fa344e7f28f9.png)
![image](https://user-images.githubusercontent.com/39887349/79696000-a7eb7d00-823f-11ea-8792-ecdf6e0e28c7.png)
![image](https://user-images.githubusercontent.com/39887349/79696028-c18cc480-823f-11ea-88cb-3acd4a248e0d.png)

Apps missing black headers
![image](https://user-images.githubusercontent.com/39887349/79695868-ca30cb00-823e-11ea-98d9-0a391b5d67f8.png)
![image](https://user-images.githubusercontent.com/39887349/79695874-d4eb6000-823e-11ea-8a3f-96686ed054c7.png)
![image](https://user-images.githubusercontent.com/39887349/79695931-37446080-823f-11ea-8385-54044d1d6b53.png)

Example of Tautulli with black header
![image](https://user-images.githubusercontent.com/39887349/79695955-5f33c400-823f-11ea-9dce-f87415af2fe8.png)

**Comment by gilbN** [comment]
I'll answer you here as well.. Heh

Yeah, there's a bit of inconsistency between themes. It looks better with dark header standalone. But when using org it looks better without lol.. 

https://selfhosted.app/f3c10/SicopEdu01.png

But yeah I might add headers to all . Theres a lot of different inconsistencies I havent really made a cheat sheet to use when making the themes. To much work lol
