### ISSUE TITLE
Themes not working in some browser all of the sudden

### ISSUE THREAD

**Issue by bbaraniec** [GilbN/theme.park#431]
I don't know what happened but themes are not being loaded for any browser (edge, chrome, firefox) for Sabnzbd and Radarr. Sonarr works. Funny thing, that they do still work on mobile browser (edge) on my iPhone and on Safari.
I'm really lost, what's going on.

**Comment by GilbN** [comment]
Check the browser console for errors

**Comment by bbaraniec** [comment]
Mixed Content: The page at 'redected was loaded over HTTPS, but requested an insecure stylesheet 'http://theme-park.dev/css/base/sabnzbd/sabnzbd-base.css'. This request has been blocked; the content must be served over HTTPS.

Docker settings are:
![image](https://user-images.githubusercontent.com/4579438/188481807-6cd34d08-c67d-4891-aa75-bb0f884bba28.png)
