### ISSUE TITLE
Overseer elements are now transparent

### ISSUE THREAD

**Issue by VanCityGuy** [GilbN/theme.park#435]
**Describe the bug**
It seems like a recent update to the Overseer may have broken the base css, causing many elements on the page to transparent, including the add options and hovering tool tips.

**Theme Install Method** (Don't skip)
NGINX Variable

**Application Info** (Don't skip)
- Version : 7404d68143e830df73b9d2779a6d7ea65bc9fd4f
- Branch : Develop
- Linuxserver

**To Reproduce**
1. Apply any theme to Overseer
2. Check the elements on the page.

**Expected behavior**
Would expect there to be no transparent elements on Overseer

**Screenshots**

![request](https://user-images.githubusercontent.com/20589808/191093354-cba48e07-57c3-453f-9885-bebd3a8a0173.PNG)
Here we see since the bottom half of the box and drop down menus all transparent. I am currently using the Nord theme.

![tool tip](https://user-images.githubusercontent.com/20589808/191093934-54c3674a-57cb-493d-a98d-263f826e5395.png)
Here we see a hovering tool tip exhibiting the same behaviour

**Desktop (If applicable) (please complete the following information):**
 - OS: Unraid
 - Chrome

**Comment by BaukeZwart** [comment]
Same issue here, theme applied in NPM on Syno.

**Comment by GilbN** [comment]
Test develop

**Comment by BaukeZwart** [comment]
Development branch fixed the issue.
