### ISSUE TITLE
[CalibreWeb] Background not being set on Index page

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#44]
Thanks for all the hard work! Whenever you want me to stop, let me know :smile:

For Calibre-Web (using CaliBlur as a base), the background does not seem to be set on the index pages (i.e. Recently Added or any of the other tabs clicked on from the side menu). Also does not seem to work when searching, the about page, settings page, or admin page.

However, it does work when navigating to a specific book page

![image](https://user-images.githubusercontent.com/39887349/79700782-e8f28a00-825d-11ea-91e2-e3c3f544b92c.png)

![image](https://user-images.githubusercontent.com/39887349/79700789-fdcf1d80-825d-11ea-8865-6b6e42779fb7.png)

Also, this is probably an issue in CaliBlur itself, but just FYI, some of the newer pages have some UI quirks

![image](https://user-images.githubusercontent.com/39887349/79700829-3ec73200-825e-11ea-9d39-6393847b5c35.png)
![image](https://user-images.githubusercontent.com/39887349/79700839-51416b80-825e-11ea-82b4-f968ca2cc3ca.png)
![image](https://user-images.githubusercontent.com/39887349/79700867-5b636a00-825e-11ea-8ae2-6d1c5c581953.png)

**Comment by gilbN** [comment]
Thanks! I'll check it out 👍🏻

**Comment by gilbN** [comment]
Still an issue?

**Comment by rg9400** [comment]
The background is no longer an issue. The rest of the UI quirks still are, but I think those should be fixed in CaliBlur, not here.
