### ISSUE TITLE
Uptime-Kuma : overlap in credentials login fields page and 2FA field

### ISSUE THREAD

**Issue by MilesTEG1** [GilbN/theme.park#440]
**Describe the bug**
In the login screen of Uptime-Kuma, the default Username overlap the text's filed "Nom d'utilisateur".
Same for the field password.
Same again for the 2FA field.

**Theme Install Method** (Don't skip)
- Webserver subfilter Config : with NGINX (SWAG container)

**Application Info** (Don't skip)
- Version: 1.18.0
- Branch : main
- Container : Uptime-Kuma
- Logs :  X

**To Reproduce**
Set the theme to one of the option.
I tried Dark, Dracula.

**Expected behavior**
Texts not overlapping.

**Screenshots**
![image](https://user-images.githubusercontent.com/29298312/192532279-f5e3e2cf-c932-4d5b-9568-859cd9ab6b88.png)
![image](https://user-images.githubusercontent.com/29298312/192533576-c593f3a9-4acb-4270-9746-6f3d7ad4f643.png)

When I click in one, it's OK :
![image](https://user-images.githubusercontent.com/29298312/192532754-b1583900-e336-4bf1-8f43-04025f8ec75c.png)
Same after filling the credentials or 2FA field :
![image](https://user-images.githubusercontent.com/29298312/192532946-10779016-2396-412d-86ae-cf81744c5189.png)
![image](https://user-images.githubusercontent.com/29298312/192533912-2f5d303e-c8bc-420c-8689-38773a3683b0.png)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows10
 - Browser: Brave
 - Version: v1.43.93

**Comment by MilesTEG1** [comment]
@GilbN 
I just try with Stylus, and the same results happen.

**Comment by GilbN** [comment]
Test with a different browser.

**Comment by MilesTEG1** [comment]
> Test with a different browser.

It's the same with Vivaldi.
But with Ms Edge, it's working :

https://user-images.githubusercontent.com/29298312/193457265-c6b63cf1-7455-421f-9ef6-766db1ca446d.mp4

But Edge isn't my principal browser...

Can it be fixed for Brave ?

**Comment by GilbN** [comment]
It's an upstream issue.  The #floatingInput placeholder isn't translated on the login page.
A temp fix is to set the the language to English.

**Comment by GilbN** [comment]
Fixed on develop
