### ISSUE TITLE
Docker Mod Scripts No Longer Backwards Compatible With S6 v2

### ISSUE THREAD

**Issue by owine** [GilbN/theme.park#441]
**Describe the bug**
Docker Mod scripts are no longer backwards compatible with s6 v2. I am reporting this on Plex, but it would apply to others. I am  not sure if there is a good way to make the scripts dually compatible.

Note: This is when using the script files directly (hotio image, PMS official image) rather than the LSIO true mod method

**Theme Install Method** (Don't skip)
- Docker run / Compose Config
  - If using docker mods share your container logs..
```[cont-init.d] 98-themepark: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/98-themepark: No such file or directory
[cont-init.d] 98-themepark: exited 127.
```

**Application Info** (Don't skip)
- Version
- Branch `latest`
- Container `plexinc/pms-docker`
- Logs `(above)`

**To Reproduce**
1. Grab `98-themepark` script
2. Mount into container using image built on S6 v2
3. See error

**Expected behavior**
Expect mod to be applied successfully, but because the `#/command/with-contenv bash` path does not exist on S6 v2, the script fails to run successfully

**Screenshots**

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by GilbN** [comment]
Are you using the latest tag for hotio?

**Comment by owine** [comment]
> Are you using the latest tag for hotio?
> 
> 

I observed this on the official Plex image. 

Another user appeared to be experiencing it on a hotio qbittorrent version pinned to a version prior to the S6 v3 transition.

**Comment by GilbN** [comment]
I see. I only support Hotio and LSIO. Which uses V3. 

You should just use the LSIO container and make your life easier :)
You can replace the shebang with `#!/usr/bin/with-contenv bash`
