### ISSUE TITLE
[Grafana] Checkboxes not quite themed

### ISSUE THREAD

**Issue by Roxedus** [gilbN/theme.park#45]
I don't remember if the checkboxes were ever themed, however they look off now. 
![image](https://user-images.githubusercontent.com/7110194/79753088-a3919380-8315-11ea-8997-e1f1aacc9967.png)
If they were never meant to be themed, deleting `.gf-form-checkbox` is enough.

Leaving issue for discussion purposes.

**Comment by gilbN** [comment]
It's even more broken ov v7.0.0 hehe

**Comment by gilbN** [comment]
will look at it when v7 is released.
