### ISSUE TITLE
Sonarr base css for calendar missing new changes

### ISSUE THREAD

**Issue by scooterpsu** [GilbN/theme.park#450]
Commit https://github.com/GilbN/theme.park/commit/a56b789361118cd5977268eb53938e5a0dc0775b removed Calendar-Event class background entries from sonarr-base.css without any equivalent added -alt-calendar.css addon.

Should probably either add that to an addon or revert that base file.

**Comment by GilbN** [comment]
Sonarr had that built in

**Comment by scooterpsu** [comment]
Existing Sonarr elements didn't use your --calendar-downloaded, etc background color variables, and so removing those gives white backgrounds on dark themes (ie. Organizr).

Everything else in the commit added some catch for this, but sonarr-base only had lines removed and nothing added.
