### ISSUE TITLE
Sonarr Calendar page:  Unaired and 3 other categories are not showing correctly in dark theme

### ISSUE THREAD

**Issue by mastakebob** [GilbN/theme.park#451]
Using the theme.park with Sonarr via docker_mods (DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr).  A couple of weeks (months?) ago the Calendar page has been messed up with Unaired episodes showing bright vertical pinstripes.  See screengrab below.  This also seems to happen for 3 other calendar categories:  "unmonitored", "currently airing", and "aired but missing from disk".  Categories "downloading" and "downloaded" appear to work OK.  

Expected behavior:  Episodes in those categories are shown normally like they appear as Downloaded or Downloading.  

![Sonarr with Dark Theme Park](https://user-images.githubusercontent.com/47671816/200121775-7a197af5-a399-4e62-b9cb-b1c7986ad5c6.jpg)

**Comment by GilbN** [comment]
Disable colored impared mode
