### ISSUE TITLE
Radarr 4K Desktop Logo Incorrectly Sized

### ISSUE THREAD

**Issue by yammes08** [GilbN/theme.park#452]
**Describe the bug**
Rakarr 4k Logo is larger than the default Radarr logo

**Theme Install Method** (Don't skip)
- Webserver subfilter Config (nginx proxy manager) - using self-hosted docker for theme.park files

**Application Info** (Don't skip)
- Radarr Version 4.3.0.6671
- testing-e90c111 by [hotio]

**To Reproduce**
1. Create reverse proxy for Radarr 4k instance
2. Add subfilter to npm:

```
proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="http://local-ip:port/css/base/radarr/radarr-base.css">
<link rel="stylesheet" type="text/css" href="http://local-ip:port/css/addons/radarr/radarr-darker/radarr-darker.css">
<link rel="stylesheet" type="text/css" href="http://local-ip:port/css/addons/radarr/radarr-4k-logo/radarr-4k-logo.css">
</head>';
sub_filter_once on;
```
3. Save and visit Radarr 4k instance

**Expected behavior**
Flicking between Radarr instances 1 and 2, the logo would be the same size

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox

**Comment by GilbN** [comment]
Fixed on develop
