### ISSUE TITLE
Dracula on Gitea is too far from the official design

### ISSUE THREAD

**Issue by TheFrenchGhosty** [GilbN/theme.park#454]
**Describe the bug**

The theme park theme for Gitea use bright pink and bright green for text, while the official Dracula theme for GitHub only use those 2 colors for accent, it almost looks like Gitea theme try to avoid white text. 
The Gitea theme also use a "dark grey" that isn't used on the Github theme, which looks weird and out of place.

This make the Gitea theme really bad compared to the GitHub theme. 

**Screenshots**

Official theme for GitHub:

![image](https://user-images.githubusercontent.com/47571719/201427049-ac30e260-c59e-4ef0-bf65-d6d460f503d1.png)

Your theme for Gitea:

![image](https://user-images.githubusercontent.com/47571719/201427212-2d6f86bf-d7c2-4abe-a9a4-f98e883e2651.png)

**Comment by GilbN** [comment]
It's open source. Fork it and make your own theme-option. https://docs.theme-park.dev/custom/

**Comment by TheFrenchGhosty** [comment]
@GilbN I'm not interested in forking it... I'm just bringing the issue that the theme named "Dracula" doesn't respect the design of the Dracula theme.
