### ISSUE TITLE
rutorrent oddness

### ISSUE THREAD

**Issue by deathbybandaid** [GilbN/theme.park#461]
**Describe the bug**
See Screenshots, I'm not sure the correct words to describe

**Theme Install Method**
- Webserver subfilter Config
- nginx

**Application Info**
- v4.0-beta.3 is the latest, but the guide I followed is a git clone of master
- Master

**Expected behavior**

**Screenshots**
How it looks without subfilter versus with

![image](https://user-images.githubusercontent.com/18010545/205959830-260feb4d-4805-49f4-9508-95f2676b4ac4.png)![image](https://user-images.githubusercontent.com/18010545/205960020-9aa9b392-a3be-465c-88f0-897f7b437083.png)

**Comment by GilbN** [comment]
Hm, I don't use it, so it might be time to deprecate this theme.
