### ISSUE TITLE
Ombi: Dark CSS theme sidebar color too light

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#462]
**Describe the bug**
OMBI dark CSS theme sidebar color is too bright.

**Theme Install Method** (Don't skip)
- nginx subfilter:
  https://theme-park.dev/css/base/ombi/dark.css

**Application Info** (Don't skip)
Current releases of OMBI.

**Expected behavior**
Sidebar color is wrong...too light. Should be darker to match Themepark Dark sidebar color.

**Screenshots**
![Screenshot_20221209_205845_Samsung Internet](https://user-images.githubusercontent.com/811008/206830179-38f22f93-ee54-403d-9a6f-97560620e373.png)

**Comment by GilbN** [comment]
Not a bug, thats just how the variable `--modal-bg-color` colors looks for dark on the side menu. You are free to roll your own custom variant as its just css variables. Check the docs.
