### ISSUE TITLE
Sonarr No such file or directory

### ISSUE THREAD

**Issue by subsonicboom** [GilbN/theme.park#467]
**Describe the bug**
No Such file or directory while running Theme-park

**Theme Install Method** (Don't skip) 
ls.io & Docker_MODS

**Application Info** (Don't skip)
- Version - 1.13.3
- Branch - develop
- Container - appdata\theme-park
- Logs

**To Reproduce**
using binhex-sonarr
Docker_mods & 98-themepark-sonarr

**Screenshots**
Unraid Setup:
![image](https://user-images.githubusercontent.com/98620702/209448255-5a7a3345-b0a9-4e00-b3a2-145861152ca6.png)

Theme-park logs:
![image](https://user-images.githubusercontent.com/98620702/209448433-eae6feba-73ff-412e-a23d-8e5d3edc24c4.png)

shown in theme-park startup logs:

grep: /app/sonarr/bin/UI/index.html: No such file or directory
s6-rc: info: service init-mods-package-install successfully started
sed: /app/sonarr/bin/UI/index.html: No such file or directory
sed: /app/sonarr/bin/UI/index.html: No such file or directory
sed: /app/sonarr/bin/UI/login.html: No such file or directory
sed: /app/sonarr/bin/UI/login.html: No such file or directory

**Desktop (If applicable) (please complete the following information):**
 - OS: [Unraid]
 - Browser [firefox]
 - Version [108.0.1]

**Additional context**
Running binhex-sonarr in unraid

**Comment by GilbN** [comment]
You need to use https://github.com/linuxserver/docker-sonarr
Docker mods is only for lsio containers. Not Binhex.

**Comment by subsonicboom** [comment]
Thanks for the help although, I switched over to Isio sonarr container as advised, and having the same exact problem.

**Comment by GilbN** [comment]
Tested here, and it works so something is messed up with your setup. Also there would be 10s of issues created if it was broken. So try and recreate and make sure everything is up to date.

**Comment by subsonicboom** [comment]
Thanks again, I got it taken care of.
