### ISSUE TITLE
ruTorrent moved to v4 - rework needed

### ISSUE THREAD

**Issue by the-lazy-fox** [GilbN/theme.park#469]
**Describe the bug**
ruTorrent moved to v4 which creates few bugs

**Theme Install Method** (Don't skip)
Using Docker mods, it works well, just related to the upgrade

**Application Info** (Don't skip)
- Version: 4
- Branch: latest
- Container: crazymax

**Screenshots**
![image](https://user-images.githubusercontent.com/35723598/212359694-a78d82d4-2cdd-4645-97b5-2c80a86a9bf3.png)

Thank you!

**Comment by SmokeyBR** [comment]
issue seems to be this line https://github.com/GilbN/theme.park/blob/f77c17699212b4291b76317f27d077db34af6dc5/css/base/rutorrent/rutorrent-base.css#L454

if overwritten with `background-image: none;` seems fine

**Comment by GilbN** [comment]
You can try and implement the same changes here and see if that works 
https://github.com/themightykitten/ruTorrent-MaterialDesign/pull/6/files#diff-9cf5e968d7620a70c214f8015cd130d2dfc9f6c31c3a12dd2f3c4ddb434b27ec

**Comment by the-lazy-fox** [comment]
https://github.com/GilbN/theme.park/pull/471

**Comment by GilbN** [comment]
I would rather you made the same changes as this: https://github.com/themightykitten/ruTorrent-MaterialDesign/pull/6/files#diff-9cf5e968d7620a70c214f8015cd130d2dfc9f6c31c3a12dd2f3c4ddb434b27ec and see how that looks.

**Comment by the-lazy-fox** [comment]
Sorry I don't have time right now to go that deep into it, the fixes works for me currently.

**Comment by GilbN** [comment]
Fixed with https://github.com/GilbN/theme.park/commit/0b9459a070ea9fe809178bf73b4442c5ebb90562
