### ISSUE TITLE
Publishing fork to github.io shows no background in unraid login

### ISSUE THREAD

**Issue by Carpe-Diem-Postero** [GilbN/theme.park#472]
**Describe the bug**
After forking the theme.park repository, publishing it to github.io, and then switching domain variable to user.github.io, the script modifies UnRAID login screen partially, because it shows the custom login box, but no background is shown.

**Theme Install Method** (Don't skip)
- install user script plugin through app tab
- Create .sh script as instructed in the documentation

**Application Info** (Don't skip)
- UnRAID OS
- 6.11.5
- Stable

**To Reproduce**
- Fork repository
- Publish to github pages
- install user script plugin
- Create .sh script
- Modify it to select either alien or fallout theme
- Change DOMAIN="theme-park.dev" to DOMAIN="user.github.io"
- run script
- Login screen shows modified login box, but no background

If another wallpaper is selected, same behavior happens.
If DOMAIN is switch back to default (theme-park.dev) then the login screen fully works, so it is related to path in user.github.io domain usage.

**Script output**
```
Script location: /tmp/user.scripts/tmpScripts/Login screen/script
Note that closing this window will abort the execution of this script
Variables set:
TYPE = fallout
THEME = dirty_terminal2.css
DOMAIN = carpe-diem-postero.github.io
SCHEME = https
ADD_JS = false
JS = please_stand_by.js
DISABLE_THEME = false

NOTE: Change the LOGIN_PAGE variable to /usr/local/emhttp/login.php if you are on a version older than 6.10
Unraid version: 6.11.2
Switching to github.io URL style
grep: warning: stray \ before /
Adding stylesheet
Stylesheet set to dirty_terminal2.css
```

**what I tried**
I tried removing the extra \ in line 57:

From
DOMAIN="${DOMAIN}\\/theme.park"

to
DOMAIN="${DOMAIN}/theme.park"

This solves the "grep: warning: stray \ before /" error in script output, but problem with background persists

**Expected behavior**
Login screen should be fully functional

**Screenshots**

![image](https://user-images.githubusercontent.com/47411669/213886049-376f560d-4247-4fb5-8ce6-a209b238c2c0.png)

**Comment by GilbN** [comment]
Check the browser console for errors.

**Comment by Carpe-Diem-Postero** [comment]
> Check the browser console for errors.

![image](https://user-images.githubusercontent.com/47411669/213915131-37e69e39-9d7b-45e8-9e2c-9b03ccb86f3d.png)

As expected, there are some path errors with github.io GET commands.

![image](https://user-images.githubusercontent.com/47411669/213915575-fa635ea7-85b3-4185-af60-a2b70f9690dc.png)


Path used to grab some css and image is not passed correctly. Path used is:

https://carpe-diem-postero.github.io/css/addons/unraid/login-page/fallout/wallpaper/terminal2.jpg

When it should be:

https://carpe-diem-postero.github.io/theme.park/css/addons/unraid/login-page/fallout/wallpaper/terminal2.jpg

The login script contains (line 57):

```
# Use correct domain style
case ${DOMAIN} in
  *"github.io"*)
  echo "Switching to github.io URL style"
    DOMAIN="${DOMAIN}\/theme.park"
    ;;
esac
```

It seems that the new relative path is used for some css components, but it is not correctly passed to others,

**Comment by Carpe-Diem-Postero** [comment]
Has anyone been able to confirm the issue?

**Comment by GilbN** [comment]
I'll try and do some testing this weekend

**Comment by danktankk** [comment]
Can confirm this is working with 6.11.5.  I recently updated from 6.10.3.  I simply copied the script into a test editor and compared it against my old one in notepad++ and the compare plugin.  There were obvious differences.  Once i pasted the new script in, it worked fine but did give an error as described for a leading slash.  Even with that error, my custom background and login loaded without any issue.  After correcting the error, It didn't complain anymore and still worked fine.  

I also removed the theme and reverted to the original login and then back again.  Works fine.

**Comment by Carpe-Diem-Postero** [comment]
> Can confirm this is working with 6.11.5.  I recently updated from 6.10.3.  I simply copied the script into a text editor and compared it against my old login script using notepad++ and the compare plugin.  There were obvious differences.  Once I pasted the new script in, it worked fine but did give an error as described for the leading slash `DOMAIN="${DOMAIN}\/theme.park"`.  Even with that error, my custom background and login loaded without any issue.  After correcting the error, It didn't complain anymore and still worked fine.  
> 
> I also reverted to the original login and then back again to be sure.  Works fine.

You got it working with github.io? How? Did you modified any code in your fork?

Can you provide the steps performed, and the script you used in 6.11.5 ?

Thanks!

**Comment by danktankk** [comment]
> > I also reverted to the original login and then back again to be sure.  Works fine.
> 
> You got it working with github.io? How? Did you modified any code in your fork?
> 
> Can you provide the steps performed, and the script you used in 6.11.5 ?
> 
> Thanks!

Like I said, I copied the provided script from github/theme.park - Here is the script I use and the only thing changed is at the top where I selected my theme.  Mine is custom and forked, but I kept the names the same for simplicity.  This should work for you as well unless you have something else getting in the way of it.  

https://0bin.net/paste/QD09FEwM#3KQRKaaNEV3EfReOqm9Ii7XtvpI4s-ldsfmSxKWNJQ+

Hope this helps.

PS This also has the correction for the leading slash so you dont need to look for it to fix.

**Comment by Carpe-Diem-Postero** [comment]
> > > I also reverted to the original login and then back again to be sure.  Works fine.
> > 
> > You got it working with github.io? How? Did you modified any code in your fork?
> > 
> > Can you provide the steps performed, and the script you used in 6.11.5 ?
> > 
> > Thanks!
> 
> Like I said, I copied the provided script from github/theme.park - Here is the script I use and the only thing changed is at the top where I selected my theme, etc...  Mine is custom and forked, but I kept the names the same for simplicity.  This should work for you as well unless you have something else getting in the way of it.  
> 
> [Link to script](https://0bin.net/paste/QD09FEwM#3KQRKaaNEV3EfReOqm9Ii7XtvpI4s-ldsfmSxKWNJQ+)
> 
> Hope this helps.
> 
> PS This also has the correction for the leading slash so you dont need to look for it to fix.
> 
> [EDIT]
> Now that I think about it, I believe i did make a few changes in my fork.  Let me poke around and see.  Ill check back in a bit.  Let me know if this works first.  Mine is using video for the background.

Yes, you did.

In fact, you just modified what I was about to try this week

You added https://theme.park/ to all conflicting URL, so those are imported from the base repository instead of your own fork.

This is default .css
![Screenshot_20230207-154506.png](https://user-images.githubusercontent.com/47411669/217278410-383ef516-3841-4f6d-b97b-2ba16a1f27a5.png)

And this is your forked .css
![image9_1.png](https://user-images.githubusercontent.com/47411669/217279024-067da73f-a4e1-4b9d-9424-13d28a371a68.png)

**Comment by danktankk** [comment]
it Ok cool.  Seems like forking the repo isn't really as straight forward as could be.  I do remember plugging away at it for a good bit to get it to work.  It's one reason why I just replaced things and kept the names the same also.

**Comment by danktankk** [comment]
> You added https://theme-park.dev/ to all conflicting URL, so those are imported from the base repository instead of your own fork.

This is what I managed to do for my custom login screen for unraid.  

[Login Screen](https://youtu.be/ZMVSHhYc3P4)

**Comment by GilbN** [comment]
I added `/theme.park/***` as a prefix on the import, and that worked on my alt account.

https://github.com/gilbnalt/theme.park/blob/master/css/addons/unraid/login-page/retro-terminal/green.css

So my tip is to use a custom domain for your github pages setup OR add that prefix to any imports on the unraid login page theme css files ([hallway.css](https://github.com/gilbnalt/theme.park/blob/master/css/addons/unraid/login-page/alien/hallway.css), [green.css](https://github.com/gilbnalt/theme.park/blob/master/css/addons/unraid/login-page/retro-terminal/green.css), [dirty_terminal.css](https://github.com/gilbnalt/theme.park/blob/master/css/addons/unraid/login-page/fallout/dirty_terminal.css) etc)
