### ISSUE TITLE
[Addon request] Sonarr V4 Alternative Calendar

### ISSUE THREAD

**Issue by trinsic** [GilbN/theme.park#477]
It seems like a few edits to the current Radarr Alt Calendar CSS can return good results for Sonarr as well. Then I found you had done it at one point in #444 but removed it. Can we see it return? It looks so clean.

![Screenshot 2023-03-02 122310](https://user-images.githubusercontent.com/4532152/222338635-799ee5cc-8277-464f-b64c-60c7f0ca5197.jpg)

**Comment by GilbN** [comment]
Sonarr has this built in.

**Comment by trinsic** [comment]
Ahh, well then that was much easier. Your addons and themes are excellent by the way.
