### ISSUE TITLE
NPM script unable to execute

### ISSUE THREAD

**Issue by instantdreams** [GilbN/theme.park#483]
**Describe the bug**
After installing the theme, the NPM container cannot run the script.

**Theme Install Method**
- Docker Compose file extract:
```
    volumes:
      - ${DIRECTORY_DATA}:/data
      - ${DIRECTORY_LETSENCRYPT}:/etc/letsencrypt
      - ${DIRECTORY_THEMEPARK}:/etc/cont-init.d/99-themepark
```
- .env file extract:
```
# Directory locations
DIRECTORY_DATA=/srv/nginx-proxy-manager/data
DIRECTORY_LETSENCRYPT=/srv/nginx-proxy-manager/letsencrypt
DIRECTORY_THEMEPARK=/srv/nginx-proxy-manager/themepark/98-themepark
```
- Directory content
```
$ ls -lha /srv/nginx-proxy-manager/themepark/
total 12K
drwxr-xr-x 2 idsvc idsvc 4.0K Mar 16 03:04 .
drwxr-xr-x 5 idsvc idsvc 4.0K Mar 16 03:04 ..
-rwxr-xr-x 1 idsvc idsvc 2.0K Mar 16 03:04 98-themepark
```
- File 98-themepark obtained from [repository](https://raw.githubusercontent.com/GilbN/theme.park/develop/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark)

**Application Info**
- Version: 2.9.20
- Branch: Latest
- Logs
```
npm-1_app  | [cont-init.d] 01_s6-secret-init.sh: executing...
npm-1_app  | [cont-init.d] 01_s6-secret-init.sh: exited 0.
npm-1_app  | [cont-init.d] 99-themepark: executing...
: No such file or directorynable to exec bash
npm-1_app  | [cont-init.d] 99-themepark: exited 127.
npm-1_app  |
npm-1_app  | !!!!!
npm-1_app  |  init-stage2 failed.
npm-1_app  | !!!!!
```

**To Reproduce**
1. nano .env
2. docker compose pull;docker compose up --detach
3. docker compose logs

**Expected behavior**
Script to execute

**Versions**
 - Docker version 23.0.0, build e92dd87
 - Docker Compose version v2.15.1
 - Linux 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

**Comment by GilbN** [comment]
Take a look at the hotio FAQ here: https://docs.theme-park.dev/setup/#hotio-faq

**Comment by instantdreams** [comment]
Thank you, that worked:
```
cd /srv/nginx-proxy-manager/themepark/
rm 98-themepark
wget https://raw.githubusercontent.com/GilbN/theme.park/master/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark
chmod +x 98-themepark
cd /srv/nginx-proxy-manager
docker compose pull
docker compose up --detach
```

Resulted in this:
![image](https://user-images.githubusercontent.com/15875093/225984160-33ef37a8-207c-4a28-a327-54dea4784ba7.png)

Thank you for the direction! It was the line breaks.

**Comment by slimshizn** [comment]
Something to do with the latest NPM version. `2.9.19` works fine, while the last two versions do not. 

Error logs with everything above tried.

```
cont-init: info: running /etc/cont-init.d/01_perms.sh

/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_perms.sh: not found

cont-init: info: /etc/cont-init.d/01_perms.sh exited 127

cont-init: info: running /etc/cont-init.d/01_s6-secret-init.sh

/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_s6-secret-init.sh: Permission denied

cont-init: info: /etc/cont-init.d/01_s6-secret-init.sh exited 126

cont-init: info: running /etc/cont-init.d/99-themepark

/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/99-themepark: not found

cont-init: info: /etc/cont-init.d/99-themepark exited 127

cont-init: warning: some scripts exited nonzero
```

https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2705

**Comment by pbanj** [comment]
ya nothing i do will make it work. getting the same error as @slimshizn

**Comment by pbanj** [comment]
> Something to do with the latest NPM version. `2.9.19` works fine, while the last two versions do not.
> 
> Error logs with everything above tried.
> 
> ```
> cont-init: info: running /etc/cont-init.d/01_perms.sh
> 
> /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_perms.sh: not found
> 
> cont-init: info: /etc/cont-init.d/01_perms.sh exited 127
> 
> cont-init: info: running /etc/cont-init.d/01_s6-secret-init.sh
> 
> /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_s6-secret-init.sh: Permission denied
> 
> cont-init: info: /etc/cont-init.d/01_s6-secret-init.sh exited 126
> 
> cont-init: info: running /etc/cont-init.d/99-themepark
> 
> /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/99-themepark: not found
> 
> cont-init: info: /etc/cont-init.d/99-themepark exited 127
> 
> cont-init: warning: some scripts exited nonzero
> ```
> 
> [NginxProxyManager/nginx-proxy-manager#2705](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2705)

just figured it out. change `#!/usr/bin/with-contenv bash` to `#!/bin/bash` at the top of the script

**Comment by instantdreams** [comment]
> Change `#!/usr/bin/with-contenv bash` to `#!/bin/bash` at the top of the script

This absolutely worked for me too, thank you.
