### ISSUE TITLE
Cannot switch language——qBittorrent v4.5.2 Web UI (64-bit)

### ISSUE THREAD

**Issue by hululu1068** [GilbN/theme.park#484]
**Describe the bug**
Cannot switch language

**Theme Install Method** (Don't skip)
- Docker run 

**Application Info** 
- qBittorrent v4.5.2 Web UI (64-bit)

**To Reproduce**
``
docker run -d  \
  --name=qbittorrent2 \
  -e PUID=1026 \
  -e PGID=100 \
  -e TZ=Asia/Shanghai \
  -e DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent \
  -e TP_THEME=plex \
  -e WEBUI_PORT=18080 \
  -p 18080:18080 \
  -p 16881:6881 \
  -p 16881:6881/udp \
  -v /volume1/docker/qb-config:/config \
  -v /volume2/downloads/Qb:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:amd64-latest
``

**Desktop (If applicable) (please complete the following information):**
 - OS: [synology]
 - Browser [chrome, safari]
 - Version [Docker Version: 20.10.3]

<img width="761" alt="2023-03-22_00-17-29" src="https://user-images.githubusercontent.com/68652362/226676571-4af60fdc-d38e-46a5-a450-cc177f5ff8c3.png">

<img width="574" alt="2023-03-22_00-18-46" src="https://user-images.githubusercontent.com/68652362/226676815-cedadd16-a561-437b-bb2c-b8a798eb5938.png">

**Comment by GilbN** [comment]
Only English is supported using docker mods.
Use subfiltering if you need to change language.
