### ISSUE TITLE
Self-hosted deployments have a "None" SHA

### ISSUE THREAD

**Issue by RealOrangeOne** [GilbN/theme.park#493]
**Describe the bug**

When self-hosting a deployment, the `sha` querystring argument is always `None`.

**Theme Install Method** (Don't skip)

https://docs.theme-park.dev/setup/#docker

**Application Info** (Don't skip)
- Version: `latest`
- Branch
- Container
- Logs

**To Reproduce**
1. Deploy container
2. Notice `?sha=None` is appended to all URLs

**Expected behavior**

The `sha` querystring param contains a hash of the file. This isn't strictly a problem, as files are served with cache-busting headers anyway, but it's intended functionality which doesn't work.

**Screenshots**

```css
@import url("/css/base/gitea/gitea-base.css?sha=None");
@import url("/css/theme-options/plex.css?sha=None");
```

**Additional context**

The cause of the problem seems to be running `themes.py` inside the container. `themes.py` assumes it's running in a git repository, and calls out to `git` to collect file hashes. This could instead be replaced with `hashlib`, and have `themes.py` calculate the hashes itself. This would likely slow down startup, but not by a noticable amount.

**Comment by GilbN** [comment]
Can you test develop?
