### ISSUE TITLE
orgarr.css theme isn't view able anymore with the new V3 (latest version)

### ISSUE THREAD

**Issue by TRaSH-** [gilbN/theme.park#5]
orgarr.css theme isn't view able anymore with the new V3 (latest version)
The text is hard to read,
i've added some example screenshots

![image](https://user-images.githubusercontent.com/6155095/55673662-34343780-58ab-11e9-9c5f-5d7d1c08e98f.png)

![image](https://user-images.githubusercontent.com/6155095/55673694-85442b80-58ab-11e9-8a8b-a64b60fcfb0d.png)

**Comment by mouzzampk2014** [comment]
Yes agreed! I am having difficulties reading too.

**Comment by gilbN** [comment]
Yeah they changed all the css selectors om the last update, havent had any time to fix it.

**Comment by TRaSH-** [comment]
perhaps better wait till it's final, release ready.
you're right.
thnx for the heads up so i know it isn't only on my side

**Comment by gilbN** [comment]
@TRaSH- @mouzzampk2014  This should be fixed now. Please try it.
