### ISSUE TITLE
Stylesheets loaded in backwards order with docker mods

### ISSUE THREAD

**Issue by zb140** [GilbN/theme.park#502]
**Describe the bug**

Since the change to docker mods to load the stylesheets under `<body>` instead of `<head>`, the sheets are being loaded in the opposite order from what they previously were.  This is causing my custom theme to break because the variables it defines are being overridden by values in the `base.css` file.

**Theme Install Method** docker mods
- Docker run / Compose Config

<details>
<summary>Sonarr log example</summary>

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding gilbn/theme.park:sonarr to container
[mod-init] Downloading gilbn/theme.park:sonarr from registry-1.docker.io
[mod-init] Installing gilbn/theme.park:sonarr
[mod-init] gilbn/theme.park:sonarr applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1002
───────────────────────────────────────
---------------------------
|  Sonarr theme.park Mod  |
---------------------------
Variables set:
'TP_DOMAIN'=novinha:8080
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=http
'TP_ADDON'=sonarr-calendar
'TP_THEME'=tender
---------------------------
|  Adding the stylesheet  |
---------------------------
Stylesheet set to tender
Added custom addon: sonarr-calendar
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.10.1567 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] Router: Application mode: Interactive 
```

</details>

**Application Info** (Don't skip)
- Version
Sonarr 3.0.10.1567
- Branch
latest
- Container
lsio

**Additional context**
The reason it's loading backwards is because the `sed` command is replacing an opening tag rather than a closing tag, meaning that the second replacement actually gets inserted before the first one.  I _may_ be able to work around this by judicious use of `!important` but I haven't tried it yet, and it really feels like the theme file should be loaded after the base file anyway. I'm happy to try to put together a PR, or happy to leave it to someone with more experience in the code base, as you see fit :smile:

**Comment by GilbN** [comment]
Hm. I see. Yeah, sure you can make a PR one the *arr mods that are affected. Make the pr on the develop branch.

**Comment by GilbN** [comment]
new mods built with tag `<app>-develop`
