### ISSUE TITLE
Grafana 7.0 compatibility

### ISSUE THREAD

**Issue by Beet4** [gilbN/theme.park#61]
Some elements are not themed properly after update to Grafana 7.0 such as tables:
![image](https://user-images.githubusercontent.com/38279393/84369214-cf731c00-abd6-11ea-8dcf-da53248a3f3e.png)

The edit-screen of panels is not themed at all:
![image](https://user-images.githubusercontent.com/38279393/84369398-0ea16d00-abd7-11ea-8688-c8619278aa4b.png)

Select dashboard is also not themed:
![image](https://user-images.githubusercontent.com/38279393/84369442-1c56f280-abd7-11ea-988c-2c818f0e4107.png)

I guess there is more as much of the design was changed in 7.0

**Comment by gilbN** [comment]
relates to https://github.com/gilbN/theme.park/issues/45

Will see if I have time this weekend

**Comment by gilbN** [comment]
Should be good now. Let me know if you find more.
