### ISSUE TITLE
Missing Radarr 4K Logo

### ISSUE THREAD

**Issue by StudentOf33** [gilbN/theme.park#63]
Hello,

I have successfully imported the Radarr 4K CSS theme, however it appears that a link is broken and does not display the Radarr 4K logo in the upper-left hand corner. I checked the code, and found the problem below:

`background-image: url("https://gflix.app/theme.park/CSS/addons/radarr/radarr4k-v3.png");`

This is pointing to a website that is no longer in service. I believe the URL needs to be updated to reflect the Github path, as the 'radarr4k-v3.png' file is hosted here:

`https://github.com/gilbN/theme.park/blob/master/CSS/addons/radarr/radarr4k-v3.png`

Please let me know if you need more information. Thank you for all of the hard work!

**Comment by gilbN** [comment]
woops

**Comment by gilbN** [comment]
fixed. Thanks.
