### ISSUE TITLE
Space Gray

### ISSUE THREAD

**Issue by DirtyCajunRice** [gilbN/theme.park#69]
Refresh button for rutorrent is massive. Can it be resized/changed to match the theme?
https://images.cajun.pro/7ac5b/ZUWoNUri49.png/raw
Also can the font be thicker? The pencil thin font that is inherited from the default is rough

**Comment by gilbN** [comment]
Sure, I'll look into it.

**Comment by gilbN** [comment]
Btw if you turn in "Alternate homepage titles" the refresh button will be smaller. 

![image](https://user-images.githubusercontent.com/24592972/87391572-4707e280-c5ab-11ea-9a8a-6641386c3619.png)

**Comment by gilbN** [comment]
Better? 

![image](https://user-images.githubusercontent.com/24592972/87395071-0317dc00-c5b1-11ea-9bce-ec81aefe0a13.png)
