### ISSUE TITLE
[New Theme Request] Stash

### ISSUE THREAD

**Issue by rg9400** [GilbN/theme.park#73]
This is an upcoming project for a web-based organizer for *cough* adult media. It has a few things that require smoothening out, but the work being done is excellent (especially on building out and connecting to a backend metadata provider like TPDB or Stash-Box). I honestly think this is one of the coolest apps being developed, if you don't mind the nature or stigma around its theme. I listed out its main competitor below as well

https://github.com/stashapp/stash
https://github.com/boi123212321/porn-vault

**Comment by GilbN** [comment]
Closing this as I dont plan on theming this in the foreseeable future :)
