### ISSUE TITLE
[New Theme Request] XBVR

### ISSUE THREAD

**Issue by rg9400** [GilbN/theme.park#74]
Sorry for so many requests, but figured I might as well get all of them out there at once. 

XBVR is another *cough* adult themed application built around adult VR videos. Unlike Stash, it just works, with a fairly slick UI and easy setup. It's already fairly functional with automated scraping, fairly robust matching, a DLNA server for most client support, as well as native DeoVR support

https://github.com/xbapps/xbvr

**Comment by GilbN** [comment]
Closing this as I dont plan on theming this in the foreseeable future :)
