### ISSUE TITLE
[Bug] Backgrounds do not display on Edge (Android)

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#75]
I was trying out the Edge browser on Android, and I noticed that the blur background does not render properly. It works for some pages like Sonarr/Radarr, but not Tautulli or NZBGet. I didn't do a full analysis of each theme I use just in case there was some obvious reason for this behavior.

EDIT: Did some testing, here are the below apps that had some issues
1. Tautulli (no background for the entire page except header)
2. NZGet (no background for half the page)
3. Calibre (header has no background)
4. qBittorrent (entire login page has no background, once logged in, background renders fine)
5. Guacamole (entire login page has no background, once logged in, half the background renders, other half is missing)

Below apps were fine
1. Sonarr/Radarr/Lidarr/Readarr/Bazarr
2. Synclounge
3. NZBHydra 2
4. Lazylibrarian (sometimes background does not render, is intermittent and does eventually load)
5. Monitorr (takes a while, but background does eventually load)
6. Grafana
7. Deluge
8. Filebrowser
9. Ombi (v4)
10. Plex

Worth noting that it works perfectly in the current Chrome dev build, so even though Edge is built on Chromium, there's something specific to that browser.

Edge version: 45.06.24.5043
Android version: Android 9

![tautulli](https://user-images.githubusercontent.com/39887349/89701699-fca22900-d8fe-11ea-8b68-f9b2ec933f78.jpg)
![nzbget](https://user-images.githubusercontent.com/39887349/89701702-fd3abf80-d8fe-11ea-8ee3-80824215d628.jpg)

**Comment by gilbN** [comment]
Hm, wierd. I don't have an android device, so I can really test. Edge on ios is webkit so that works as expected. Does the colors work ok with the organizr-dark theme?

**Comment by rg9400** [comment]
Yeah the Organizr-Dark theme works perfectly. Must be the gradient stuff then?

**Comment by gilbN** [comment]
Yup, I guess their version doesn't support it. Its the same with Firefox.

**Comment by rg9400** [comment]
Strange since, unlike Firefox, it's still Chromium under the hood. Either way, I've shifted to the new Organizr Dark theme which looks amazing and also works perfectly on all my devices!

**Comment by gilbN** [comment]
Yeah I'm guessing it will be fixed in the future. 
Same here😄
