### ISSUE TITLE
Discover poster with title

### ISSUE THREAD

**Issue by reloxx13** [gilbN/theme.park#76]
radarr space-grey

text not readable

![grafik](https://user-images.githubusercontent.com/14855001/89726423-ab875780-da1a-11ea-924b-8604d49ee452.png)

**Comment by reloxx13** [comment]
my fix
```
/* Movie Title in discover */
.AddListMoviePoster-title-2qKvg{
	font-size: 13px;
	font-weight: bold;
	background-color: rgba(0, 0, 0, .7);
}
```

**Comment by gilbN** [comment]
Thanks for the issue, should be good now.
