### ISSUE TITLE
Radarr success no difference in space grey

### ISSUE THREAD

**Issue by reloxx13** [gilbN/theme.park#78]
![grafik](https://user-images.githubusercontent.com/14855001/89726589-4df40a80-da1c-11ea-9a1c-6b188231111b.png)

should be green or dark green

i use this now:
```
.Label-success-1pfcC {
    border-color: #1b8033;
    background-color: #1b8033;
    color: #eee;
}
```

![grafik](https://user-images.githubusercontent.com/14855001/89726610-7ed43f80-da1c-11ea-84da-507cfd57a1b7.png)

**Comment by gilbN** [comment]
Thanks for the issue, should be good now.

**Comment by reloxx13** [comment]
i would suggest to not override the success badge style, its a state info and not an accent.
