### ISSUE TITLE
Switching to CDN

### ISSUE THREAD

**Issue by camjac251** [gilbN/theme.park#79]
I tried to find info on if GitHub Pages used a CDN on the backend but I don't believe they do.

I found two CDNs that work with GitHub directly that might be interesting to use. GitCDN and Statically.

GitCDN (https://github.com/schme16/gitcdn.xyz) and Statically (https://statically.io) both offer minifying on the fly as well which is an added bonus
https://min.gitcdn.xyz for GitCDN.

Statically might be faster since it has a larger offering of CDNs but not sure.

**Comment by camjac251** [comment]
Here's what the URLs would be if a CDN was used

For normal (no minification) CDN
https://cdn.statically.io/gh/gilbN/theme.park/master/CSS/themes
https://gitcdn.xyz/cdn/gilbN/theme.park/master/CSS/themes

Minifying on server before serving (on first load it serves unminified version if it hasn't been before)
https://min.statically.io/gh/gilbN/theme.park/master/CSS/themes
https://min.gitcdn.xyz/cdn/gilbN/theme.park/master/CSS/themes

**Comment by gilbN** [comment]
Did you notice a speed difference?
