### ISSUE TITLE
Orgarr.css Sonarr V3 text unreadable

### ISSUE THREAD

**Issue by henrywhitaker3** [gilbN/theme.park#8]
Using the orgarr.css file through nginx, some of the ui of sonarr v3 has become unreadable
![sonarr theme park](https://user-images.githubusercontent.com/36062479/59552956-48687500-8f7d-11e9-8362-afe1b0566e28.png)

![sonarr v3 theme park](https://user-images.githubusercontent.com/36062479/59552951-2111a800-8f7d-11e9-81e1-9f28f0e7ef0f.png)

**Comment by gilbN** [comment]
Tried clearing cache? If youre using cloudflare you need to clear it there also.

**Comment by henrywhitaker3** [comment]
Cleared cache and not using cloudflare

The div with class starting `SeriesIndexPoster` have the CSS `background-color: #fafbfc` which toggles it

![sonarr theme debug](https://user-images.githubusercontent.com/36062479/59553229-a13a0c80-8f81-11e9-8e3c-846d7fb03335.png)

but then there's still a white bit left when that's toggled off which is for the 'Next Airing' section

![sonarr theme debug 2](https://user-images.githubusercontent.com/36062479/59553249-eb22f280-8f81-11e9-842c-bde035fd2a94.png)

**Comment by gilbN** [comment]
Which version of sonarrv3 are you using?

**Comment by henrywhitaker3** [comment]
Sonarr version: 3.0.0.348
Mono version: 5.20.1.19

**Comment by gilbN** [comment]
If you are using docker please switch to `linuxserver/sonarr:preview`

**Comment by henrywhitaker3** [comment]
Yup that's sorted it, had to change apt repo to the Debian 9 version which then had an update for sonarr, which then showed an available update within the sonarr ui. So I think for any users using the Debian 8 'Jessie' repo for sonarr, orgarr.css will be broken for it

**Comment by gilbN** [comment]
Yeah, they recently changed almost all the css selectors in an update.  I had to basically make the theme again from scratch. https://github.com/gilbN/theme.park/issues/5#issuecomment-480527799
