### ISSUE TITLE
"Close Splash" misplaced in Organizr V2

### ISSUE THREAD

**Issue by klausmcm** [gilbN/theme.park#80]
See screenshot. The **Close Splash** button is misplaced behind another icon.

![Screenshot_2020-08-10 Settings - Organizr V2](https://user-images.githubusercontent.com/14914359/89808359-e35fcf00-daee-11ea-9bb3-b62cb6995434.png)

Happens in **Firefox v68** and **Chromium v83**.

**Comment by gilbN** [comment]
I see I removed the tab names, I'll look into adding those back.
