### ISSUE TITLE
[Radarr Aphrodite] Custom Formats "Required" color

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#81]
It's hard to distinguish the Required color in Aphrodite's custom formats because it matches the condition label. Negate has it's own color, and Radarr's default color for the success label looks good here, maybe the theme color can be removed for the required label?

Current:
![image](https://user-images.githubusercontent.com/39887349/90326098-dce7b200-df49-11ea-9d5d-fc8b59f40d69.png)

Without the theme background override:
![image](https://user-images.githubusercontent.com/39887349/90326115-115b6e00-df4a-11ea-8a52-b068f8d2d750.png)

**Comment by gilbN** [comment]
Yup, fixed.
