### ISSUE TITLE
add theme support for some of the commonly used rutorrent plugins

### ISSUE THREAD

**Issue by BrandonG777** [gilbN/theme.park#83]
autodl-irssi, ratio rules, and URL replacement in RSS are three commonly used rutorrent plugins that currently have some rendering issues. It would be nice if support was added for these...

![image](https://user-images.githubusercontent.com/1915294/90821761-0cefd600-e2f9-11ea-9012-f44029f8fc11.png)
![image](https://user-images.githubusercontent.com/1915294/90821860-327cdf80-e2f9-11ea-9f72-8544a0f2406a.png)

![image](https://user-images.githubusercontent.com/1915294/90821786-137e4d80-e2f9-11ea-825e-43611b35951d.png)

**Comment by gilbN** [comment]
Should be fixed now.
