### ISSUE TITLE
[New Theme Request] Resilio Sync

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#87]
Resilio Sync is a software that can be used headless with a webUI. It allows you to sync files and folders across multiple locations in real time. 

https://www.resilio.com/individuals/

**Comment by gilbN** [comment]
Added. 
I dont use it, so there are definitively some bugs.
I know there are some with the svg icons they used. I got lazy and  havent changed them. Need to host them on github with new colors.
