### ISSUE TITLE
Lidarr - Import ...

### ISSUE THREAD

**Issue by goldenpipes** [gilbN/theme.park#9]
orgarr-plex.css

lidarr version 0.6.2.883

Looks like the selector isn't correct?

![image](https://user-images.githubusercontent.com/6140137/59853252-17e65980-9336-11e9-9240-7eba51431380.png)

**Comment by gilbN** [comment]
Thanks! 
Fixed on https://github.com/gilbN/theme.park/commit/7bcc87d45c37de14347ce040b001f3f00de955f6
