### ISSUE TITLE
[New Theme Request] gitea

### ISSUE THREAD

**Issue by systemofapwne** [gilbN/theme.park#91]
I would love to see themepark to support gitea. Gitea is a self-hosted git repo management system like github or gitlab.

https://github.com/go-gitea/gitea

**Comment by gilbN** [comment]
There is a gitea branch now, that I've made some progress on. But theres still lots to do.

**Comment by gilbN** [comment]
Changes are now in master, about 90% done.

**Comment by gilbN** [comment]
Should be about 99% finished now: 
Instructions here: https://github.com/gilbN/theme.park/wiki/Gitea
Let me know if you find any bugs
