### ISSUE TITLE
[New Theme Request] Channels DVR

### ISSUE THREAD

**Issue by bnhf** [GilbN/theme.park#93]
Channels DVR is an outstanding compliment to a Sonarr/Radarr setup. It's specifically for live TV -- using an HDHomeRun, TV Everywhere (cable or satellite credentials work best) or Locast for content. Though I also use Plex, I find Channels DVR much nicer for live TV and specifically live sports.

The web interface for managing the Channels DVR server would really benefit from a Theme.Park makeover!

**Comment by gilbN** [comment]
Do you have a link to the repo?

**Comment by bnhf** [comment]
Like Plex, it's not open source -- but the Channels DVR Server download can be found at:

https://getchannels.com/dvr-server/

**Comment by GilbN** [comment]
Sorry. Looks like this need a subscription and or an HDHomeRun to be able to theme. So that's not happening :)
