### ISSUE TITLE
[BUG] Adguard - Hover over eye icon - Unable to read content

### ISSUE THREAD

**Issue by yurividal** [gilbN/theme.park#96]
![image](https://user-images.githubusercontent.com/8555749/94437995-69ff6700-0196-11eb-9150-b14b6b107dd4.png)

Happens when you hover the mouse over the eye icon to see details about a certain domain.

**Comment by gilbN** [comment]
Hi. Which browser are you using?

**Comment by yurividal** [comment]
Tried chrome, Edge(Chromium) and Firefox.
It works on Firefox, but is broken on the other 2.

**Comment by yurividal** [comment]
There is also white text on white BG on /#logs?response_status=all
![image](https://user-images.githubusercontent.com/8555749/94467698-384cc700-01bb-11eb-998f-f246e4b2b6d8.png)

and when setting a tag for a Client:
![image](https://user-images.githubusercontent.com/8555749/94467841-692cfc00-01bb-11eb-98c9-f1615e72d1d7.png)

**Comment by gilbN** [comment]
I'll try and look at the new client stuff this weekend. That was a tough nut.

**Comment by yurividal** [comment]
Found one more issue. Menu is transparent on mobile. 

![Screenshot_20201002-091113_Samsung Internet Beta](https://user-images.githubusercontent.com/8555749/94902084-8bf73300-048f-11eb-98bf-103612c1c302.png)
