### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bchilton9** [gilbN/theme.park#98]
I am new to this and trying to get it working.

I am using xampp and everything works other then the themes

where do I put the apache <location /sonarr> code?

everywhere I have tried has not worked. Thank you

**Comment by gilbN** [comment]
I havent used apache before. The example in setup didnt work? https://github.com/gilbN/theme.park/wiki/Setup#example-1

**Comment by bchilton9** [comment]
I can’t figure out where to put the example. I tried the httpd but then Apache would not start

**Comment by gilbN** [comment]
Do you have a working reverse proxy for sonarr with Apace?

**Comment by bchilton9** [comment]
No. I don’t know where to put the code.

**Comment by gilbN** [comment]
If you where to switch to Nginx I could help you. I recommend this container. https://github.com/linuxserver/docker-swag
